//generated by gpt-5<noreply@openai.com> @ codex
#include "deque.h"

#include "alloc.h"

static usize deque_physical_index(const Deque *deque, usize index)
{
	return (deque->first + index) % deque->cap;
}

static void *deque_slot(const Deque *deque, usize index)
{
	return raw_buf_get(&deque->data, index);
}

ResultDeque deque_new(TypeDesc elem)
{
	ResultRawBuf result;
	Deque deque;

	if (elem.size == 0) {
		return DequeErr(ERROR_INVALID_ARGUMENT);
	}
	result = raw_buf_new(elem.size);
	if (RawBuf_is_err(&result)) {
		return DequeErr(RawBuf_error(&result));
	}
	deque = (Deque){
		.data = RawBuf_unwrap(&result),
		.elem = elem,
		.first = 0,
		.last = 0,
		.len = 0,
		.cap = 0,
	};
	return DequeOk(deque);
}

usize deque_len(const Deque *deque)
{
	return deque->len;
}

usize deque_capacity(const Deque *deque)
{
	return deque->cap;
}

bool deque_is_empty(const Deque *deque)
{
	return deque->len == 0;
}

i32 deque_reserve(Deque *deque, usize additional)
{
	ResultRawBuf result;
	RawBuf grown;
	usize required;
	usize i;

	if (additional > (usize)-1 - deque->len) {
		return -1;
	}
	required = deque->len + additional;
	if (required <= deque->cap) {
		return 0;
	}
	result = raw_buf_new(deque->elem.size);
	if (RawBuf_is_err(&result)) {
		return -1;
	}
	grown = RawBuf_unwrap(&result);
	if (raw_buf_reserve(&grown, required) != 0) {
		raw_buf_drop(&grown);
		return -1;
	}
	for (i = 0; i < deque->len; ++i) {
		memcpy(
			raw_buf_get(&grown, i),
			deque_slot(deque, deque_physical_index(deque, i)),
			deque->elem.size
		);
	}
	raw_buf_drop(&deque->data);
	deque->data = grown;
	deque->cap = grown.cap;
	deque->first = 0;
	deque->last = deque->len == deque->cap ? 0 : deque->len;
	return 0;
}

static i32 deque_push_impl(
	Deque *deque,
	const void *value,
	bool front,
	bool clear_source
)
{
	usize index;
	void *slot;

	if (value == NULL || deque_reserve(deque, 1) != 0) {
		return -1;
	}
	if (front) {
		deque->first =
			deque->first == 0 ? deque->cap - 1 : deque->first - 1;
		index = deque->first;
	} else {
		index = deque->last;
		deque->last = (deque->last + 1) % deque->cap;
	}
	slot = deque_slot(deque, index);
	if (clear_source) {
		obj_move(deque->elem, slot, (void *)value);
	} else {
		memcpy(slot, value, deque->elem.size);
	}
	deque->len++;
	return 0;
}

i32 deque_push_front(Deque *deque, void *value)
{
	return deque_push_impl(deque, value, true, true);
}

i32 deque_push_back(Deque *deque, void *value)
{
	return deque_push_impl(deque, value, false, true);
}

i32 deque_push_front_raw(Deque *deque, const void *value)
{
	return deque_push_impl(deque, value, true, false);
}

i32 deque_push_back_raw(Deque *deque, const void *value)
{
	return deque_push_impl(deque, value, false, false);
}

static i32 deque_take(Deque *deque, usize index, void *out)
{
	void *slot = deque_slot(deque, index);

	if (out == NULL) {
		obj_drop(deque->elem, slot);
	} else {
		obj_move(deque->elem, out, slot);
	}
	return 0;
}

i32 deque_pop_front(Deque *deque, void *out)
{
	usize index;

	if (deque->len == 0) {
		return ERROR_EMPTY;
	}
	index = deque->first;
	deque->first = (deque->first + 1) % deque->cap;
	deque->len--;
	(void)deque_take(deque, index, out);
	if (deque->len == 0) {
		deque->first = deque->last;
	}
	return 0;
}

i32 deque_pop_back(Deque *deque, void *out)
{
	if (deque->len == 0) {
		return ERROR_EMPTY;
	}
	deque->last = deque->last == 0 ? deque->cap - 1 : deque->last - 1;
	deque->len--;
	(void)deque_take(deque, deque->last, out);
	if (deque->len == 0) {
		deque->first = deque->last;
	}
	return 0;
}

const void *deque_get(const Deque *deque, usize index)
{
	if (index >= deque->len) {
		return NULL;
	}
	return deque_slot(deque, deque_physical_index(deque, index));
}

void *deque_get_mut(Deque *deque, usize index)
{
	return (void *)deque_get(deque, index);
}

const void *deque_front(const Deque *deque)
{
	return deque_get(deque, 0);
}

void *deque_front_mut(Deque *deque)
{
	return deque_get_mut(deque, 0);
}

const void *deque_back(const Deque *deque)
{
	if (deque->len == 0) {
		return NULL;
	}
	return deque_get(deque, deque->len - 1);
}

void *deque_back_mut(Deque *deque)
{
	if (deque->len == 0) {
		return NULL;
	}
	return deque_get_mut(deque, deque->len - 1);
}

void deque_clear(Deque *deque)
{
	while (deque->len != 0) {
		(void)deque_pop_back(deque, NULL);
	}
}

void deque_drop(void *self)
{
	Deque *deque = self;

	deque_clear(deque);
	raw_buf_drop(&deque->data);
	memset(deque, 0, sizeof(*deque));
}

void *deque_clone_obj(const void *source_ptr)
{
	const Deque *source = source_ptr;
	Deque *copy;
	ResultDeque result;
	usize i;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	result = deque_new(source->elem);
	if (Deque_is_err(&result)) {
		free(copy);
		return NULL;
	}
	*copy = Deque_unwrap(&result);
	if (deque_reserve(copy, source->len) != 0) {
		deque_drop(copy);
		free(copy);
		return NULL;
	}
	for (i = 0; i < source->len; ++i) {
		const void *value = deque_get(source, i);

		if (is_copy(source->elem)) {
			if (deque_push_back_raw(copy, value) != 0) {
				deque_drop(copy);
				free(copy);
				return NULL;
			}
		} else {
			void *cloned = obj_clone(source->elem, value);

			if (cloned == NULL ||
			    deque_push_back(copy, cloned) != 0) {
				if (cloned != NULL) {
					obj_drop(source->elem, cloned);
					free(cloned);
				}
				deque_drop(copy);
				free(copy);
				return NULL;
			}
			free(cloned);
		}
	}
	return copy;
}

ResultDeque deque_clone(const Deque *source)
{
	Deque *copy = deque_clone_obj(source);
	Deque value;

	if (copy == NULL) {
		return DequeErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return DequeOk(value);
}
