//generated by gpt-5<noreply@openai.com> @ codex
#ifndef SHYOS_DEQUE_H
#define SHYOS_DEQUE_H

#include "obj.h"
#include "rawbuf.h"
#include "result.h"

typedef struct Deque Deque;
struct Deque {
	RawBuf data;
	TypeDesc elem;
	usize first;
	usize last;
	usize len;
	usize cap;
};

void deque_drop(void *self);
void *deque_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(Deque, deque_drop, deque_clone_obj)

ResultDeque deque_new(TypeDesc elem);
ResultDeque deque_clone(const Deque *source);

usize deque_len(const Deque *deque);
usize deque_capacity(const Deque *deque);
bool deque_is_empty(const Deque *deque);

i32 deque_reserve(Deque *deque, usize additional);
i32 deque_push_front(Deque *deque, void *value);
i32 deque_push_back(Deque *deque, void *value);
i32 deque_push_front_raw(Deque *deque, const void *value);
i32 deque_push_back_raw(Deque *deque, const void *value);
i32 deque_pop_front(Deque *deque, void *out);
i32 deque_pop_back(Deque *deque, void *out);

const void *deque_get(const Deque *deque, usize index);
void *deque_get_mut(Deque *deque, usize index);
const void *deque_front(const Deque *deque);
void *deque_front_mut(Deque *deque);
const void *deque_back(const Deque *deque);
void *deque_back_mut(Deque *deque);

void deque_clear(Deque *deque);

#endif /* SHYOS_DEQUE_H */
