//generated by gpt-5<noreply@openai.com> @ codex
#![no_std]

use core::ffi::c_void;
use core::marker::PhantomData;
use core::mem::{align_of, size_of, ManuallyDrop, MaybeUninit};
use core::ops::{Index, IndexMut};
use core::ptr;
use shyos_obj::TypeDesc;
use shyos_rawbuf::RawBuf;
use shyos_result::{CResult, ERROR_INVALID_ARGUMENT, ERROR_NO_VALUE, ERROR_OUT_OF_MEMORY};

#[repr(C)]
pub struct RawDeque {
    pub data: RawBuf,
    pub elem: TypeDesc,
    pub first: usize,
    pub last: usize,
    pub len: usize,
    pub cap: usize,
}

unsafe extern "C" {
    #[link_name = "deque_new"]
    fn c_deque_new(elem: TypeDesc) -> CResult<RawDeque>;
    #[link_name = "deque_reserve"]
    fn c_deque_reserve(deque: *mut RawDeque, additional: usize) -> i32;
    #[link_name = "deque_push_front_raw"]
    fn c_deque_push_front_raw(deque: *mut RawDeque, value: *const c_void) -> i32;
    #[link_name = "deque_push_back_raw"]
    fn c_deque_push_back_raw(deque: *mut RawDeque, value: *const c_void) -> i32;
    #[link_name = "deque_pop_front"]
    fn c_deque_pop_front(deque: *mut RawDeque, out: *mut c_void) -> i32;
    #[link_name = "deque_pop_back"]
    fn c_deque_pop_back(deque: *mut RawDeque, out: *mut c_void) -> i32;
    #[link_name = "deque_get"]
    fn c_deque_get(deque: *const RawDeque, index: usize) -> *const c_void;
    #[link_name = "deque_get_mut"]
    fn c_deque_get_mut(deque: *mut RawDeque, index: usize) -> *mut c_void;
    #[link_name = "deque_clear"]
    fn c_deque_clear(deque: *mut RawDeque);
    #[link_name = "deque_drop"]
    fn c_deque_drop(deque: *mut RawDeque);
}

pub unsafe fn deque_get_raw(deque: *const RawDeque, index: usize) -> *const c_void {
    unsafe { c_deque_get(deque, index) }
}

unsafe extern "C" fn drop_element<T>(value: *mut c_void) {
    unsafe { ptr::drop_in_place(value.cast::<T>()) }
}

fn type_desc<T>() -> TypeDesc {
    TypeDesc {
        size: size_of::<T>(),
        drop: Some(drop_element::<T>),
        clone: None,
    }
}

#[repr(transparent)]
pub struct CDeque<T> {
    pub raw: RawDeque,
    marker: PhantomData<T>,
}

pub struct Iter<'a, T> {
    deque: &'a CDeque<T>,
    index: usize,
}

unsafe impl<T: Send> Send for CDeque<T> {}
unsafe impl<T: Sync> Sync for CDeque<T> {}

impl<T> CDeque<T> {
    pub fn new() -> CResult<Self> {
        if size_of::<T>() == 0 || align_of::<T>() > align_of::<usize>() {
            return CResult::err(ERROR_INVALID_ARGUMENT);
        }
        match unsafe { c_deque_new(type_desc::<T>()) } {
            CResult::Ok(raw) => CResult::ok(Self {
                raw,
                marker: PhantomData,
            }),
            CResult::Err(error) => CResult::err(error),
        }
    }

    pub fn with_capacity(capacity: usize) -> CResult<Self> {
        let mut deque = match Self::new() {
            CResult::Ok(deque) => deque,
            CResult::Err(error) => return CResult::err(error),
        };
        if let CResult::Err(error) = deque.reserve(capacity) {
            return CResult::err(error);
        }
        CResult::ok(deque)
    }

    pub fn len(&self) -> usize {
        self.raw.len
    }

    pub fn capacity(&self) -> usize {
        self.raw.cap
    }

    pub fn is_empty(&self) -> bool {
        self.raw.len == 0
    }

    pub fn reserve(&mut self, additional: usize) -> CResult<()> {
        if unsafe { c_deque_reserve(&mut self.raw, additional) } == 0 {
            CResult::ok(())
        } else {
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn push_front(&mut self, value: T) -> CResult<()> {
        self.push(value, true)
    }

    pub fn push_back(&mut self, value: T) -> CResult<()> {
        self.push(value, false)
    }

    fn push(&mut self, value: T, front: bool) -> CResult<()> {
        let value = ManuallyDrop::new(value);
        let status = unsafe {
            if front {
                c_deque_push_front_raw(&mut self.raw, (&*value as *const T).cast())
            } else {
                c_deque_push_back_raw(&mut self.raw, (&*value as *const T).cast())
            }
        };
        if status == 0 {
            CResult::ok(())
        } else {
            drop(ManuallyDrop::into_inner(value));
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn pop_front(&mut self) -> CResult<T> {
        self.pop(true)
    }

    pub fn pop_back(&mut self) -> CResult<T> {
        self.pop(false)
    }

    fn pop(&mut self, front: bool) -> CResult<T> {
        let mut value = MaybeUninit::<T>::uninit();
        let status = unsafe {
            if front {
                c_deque_pop_front(&mut self.raw, value.as_mut_ptr().cast())
            } else {
                c_deque_pop_back(&mut self.raw, value.as_mut_ptr().cast())
            }
        };
        if status == 0 {
            CResult::ok(unsafe { value.assume_init() })
        } else {
            CResult::err(ERROR_NO_VALUE)
        }
    }

    pub fn get(&self, index: usize) -> Option<&T> {
        unsafe { c_deque_get(&self.raw, index).cast::<T>().as_ref() }
    }

    pub fn get_mut(&mut self, index: usize) -> Option<&mut T> {
        unsafe { c_deque_get_mut(&mut self.raw, index).cast::<T>().as_mut() }
    }

    pub fn front(&self) -> Option<&T> {
        self.get(0)
    }

    pub fn front_mut(&mut self) -> Option<&mut T> {
        self.get_mut(0)
    }

    pub fn back(&self) -> Option<&T> {
        self.len().checked_sub(1).and_then(|index| self.get(index))
    }

    pub fn back_mut(&mut self) -> Option<&mut T> {
        let index = self.len().checked_sub(1)?;
        self.get_mut(index)
    }

    pub fn iter(&self) -> Iter<'_, T> {
        Iter {
            deque: self,
            index: 0,
        }
    }

    pub fn clear(&mut self) {
        unsafe { c_deque_clear(&mut self.raw) }
    }
}

impl<'a, T> Iterator for Iter<'a, T> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        let value = self.deque.get(self.index)?;
        self.index += 1;
        Some(value)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.deque.len() - self.index;
        (remaining, Some(remaining))
    }
}

impl<T> ExactSizeIterator for Iter<'_, T> {}

impl<T: Clone> Clone for CDeque<T> {
    fn clone(&self) -> Self {
        let mut clone = Self::with_capacity(self.len()).unwrap();
        for value in self.iter() {
            clone.push_back(value.clone()).unwrap();
        }
        clone
    }
}

impl<T> Index<usize> for CDeque<T> {
    type Output = T;

    fn index(&self, index: usize) -> &Self::Output {
        self.get(index).expect("deque index out of bounds")
    }
}

impl<T> IndexMut<usize> for CDeque<T> {
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        self.get_mut(index).expect("deque index out of bounds")
    }
}

impl<'a, T> IntoIterator for &'a CDeque<T> {
    type Item = &'a T;
    type IntoIter = Iter<'a, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.iter()
    }
}

impl<T> Drop for CDeque<T> {
    fn drop(&mut self) {
        unsafe { c_deque_drop(&mut self.raw) }
    }
}
