//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//C 实现的 no_std simple allocator 最小包装

#![no_std]

use core::alloc::{GlobalAlloc, Layout};
use core::ptr;

#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
pub use shyos_alloc::{free, heap_init, malloc};

/// RAII 包装：drop 时 free。
#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
pub struct HeapBox {
    ptr: *mut u8,
    size: usize,
}

#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
impl HeapBox {
    pub fn alloc(size: usize) -> Option<Self> {
        let ptr = unsafe { malloc(size) };
        if ptr.is_null() {
            None
        } else {
            Some(Self { ptr, size })
        }
    }

    pub fn as_ptr(&self) -> *const u8 {
        self.ptr
    }

    pub fn as_mut_ptr(&mut self) -> *mut u8 {
        self.ptr
    }

    pub fn len(&self) -> usize {
        self.size
    }

    pub fn as_slice(&self) -> &[u8] {
        unsafe { core::slice::from_raw_parts(self.ptr, self.size) }
    }

    pub fn as_mut_slice(&mut self) -> &mut [u8] {
        unsafe { core::slice::from_raw_parts_mut(self.ptr, self.size) }
    }
}

#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
impl Drop for HeapBox {
    fn drop(&mut self) {
        unsafe {
            free(self.ptr);
        }
        self.ptr = ptr::null_mut();
        self.size = 0;
    }
}

/// GlobalAlloc 适配器。启用 `SHYOS_ALLOCATOR_SIMPLE` 时注册为全局分配器。
#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
pub struct SimpleAllocator;

#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
unsafe impl GlobalAlloc for SimpleAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        // simple_alloc 只保证指针宽度对齐；更大对齐失败则返回 null。
        if layout.align() > core::mem::size_of::<*mut u8>() {
            return ptr::null_mut();
        }
        malloc(layout.size())
    }

    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        free(ptr);
    }
}

#[cfg(SHYOS_ALLOCATOR_SIMPLE)]
#[global_allocator]
static GLOBAL: SimpleAllocator = SimpleAllocator;
