//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//simple allocator：固定槽位的 first-fit 堆

#include "simple_alloc.h"

#include <stdint.h>

#if defined(SHYOS_ALLOCATOR_SIMPLE)

#if defined(SHYOS_BACKEND_LINUX_USER)
#include "board.h"
#endif

struct Heap HEAP = {
	.start = NULL,
	.now = NULL,
	.cap = 0,
};

struct HeapItem HEAP_ITEM[SIMPLE_ALLOC_MAX_ITEMS];
usize HEAP_ITEM_COUNT = 0;

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//对齐到指针宽度
static usize align_up(usize value, usize align)
{
	return (value + (align - 1u)) & ~(align - 1u);
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//第 i 个已分配块的结束偏移
static usize heap_end(usize i)
{
	return HEAP_ITEM[i].from + HEAP_ITEM[i].size;
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//在 index 处插入一项，右移后续项
static i32 heap_item_insert(usize index, usize from, usize size)
{
	usize i;

	if (HEAP_ITEM_COUNT >= (usize)SIMPLE_ALLOC_MAX_ITEMS) {
		return -1;
	}
	if (index > HEAP_ITEM_COUNT) {
		return -1;
	}

	for (i = HEAP_ITEM_COUNT; i > index; --i) {
		HEAP_ITEM[i] = HEAP_ITEM[i - 1u];
	}
	HEAP_ITEM[index].from = from;
	HEAP_ITEM[index].size = size;
	HEAP_ITEM_COUNT += 1u;
	return 0;
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//删除 index 处项，左移后续项（相邻空洞自动合并）
static void heap_item_remove(usize index)
{
	usize i;

	if (index >= HEAP_ITEM_COUNT) {
		return;
	}

	for (i = index; i + 1u < HEAP_ITEM_COUNT; ++i) {
		HEAP_ITEM[i] = HEAP_ITEM[i + 1u];
	}
	HEAP_ITEM_COUNT -= 1u;
	HEAP_ITEM[HEAP_ITEM_COUNT].from = 0;
	HEAP_ITEM[HEAP_ITEM_COUNT].size = 0;
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//simple allocator 堆初始化

i32 heap_init(void *base, usize size)
{
	usize i;

	if (size == 0) {
		return -1;
	}

	/* linux 使用 sbrk */
#if defined(SHYOS_BACKEND_LINUX_USER)
	if (base == NULL) {
		base = linux_sbrk((isize)size);
	}
#endif

	if (base == NULL) {
		return -1;
	}

	HEAP.start = base;
	HEAP.now = base;
	HEAP.cap = size;
	HEAP_ITEM_COUNT = 0;
	for (i = 0; i < (usize)SIMPLE_ALLOC_MAX_ITEMS; ++i) {
		HEAP_ITEM[i].from = 0;
		HEAP_ITEM[i].size = 0;
	}
	return 0;
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//first-fit：在相邻 used 块间隙分配，最多 256 个活跃块
void *malloc(usize size)
{
	usize need;
	usize i;
	usize prev_end;
	usize gap_end;
	usize gap;
	usize from;
	usize base;

	if (size == 0 || HEAP.start == NULL || HEAP.cap == 0) {
		return NULL;
	}

	need = align_up(size, (usize)SIMPLE_ALLOC_ALIGN);
	if (need == 0) {
		return NULL;
	}

	base = (usize)HEAP.start;

	/* 扫描 used 表：gap_i = [heap_end(i-1), HEAP_ITEM[i].from) */
	prev_end = 0;
	for (i = 0; i < HEAP_ITEM_COUNT; ++i) {
		gap_end = HEAP_ITEM[i].from;
		if (gap_end < prev_end) {
			return NULL;
		}
		gap = gap_end - prev_end;
		if (gap >= need) {
			from = prev_end;
			if (heap_item_insert(i, from, need) != 0) {
				return NULL;
			}
			HEAP.now = (void *)(base + heap_end(i));
			return (void *)(base + from);
		}
		prev_end = heap_end(i);
	}

	/* 尾部空洞：[last_end, HEAP.cap) */
	if (HEAP.cap < prev_end) {
		return NULL;
	}
	gap = HEAP.cap - prev_end;
	if (gap < need) {
		return NULL;
	}
	from = prev_end;
	if (heap_item_insert(HEAP_ITEM_COUNT, from, need) != 0) {
		return NULL;
	}
	HEAP.now = (void *)(base + from + need);
	return (void *)(base + from);
}

//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//按指针定位并移除 used 项；相邻 free 区通过表压缩自动合并
void free(void *ptr)
{
	usize i;
	usize offset;
	usize base;
	usize addr;

	if (ptr == NULL || HEAP.start == NULL) {
		return;
	}

	base = (usize)HEAP.start;
	addr = (usize)ptr;
	if (addr < base) {
		return;
	}
	offset = (usize)(addr - base);
	if (offset >= HEAP.cap) {
		return;
	}

	for (i = 0; i < HEAP_ITEM_COUNT; ++i) {
		if (HEAP_ITEM[i].from == offset) {
			heap_item_remove(i);
			if (HEAP_ITEM_COUNT == 0) {
				HEAP.now = HEAP.start;
			} else {
				HEAP.now = (void *)(base +
					heap_end(HEAP_ITEM_COUNT - 1u));
			}
			return;
		}
	}
}

#endif /* SHYOS_ALLOCATOR_SIMPLE */
