//generated by gpt-5<noreply@openai.com> @ codex
//simple allocator 实现状态

#ifndef SHYOS_SIMPLE_ALLOC_H
#define SHYOS_SIMPLE_ALLOC_H

#include "alloc.h"

struct Heap {
	void *start;
	void *now;
	usize cap;
};

struct HeapItem {
	usize from;
	usize size;
};

enum {
	SIMPLE_ALLOC_MAX_ITEMS = 256,
	SIMPLE_ALLOC_ALIGN = sizeof(void *)
};

extern struct Heap HEAP;
extern struct HeapItem HEAP_ITEM[SIMPLE_ALLOC_MAX_ITEMS];
extern usize HEAP_ITEM_COUNT;

#endif /* SHYOS_SIMPLE_ALLOC_H */
