//generated by grok-4.5<noreply@x.ai> @ cursor
#include "binary_heap.h"

#include "alloc.h"
#include "string_noalloc.h"

static void *heap_ptr(const BinaryHeap *heap, usize index)
{
	return raw_buf_get(&heap->raw, index);
}

static void heap_swap(BinaryHeap *heap, usize i, usize j)
{
	u8 *a = heap_ptr(heap, i);
	u8 *b = heap_ptr(heap, j);
	usize n = heap->elem.size;

	while (n > 0) {
		u8 tmp;

		n--;
		tmp = a[n];
		a[n] = b[n];
		b[n] = tmp;
	}
}

static void sift_up(BinaryHeap *heap, usize index)
{
	while (index > 0) {
		usize parent = (index - 1) / 2;

		if (heap->cmp(heap_ptr(heap, index), heap_ptr(heap, parent)) <= 0) {
			break;
		}
		heap_swap(heap, index, parent);
		index = parent;
	}
}

static void sift_down(BinaryHeap *heap, usize index)
{
	for (;;) {
		usize left = index * 2 + 1;
		usize right = left + 1;
		usize best = index;

		if (left < heap->len &&
		    heap->cmp(heap_ptr(heap, left), heap_ptr(heap, best)) > 0) {
			best = left;
		}
		if (right < heap->len &&
		    heap->cmp(heap_ptr(heap, right), heap_ptr(heap, best)) > 0) {
			best = right;
		}
		if (best == index) {
			break;
		}
		heap_swap(heap, index, best);
		index = best;
	}
}

static void heap_drop_item(BinaryHeap *heap, usize index)
{
	obj_drop(heap->elem, heap_ptr(heap, index));
}

ResultBinaryHeap binary_heap_new(TypeDesc elem, heap_cmp_fn cmp)
{
	ResultRawBuf raw;
	BinaryHeap heap;

	if (elem.size == 0 || cmp == NULL) {
		return BinaryHeapErr(ERROR_INVALID_ARGUMENT);
	}
	raw = raw_buf_new(elem.size);
	if (RawBuf_is_err(&raw)) {
		return BinaryHeapErr(RawBuf_error(&raw));
	}
	heap.raw = RawBuf_unwrap(&raw);
	heap.len = 0;
	heap.elem = elem;
	heap.cmp = cmp;
	return BinaryHeapOk(heap);
}

usize binary_heap_len(const BinaryHeap *heap)
{
	return heap->len;
}

usize binary_heap_capacity(const BinaryHeap *heap)
{
	return heap->raw.cap;
}

bool binary_heap_is_empty(const BinaryHeap *heap)
{
	return heap->len == 0;
}

i32 binary_heap_reserve(BinaryHeap *heap, usize additional)
{
	usize required;

	if (additional > (usize)-1 - heap->len) {
		return -1;
	}
	required = heap->len + additional;
	return raw_buf_reserve(&heap->raw, required);
}

static i32 binary_heap_push_impl(BinaryHeap *heap, const void *value,
				 bool clear_source)
{
	void *slot;

	if (value == NULL) {
		return -1;
	}
	if (binary_heap_reserve(heap, 1) != 0) {
		return -1;
	}
	slot = heap_ptr(heap, heap->len);
	if (clear_source) {
		obj_move(heap->elem, slot, (void *)value);
	} else {
		memcpy(slot, value, heap->elem.size);
	}
	heap->len++;
	sift_up(heap, heap->len - 1);
	return 0;
}

i32 binary_heap_push(BinaryHeap *heap, void *value)
{
	return binary_heap_push_impl(heap, value, true);
}

i32 binary_heap_push_raw(BinaryHeap *heap, const void *value)
{
	return binary_heap_push_impl(heap, value, false);
}

i32 binary_heap_pop(BinaryHeap *heap, void *out)
{
	if (heap->len == 0 || out == NULL) {
		return -1;
	}
	obj_move(heap->elem, out, heap_ptr(heap, 0));
	heap->len--;
	if (heap->len > 0) {
		memcpy(heap_ptr(heap, 0), heap_ptr(heap, heap->len),
			heap->elem.size);
		sift_down(heap, 0);
	}
	return 0;
}

int binary_heap_remove(BinaryHeap *heap,
		       bool (*eq)(const void *elem1, const void *elem2),
		       const void *target)
{
	usize i;

	if (eq == NULL || target == NULL) {
		return -1;
	}
	for (i = 0; i < heap->len; ++i) {
		if (!eq(heap_ptr(heap, i), target)) {
			continue;
		}
		heap_drop_item(heap, i);
		heap->len--;
		if (i < heap->len) {
			memcpy(heap_ptr(heap, i), heap_ptr(heap, heap->len),
				heap->elem.size);
			if (i > 0 &&
			    heap->cmp(heap_ptr(heap, i),
				heap_ptr(heap, (i - 1) / 2)) > 0) {
				sift_up(heap, i);
			} else {
				sift_down(heap, i);
			}
		}
		return 0;
	}
	return -1;
}

const void *binary_heap_peek(const BinaryHeap *heap)
{
	if (heap->len == 0) {
		return NULL;
	}
	return heap_ptr(heap, 0);
}

void binary_heap_clear(BinaryHeap *heap)
{
	while (heap->len > 0) {
		heap->len--;
		heap_drop_item(heap, heap->len);
	}
}

void binary_heap_drop(void *self)
{
	BinaryHeap *heap = self;

	binary_heap_clear(heap);
	raw_buf_drop(&heap->raw);
	memset(heap, 0, sizeof(*heap));
}

void *binary_heap_clone_obj(const void *source_ptr)
{
	const BinaryHeap *source = source_ptr;
	BinaryHeap *copy;
	ResultBinaryHeap result;
	usize i;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	result = binary_heap_new(source->elem, source->cmp);
	if (BinaryHeap_is_err(&result)) {
		free(copy);
		return NULL;
	}
	*copy = BinaryHeap_unwrap(&result);
	if (binary_heap_reserve(copy, source->len) != 0) {
		binary_heap_drop(copy);
		free(copy);
		return NULL;
	}
	if (is_copy(source->elem)) {
		if (source->len != 0) {
			memcpy(copy->raw.data, source->raw.data,
				source->len * source->elem.size);
		}
		copy->len = source->len;
		return copy;
	}
	for (i = 0; i < source->len; ++i) {
		void *element = obj_clone(source->elem, heap_ptr(source, i));

		if (element == NULL) {
			binary_heap_drop(copy);
			free(copy);
			return NULL;
		}
		obj_move(source->elem, heap_ptr(copy, copy->len), element);
		copy->len++;
		free(element);
	}
	return copy;
}

ResultBinaryHeap binary_heap_clone(const BinaryHeap *source)
{
	BinaryHeap *copy = binary_heap_clone_obj(source);
	BinaryHeap value;

	if (copy == NULL) {
		return BinaryHeapErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return BinaryHeapOk(value);
}

