//generated by grok-4.5<noreply@x.ai> @ cursor
#ifndef SHYOS_BINARY_HEAP_H
#define SHYOS_BINARY_HEAP_H

#include "obj.h"
#include "rawbuf.h"
#include "result.h"

/*
 * cmp(a, b) > 0 表示 a 应排在 b 之上。
 * 传入“大于”比较得到最大堆；传入“小于”比较得到最小堆。
 */
typedef i32 (*heap_cmp_fn)(const void *a, const void *b);

typedef struct BinaryHeap BinaryHeap;
struct BinaryHeap {
	RawBuf raw;
	usize len;
	TypeDesc elem;
	heap_cmp_fn cmp;
};

void binary_heap_drop(void *self);
void *binary_heap_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(BinaryHeap, binary_heap_drop, binary_heap_clone_obj)

ResultBinaryHeap binary_heap_new(TypeDesc elem, heap_cmp_fn cmp);
ResultBinaryHeap binary_heap_clone(const BinaryHeap *source);

usize binary_heap_len(const BinaryHeap *heap);
usize binary_heap_capacity(const BinaryHeap *heap);
bool binary_heap_is_empty(const BinaryHeap *heap);

i32 binary_heap_reserve(BinaryHeap *heap, usize additional);
i32 binary_heap_push(BinaryHeap *heap, void *value);
i32 binary_heap_push_raw(BinaryHeap *heap, const void *value);
i32 binary_heap_pop(BinaryHeap *heap, void *out);
const void *binary_heap_peek(const BinaryHeap *heap);
void binary_heap_clear(BinaryHeap *heap);
//eq函数:相同返回1 不同返回0. 删除掉和target相同的第一个成员
int binary_heap_remove(BinaryHeap *heap,                                                                                                                               
    bool (*eq)(const void *elem1,const void *elem2),
	const void* target
);
#endif /* SHYOS_BINARY_HEAP_H */