//generated by grok-4.5<noreply@x.ai> @ cursor
#![no_std]

use core::cmp::Ordering;
use core::ffi::c_void;
use core::marker::PhantomData;
use core::mem::{align_of, size_of, ManuallyDrop, MaybeUninit};
use core::ptr;
use shyos_obj::TypeDesc;
use shyos_rawbuf::RawBuf;
pub use shyos_result::*;
type HeapCmpFn = unsafe extern "C" fn(*const c_void, *const c_void) -> i32;
type HeapEqFn = unsafe extern "C" fn(*const c_void, *const c_void) -> bool;

#[repr(C)]
#[doc(hidden)]
pub struct RawBinaryHeap {
    pub raw: RawBuf,
    pub len: usize,
    pub elem: TypeDesc,
    cmp: Option<HeapCmpFn>,
}

unsafe extern "C" {
    #[link_name = "binary_heap_new"]
    fn c_binary_heap_new(elem: TypeDesc, cmp: Option<HeapCmpFn>) -> CResult<RawBinaryHeap>;

    #[link_name = "binary_heap_reserve"]
    fn c_binary_heap_reserve(heap: *mut RawBinaryHeap, additional: usize) -> i32;

    #[link_name = "binary_heap_push_raw"]
    fn c_binary_heap_push_raw(heap: *mut RawBinaryHeap, value: *const c_void) -> i32;

    #[link_name = "binary_heap_pop"]
    fn c_binary_heap_pop(heap: *mut RawBinaryHeap, out: *mut c_void) -> i32;

    #[link_name = "binary_heap_peek"]
    fn c_binary_heap_peek(heap: *const RawBinaryHeap) -> *const c_void;

    #[link_name = "binary_heap_remove"]
    fn c_binary_heap_remove(
        heap: *mut RawBinaryHeap,
        eq: Option<HeapEqFn>,
        target: *const c_void,
    ) -> i32;

    #[link_name = "binary_heap_clear"]
    fn c_binary_heap_clear(heap: *mut RawBinaryHeap);

    #[link_name = "binary_heap_drop"]
    fn c_binary_heap_drop(heap: *mut RawBinaryHeap);
}

unsafe extern "C" fn drop_element<T>(value: *mut c_void) {
    unsafe { ptr::drop_in_place(value.cast::<T>()) }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HeapOrder {
    Max,
    Min,
}

unsafe extern "C" fn cmp_ord_max<T: Ord>(left: *const c_void, right: *const c_void) -> i32 {
    match unsafe { &*left.cast::<T>() }.cmp(unsafe { &*right.cast::<T>() }) {
        Ordering::Less => -1,
        Ordering::Equal => 0,
        Ordering::Greater => 1,
    }
}

unsafe extern "C" fn cmp_ord_min<T: Ord>(left: *const c_void, right: *const c_void) -> i32 {
    -cmp_ord_max::<T>(left, right)
}

unsafe extern "C" fn eq_partial<T: PartialEq>(elem: *const c_void, target: *const c_void) -> bool {
    let elem = unsafe { &*elem.cast::<T>() };
    let target = unsafe { &*target.cast::<T>() };
    elem == target
}

fn type_desc<T>() -> TypeDesc {
    TypeDesc {
        size: size_of::<T>(),
        drop: Some(drop_element::<T>),
        clone: None,
    }
}

fn cmp_for<T: Ord>(order: HeapOrder) -> HeapCmpFn {
    match order {
        HeapOrder::Max => cmp_ord_max::<T>,
        HeapOrder::Min => cmp_ord_min::<T>,
    }
}

pub struct CBinaryHeap<T> {
    raw: RawBinaryHeap,
    order: HeapOrder,
    marker: PhantomData<T>,
}

unsafe impl<T: Send> Send for CBinaryHeap<T> {}
unsafe impl<T: Sync> Sync for CBinaryHeap<T> {}

impl<T: Ord> CBinaryHeap<T> {
    pub fn new(order: HeapOrder) -> CResult<Self> {
        if size_of::<T>() == 0 || align_of::<T>() > align_of::<usize>() {
            return CResult::err(ERROR_INVALID_ARGUMENT);
        }
        match unsafe { c_binary_heap_new(type_desc::<T>(), Some(cmp_for::<T>(order))) } {
            CResult::Ok(raw) => CResult::ok(Self {
                raw,
                order,
                marker: PhantomData,
            }),
            CResult::Err(error) => CResult::err(error),
        }
    }

    pub fn with_capacity(capacity: usize, order: HeapOrder) -> CResult<Self> {
        let mut heap = match Self::new(order) {
            CResult::Ok(heap) => heap,
            CResult::Err(error) => return CResult::err(error),
        };
        if let CResult::Err(error) = heap.reserve(capacity) {
            return CResult::err(error);
        }
        CResult::ok(heap)
    }

    pub fn order(&self) -> HeapOrder {
        self.order
    }

    pub fn len(&self) -> usize {
        self.raw.len
    }

    pub fn capacity(&self) -> usize {
        self.raw.raw.cap
    }

    pub fn is_empty(&self) -> bool {
        self.raw.len == 0
    }
    pub fn reserve(&mut self, additional: usize) -> CResult<()> {
        if unsafe { c_binary_heap_reserve(&mut self.raw, additional) } == 0 {
            CResult::ok(())
        } else {
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn push(&mut self, value: T) -> CResult<()> {
        let value = ManuallyDrop::new(value);
        if unsafe { c_binary_heap_push_raw(&mut self.raw, (&*value as *const T).cast::<c_void>()) }
            == 0
        {
            CResult::ok(())
        } else {
            drop(ManuallyDrop::into_inner(value));
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn pop(&mut self) -> CResult<T> {
        let mut value = MaybeUninit::<T>::uninit();
        if unsafe { c_binary_heap_pop(&mut self.raw, value.as_mut_ptr().cast()) } == 0 {
            CResult::ok(unsafe { value.assume_init() })
        } else {
            CResult::err(ERROR_NO_VALUE)
        }
    }

    pub fn peek(&self) -> Option<&T> {
        unsafe { c_binary_heap_peek(&self.raw).cast::<T>().as_ref() }
    }

    pub fn clear(&mut self) {
        unsafe { c_binary_heap_clear(&mut self.raw) }
    }

    pub fn remove(&mut self, target: T) -> CResult<()> {
        let target = ManuallyDrop::new(target);
        if unsafe {
            c_binary_heap_remove(
                &mut self.raw,
                Some(eq_partial::<T>),
                (&*target as *const T).cast::<c_void>(),
            )
        } == 0
        {
            CResult::ok(())
        } else {
            drop(ManuallyDrop::into_inner(target));
            CResult::err(ERROR_NO_VALUE)
        }
    }
}

impl<T: Ord + Clone> Clone for CBinaryHeap<T> {
    fn clone(&self) -> Self {
        let mut clone = Self::with_capacity(self.len(), self.order).unwrap();
        for index in 0..self.len() {
            let value = unsafe { &*self.raw.raw.data.cast::<T>().add(index) };
            clone.push(value.clone()).unwrap();
        }
        clone
    }
}

impl<T> Drop for CBinaryHeap<T> {
    fn drop(&mut self) {
        unsafe { c_binary_heap_drop(&mut self.raw) }
    }
}
