//generated by gpt-5<noreply@openai.com> @ codex
//C-only 01log image 的 Rust 闭包与 panic handler。

#![no_std]

pub use shyos_log::*;

#[panic_handler]
fn panic(info: &::core::panic::PanicInfo) -> ! {
    shyos_log::panic::handle_panic(info)
}
