//generated by gpt-5<noreply@openai.com> @ codex
//Linux user backend raw input through board syscall wrappers.

#include <asm/ioctls.h>
#include <asm/termbits.h>
#include "board.h"

u8 shyos_linux_raw_getc(void)
{
	struct termios original;
	struct termios raw;
	u8 c = 0;
	long is_terminal;

	is_terminal = linux_ioctl(0, TCGETS, &original);
	if (is_terminal == 0) {
		raw = original;
		raw.c_lflag &= ~(ICANON | ECHO);
		raw.c_cc[VMIN] = 1;
		raw.c_cc[VTIME] = 0;
		(void)linux_ioctl(0, TCSETS, &raw);
	}

	(void)linux_syscall(__NR_read, 0, (long)&c, 1, 0, 0, 0);

	if (is_terminal == 0)
		(void)linux_ioctl(0, TCSETS, &original);

	return c;
}
