/* generated by gpt-5<noreply@openai.com> @ codex
 * C 世界 early console 字节 IO；Linux 使用 read/write，裸机使用 raw UART
 */
#ifndef SHYOS_UART_H
#define SHYOS_UART_H

void raw_putc(char c);
char raw_getc(void);

#endif
