/* generated by gpt-5.6-sol<noreply@openai.com> @ cursor
 * early_raw_* 始终轮询；raw_* / uart_interupt_init 由所选 UART provider 提供。
 * 轮询 provider 对 uart_interupt_init 提供空实现。
 */
#ifndef SHYOS_UART_H
#define SHYOS_UART_H

#include "shy_type.h"

void early_raw_putc(char c);
char early_raw_getc(void);

void raw_putc(char c);
char raw_getc(void);

i32 uart_interupt_init(void);

#endif
