//generated by gpt-5<noreply@openai.com> @ codex
//Rust wrapper for the C xorshift random implementation.

#![no_std]

unsafe extern "C" {
    #[link_name = "rand_seed"]
    fn c_rand_seed(seed: u64);

    #[link_name = "rand_u64"]
    fn c_rand_u64() -> u64;

    #[link_name = "randint"]
    fn c_randint(min: i32, max: i32) -> i32;
}

pub fn seed(seed: u64) {
    unsafe { c_rand_seed(seed) }
}

pub fn random() -> u64 {
    unsafe { c_rand_u64() }
}

pub fn randint(min: i32, max: i32) -> i32 {
    unsafe { c_randint(min, max) }
}
