/* generated by grok-4.5<noreply@x.ai> @ cursor
 * raw spinlock：关中断 + xchg 忙等。
 * 参数为 void *，调用方传入首字段为 struct spinlock 的对象即可。
 */
#include "spinlock.h"

#include "atomic.h"
#include "irq.h"

void spinlock_init(void *lock)
{
	struct spinlock *l = lock;
	l->locked = 0;
}

void spinlock_lock(void *lock)
{
	struct spinlock *l = lock;
	l->mask = disable_irq(IRQ_MASK_ALL);
	while (xchg(&l->locked, 1) != 0)
		;
}

void spinlock_unlock(void *lock)
{
	struct spinlock *l = lock;
	l->locked = 0;
	set_irq(l->mask);
}
