/* generated by grok-4.5<noreply@x.ai> @ cursor
 * raw spinlock + Result 风格 SpinlockT 布局宏。
 *
 * 约定：SpinlockT 的首字段必须是 struct spinlock，因此
 * spinlock_init/lock/unlock 可对任意 SpinlockT * 直接以 void * 调用。
 */
#ifndef SHYOS_SPINLOCK_H
#define SHYOS_SPINLOCK_H

#include "irq.h"
#include "shy_type.h"

struct spinlock {
	i32 locked;
	irq_mask_t mask;
};

/* 首字段为 struct spinlock 的对象均可传入（含 SpinlockT *）。 */
void spinlock_init(void *lock);
void spinlock_lock(void *lock);
void spinlock_unlock(void *lock);

#define SHY_SPINLOCK_TYPE_INNER(T) Spinlock##T
#define SHY_SPINLOCK_TYPE(T) SHY_SPINLOCK_TYPE_INNER(T)

#define DECLARE_SHY_SPINLOCK(T)                                              \
	typedef struct SHY_SPINLOCK_TYPE(T) SHY_SPINLOCK_TYPE(T);            \
	struct SHY_SPINLOCK_TYPE(T) {                                        \
		struct spinlock lock;                                        \
		T value;                                                     \
	};

#define IMPL_SHY_SPINLOCK(T)                                                 \
	DECLARE_SHY_SPINLOCK(T)                                              \
	static inline T *T##_spinlock_get(SHY_SPINLOCK_TYPE(T) *s)           \
	{                                                                    \
		return &s->value;                                            \
	}

IMPL_SHY_SPINLOCK(bool)
IMPL_SHY_SPINLOCK(char)
IMPL_SHY_SPINLOCK(i8)
IMPL_SHY_SPINLOCK(i16)
IMPL_SHY_SPINLOCK(i32)
IMPL_SHY_SPINLOCK(i64)
IMPL_SHY_SPINLOCK(u8)
IMPL_SHY_SPINLOCK(u16)
IMPL_SHY_SPINLOCK(u32)
IMPL_SHY_SPINLOCK(u64)
IMPL_SHY_SPINLOCK(isize)
IMPL_SHY_SPINLOCK(usize)
IMPL_SHY_SPINLOCK(f32)
IMPL_SHY_SPINLOCK(f64)
IMPL_SHY_SPINLOCK(int)
IMPL_SHY_SPINLOCK(unsigned)
IMPL_SHY_SPINLOCK(long)

#endif /* SHYOS_SPINLOCK_H */
