//generated by gpt-5<noreply@openai.com> @ codex
#include "ringbuffer.h"

#include "alloc.h"

ResultRingBuffer ring_buffer_new(usize capacity, TypeDesc elem)
{
	ResultDeque result;
	RingBuffer buffer;

	if (capacity == 0) {
		return RingBufferErr(ERROR_INVALID_ARGUMENT);
	}
	result = deque_new(elem);
	if (Deque_is_err(&result)) {
		return RingBufferErr(Deque_error(&result));
	}
	buffer.data = Deque_unwrap(&result);
	buffer.cap = capacity;
	if (deque_reserve(&buffer.data, capacity) != 0) {
		ring_buffer_drop(&buffer);
		return RingBufferErr(ERROR_OUT_OF_MEMORY);
	}
	return RingBufferOk(buffer);
}

usize ring_buffer_len(const RingBuffer *buffer)
{
	return deque_len(&buffer->data);
}

usize ring_buffer_capacity(const RingBuffer *buffer)
{
	return buffer->cap;
}

bool ring_buffer_is_empty(const RingBuffer *buffer)
{
	return deque_is_empty(&buffer->data);
}

bool ring_buffer_is_full(const RingBuffer *buffer)
{
	return ring_buffer_len(buffer) == buffer->cap;
}

i32 ring_buffer_push(RingBuffer *buffer, void *value)
{
	if (ring_buffer_is_full(buffer)) {
		if (deque_pop_front(&buffer->data, NULL) != 0) {
			return ERROR_EMPTY;
		}
	}
	if (deque_push_back(&buffer->data, value) != 0) {
		return ERROR_OUT_OF_MEMORY;
	}
	return 0;
}

i32 ring_buffer_push_raw(RingBuffer *buffer, const void *value)
{
	if (ring_buffer_is_full(buffer)) {
		if (deque_pop_front(&buffer->data, NULL) != 0) {
			return ERROR_EMPTY;
		}
	}
	if (deque_push_back_raw(&buffer->data, value) != 0) {
		return ERROR_OUT_OF_MEMORY;
	}
	return 0;
}

i32 ring_buffer_pop(RingBuffer *buffer, void *out)
{
	return deque_pop_front(&buffer->data, out);
}

const void *ring_buffer_front(const RingBuffer *buffer)
{
	return deque_front(&buffer->data);
}

void *ring_buffer_front_mut(RingBuffer *buffer)
{
	return deque_front_mut(&buffer->data);
}

const void *ring_buffer_back(const RingBuffer *buffer)
{
	return deque_back(&buffer->data);
}

void *ring_buffer_back_mut(RingBuffer *buffer)
{
	return deque_back_mut(&buffer->data);
}

void ring_buffer_clear(RingBuffer *buffer)
{
	deque_clear(&buffer->data);
}

void ring_buffer_drop(void *self)
{
	RingBuffer *buffer = self;

	deque_drop(&buffer->data);
	memset(buffer, 0, sizeof(*buffer));
}

void *ring_buffer_clone_obj(const void *source_ptr)
{
	const RingBuffer *source = source_ptr;
	RingBuffer *copy;
	ResultDeque data;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	data = deque_clone(&source->data);
	if (Deque_is_err(&data)) {
		free(copy);
		return NULL;
	}
	copy->data = Deque_unwrap(&data);
	copy->cap = source->cap;
	return copy;
}

ResultRingBuffer ring_buffer_clone(const RingBuffer *source)
{
	RingBuffer *copy = ring_buffer_clone_obj(source);
	RingBuffer value;

	if (copy == NULL) {
		return RingBufferErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return RingBufferOk(value);
}
