//generated by gpt-5<noreply@openai.com> @ codex
#ifndef SHYOS_RINGBUFFER_H
#define SHYOS_RINGBUFFER_H

#include "deque.h"

typedef struct RingBuffer RingBuffer;
struct RingBuffer {
	Deque data;
	usize cap;
};

/*
 * RingBuffer is an overwrite queue: when full, push drops the oldest
 * element before appending the new value.
 */
void ring_buffer_drop(void *self);
void *ring_buffer_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(RingBuffer, ring_buffer_drop, ring_buffer_clone_obj)

ResultRingBuffer ring_buffer_new(usize capacity, TypeDesc elem);
ResultRingBuffer ring_buffer_clone(const RingBuffer *source);

usize ring_buffer_len(const RingBuffer *buffer);
usize ring_buffer_capacity(const RingBuffer *buffer);
bool ring_buffer_is_empty(const RingBuffer *buffer);
bool ring_buffer_is_full(const RingBuffer *buffer);

/* Push never returns full; a full buffer overwrites its oldest element. */
i32 ring_buffer_push(RingBuffer *buffer, void *value);
i32 ring_buffer_push_raw(RingBuffer *buffer, const void *value);
i32 ring_buffer_pop(RingBuffer *buffer, void *out);

const void *ring_buffer_front(const RingBuffer *buffer);
void *ring_buffer_front_mut(RingBuffer *buffer);
const void *ring_buffer_back(const RingBuffer *buffer);
void *ring_buffer_back_mut(RingBuffer *buffer);

void ring_buffer_clear(RingBuffer *buffer);

#endif /* SHYOS_RINGBUFFER_H */
