# generated by gpt-5.6-sol<noreply@openai.com> @ codex
# Internal build configuration: load the final image's choices, validate them,
# and derive toolchain/C/Rust settings.

SHYOS_ROOT ?= $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)

# ---- image configuration ----
ifndef SHYOS_CONFIG
$(error SHYOS_CONFIG must point to an app/kernel/test shyos.mk)
endif
ifneq ($(filter /%,$(SHYOS_CONFIG)),)
SHYOS_CONFIG_FILE := $(SHYOS_CONFIG)
else
SHYOS_CONFIG_FILE := $(SHYOS_ROOT)/$(SHYOS_CONFIG)
endif
SHYOS_CONFIG_FILE := $(abspath $(SHYOS_CONFIG_FILE))

ifeq ($(wildcard $(SHYOS_CONFIG_FILE)),)
$(error ShyOS config not found: $(SHYOS_CONFIG_FILE))
endif
include $(SHYOS_CONFIG_FILE)
export SHYOS_CONFIG

ifeq ($(CONFIG),DEBUG)
C_BUILD_FLAGS := -O0 -g3
CARGO_PROFILE := debug
CARGO_PROFILE_ARGS :=
else ifeq ($(CONFIG),GDB)
C_BUILD_FLAGS := -Og -g3
CARGO_PROFILE := debug
CARGO_PROFILE_ARGS :=
else ifeq ($(CONFIG),RELEASE)
C_BUILD_FLAGS := -O2
CARGO_PROFILE := release
CARGO_PROFILE_ARGS := --release
else
$(error CONFIG must be DEBUG, GDB or RELEASE; got: $(CONFIG))
endif

SHYOS_DEFINES := $(strip $(SHYOS_DEFINES))
BACKEND_DEFINES := $(filter SHYOS_BACKEND_%,$(SHYOS_DEFINES))
BOARD_DEFINES := $(filter BOARD_%,$(SHYOS_DEFINES))
UART_DEFINES := $(filter SHYOS_UART_%,$(SHYOS_DEFINES))
PMM_DEFINES := $(filter SHYOS_PMM_%,$(SHYOS_DEFINES))

ifneq ($(words $(BACKEND_DEFINES)),1)
$(error config must keep exactly one SHYOS_BACKEND_* macro; got: $(BACKEND_DEFINES))
endif
ifneq ($(words $(UART_DEFINES)),1)
$(error config must keep exactly one SHYOS_UART_* macro; got: $(UART_DEFINES))
endif

# pmm 可选：未指定任何 SHYOS_PMM_* 时默认 NONE（alloc 接管全部可分配内存）。
ifeq ($(words $(PMM_DEFINES)),0)
SHYOS_DEFINES += SHYOS_PMM_NONE
PMM_DEFINES := SHYOS_PMM_NONE
else ifneq ($(words $(PMM_DEFINES)),1)
$(error config must keep at most one SHYOS_PMM_* macro; got: $(PMM_DEFINES))
endif

# ---- common tools ----
CARGO := cargo
unexport RUSTC

# ---- backend/toolchain ----
ifneq ($(filter SHYOS_BACKEND_QEMU_VIRT,$(BACKEND_DEFINES)),)
BACKEND := qemu_virt
BOARD := qemu_virt
ifneq ($(BOARD_DEFINES),BOARD_QEMU_VIRT)
$(error SHYOS_BACKEND_QEMU_VIRT requires exactly BOARD_QEMU_VIRT; got: $(BOARD_DEFINES))
endif

BAREMETAL_CROSS ?= riscv64-unknown-elf-
ARCH_BAREMETAL_CROSS ?= riscv64-elf-
LINUX_CROSS ?= riscv64-linux-gnu-
ifeq ($(origin CROSS),undefined)
ifneq ($(shell command -v $(BAREMETAL_CROSS)gcc 2>/dev/null),)
CROSS := $(BAREMETAL_CROSS)
else ifneq ($(shell command -v $(ARCH_BAREMETAL_CROSS)gcc 2>/dev/null),)
CROSS := $(ARCH_BAREMETAL_CROSS)
else ifneq ($(shell command -v $(LINUX_CROSS)gcc 2>/dev/null),)
CROSS := $(LINUX_CROSS)
else
$(error no RISC-V compiler found; install $(BAREMETAL_CROSS)gcc, $(ARCH_BAREMETAL_CROSS)gcc, or set CROSS=<tool-prefix>)
endif
endif

CC := $(CROSS)gcc
AS := $(CROSS)gcc
LD := $(CROSS)ld
AR := $(CROSS)ar
OBJCOPY := $(CROSS)objcopy
OBJDUMP := $(CROSS)objdump

RUST_TARGET ?= riscv64gc-unknown-none-elf
CFLAGS_COMMON := \
	-ffreestanding -fno-builtin -fno-stack-protector \
	-ffunction-sections -fdata-sections \
		-nostdlib -nostartfiles \
		-march=rv64gc -mabi=lp64d \
		-mcmodel=medany \
		-Wall -Wextra
LDFLAGS_DEFAULT := -nostdlib -static -Wl,--gc-sections \
	-Wl,--build-id=none -T $(SHYOS_ROOT)/lib/00arch/linker.ld
RUST_CODEGEN_FLAGS := \
	-C relocation-model=static \
	-C code-model=medium \
	-C target-feature=+m,+a,+c
else ifneq ($(filter SHYOS_BACKEND_LINUX_USER,$(BACKEND_DEFINES)),)
BACKEND := linux_user
BOARD := none
ifneq ($(BOARD_DEFINES),)
$(error SHYOS_BACKEND_LINUX_USER does not use a BOARD_* macro; got: $(BOARD_DEFINES))
endif
# linux_user 没有物理页概念：pmm 只能是 NONE，alloc 用 brk/sbrk 接管全部
ifneq ($(PMM_DEFINES),SHYOS_PMM_NONE)
$(error SHYOS_BACKEND_LINUX_USER requires SHYOS_PMM_NONE; got: $(PMM_DEFINES))
endif

ifeq ($(origin CROSS),undefined)
CROSS :=
endif
CC := $(CROSS)gcc
AS := $(CROSS)gcc
LD := $(CROSS)ld
AR := $(CROSS)ar
OBJCOPY := $(CROSS)objcopy
OBJDUMP := $(CROSS)objdump

RUST_HOST := $(shell rustc -vV | sed -n 's/^host: //p')
RUST_TARGET ?= $(RUST_HOST)
	CFLAGS_COMMON := \
		-ffunction-sections -fdata-sections \
		-fno-builtin -fno-stack-protector \
		-Wall -Wextra
LDFLAGS_DEFAULT := -Wl,--gc-sections -Wl,--build-id=none
RUST_CODEGEN_FLAGS := -C relocation-model=pic
else
$(error unsupported backend macro: $(BACKEND_DEFINES))
endif

# ---- include paths ----
MODULE_INCLUDE_DIRS := $(shell python3 $(SHYOS_ROOT)/tools/layer_graph.py \
	--root $(SHYOS_ROOT) include-dirs)
INCLUDES := \
	-I$(SHYOS_ROOT)/include \
	$(addprefix -I,$(MODULE_INCLUDE_DIRS))

CONFIG_CFLAGS := $(addprefix -D,$(SHYOS_DEFINES))
CFLAGS ?= $(CFLAGS_COMMON) $(C_BUILD_FLAGS) $(CONFIG_CFLAGS) $(INCLUDES)
ASFLAGS ?= $(CFLAGS_COMMON) $(C_BUILD_FLAGS) $(CONFIG_CFLAGS)
LDFLAGS ?= $(LDFLAGS_DEFAULT)

# ---- Rust/cargo ----
CARGO_TARGET_DIR ?= $(SHYOS_ROOT)/target/cargo
export CARGO_TARGET_DIR

SHYOS_RUST_INPUTS := \
	$(wildcard \
		$(SHYOS_ROOT)/Cargo.toml \
		$(SHYOS_ROOT)/Cargo.lock \
		$(SHYOS_ROOT)/rust-toolchain.toml \
		$(SHYOS_ROOT)/.cargo/config.toml) \
	$(shell find $(SHYOS_ROOT)/lib \
		-path '*/target' -prune -o \
		-type f \( -name 'Cargo.toml' -o -name '*.rs' \) -print)

RUSTFLAGS_EXTRA ?=
CONFIG_RUSTFLAGS := \
	$(foreach cfg,$(SHYOS_DEFINES),--cfg $(cfg)) \
	--check-cfg=cfg(any())
RUSTFLAGS := $(strip \
	$(RUSTFLAGS_EXTRA) \
	$(CONFIG_RUSTFLAGS) \
	$(RUST_CODEGEN_FLAGS))
export RUSTFLAGS

# Final Rust image crates rebuild the freestanding Rust runtime closure for
# their selected target instead of relying on the target's prebuilt sysroot.
CARGO_BUILD_STD_FLAGS ?= -Z build-std=core,alloc,compiler_builtins

# Per-configuration native output variant. Objects built with different
# effective flags live in separate target/<config-id>/ directories, so
# switching images or backends no longer rebuilds the other configuration.
SHYOS_CONFIG_ID := $(shell printf '%s\n' \
	'$(CONFIG)' '$(SHYOS_DEFINES)' '$(BACKEND)' '$(BOARD)' '$(CC)' \
	'$(CFLAGS)' '$(ASFLAGS)' '$(LDFLAGS)' '$(RUST_TARGET)' '$(RUSTFLAGS)' \
	'$(CARGO_PROFILE)' '$(CARGO_BUILD_STD_FLAGS)' | md5sum | cut -c1-12)
SHYOS_TARGET_DIR := target/$(SHYOS_CONFIG_ID)

# Record the effective configuration once per variant; the marker keeps its
# mtime afterwards so dependents never rebuild for a stable configuration.
SHYOS_CONFIG_STATE := $(SHYOS_ROOT)/target/.shyos-config-$(SHYOS_CONFIG_ID)

.PHONY: shyos-config-force
shyos-config-force:

$(SHYOS_CONFIG_STATE): shyos-config-force
	@mkdir -p $(dir $@)
	@tmp="$@.$$$$.tmp"; \
	trap 'rm -f "$$tmp"' EXIT HUP INT TERM; \
	{ \
		printf '%s\n' 'CONFIG=$(CONFIG)'; \
		printf '%s\n' 'SHYOS_DEFINES=$(SHYOS_DEFINES)'; \
		printf '%s\n' 'BACKEND=$(BACKEND)'; \
		printf '%s\n' 'BOARD=$(BOARD)'; \
		printf '%s\n' 'CC=$(CC)'; \
		printf '%s\n' 'CFLAGS=$(CFLAGS)'; \
		printf '%s\n' 'ASFLAGS=$(ASFLAGS)'; \
		printf '%s\n' 'LDFLAGS=$(LDFLAGS)'; \
		printf '%s\n' 'RUST_TARGET=$(RUST_TARGET)'; \
		printf '%s\n' 'RUSTFLAGS=$(RUSTFLAGS)'; \
		printf '%s\n' 'CARGO_TARGET_DIR=$(CARGO_TARGET_DIR)'; \
		printf '%s\n' 'CARGO_PROFILE=$(CARGO_PROFILE)'; \
		printf '%s\n' 'CARGO_BUILD_STD_FLAGS=$(CARGO_BUILD_STD_FLAGS)'; \
	} > "$$tmp"; \
	if test -r "$@" && cmp -s "$$tmp" "$@"; then \
		rm -f "$$tmp"; \
	else \
		mv -f "$$tmp" "$@"; \
	fi; \
	trap - EXIT HUP INT TERM
