# generated by gpt-5.6-sol<noreply@openai.com> @ codex
# 编号层公共构建：先校验模块 DAG，再按拓扑序构建依赖层和本层模块。

ifndef LAYER
$(error layer Makefile must define LAYER before including mk/layer.mk)
endif
ifndef LAYER_ARCHIVE
$(error layer Makefile must define LAYER_ARCHIVE before including mk/layer.mk)
endif
ifndef LAYER_RUST_LIB
$(error layer Makefile must define LAYER_RUST_LIB before including mk/layer.mk)
endif

LAYER_TOOL := $(SHYOS_ROOT)/tools/layer_graph.py
LAYER_FILE ?= $(OUT_DIR)/$(LAYER).layer.ld
LAYER_NORUST_FILE ?= $(OUT_DIR)/$(LAYER).norust.layer.ld
LAYER_RUST_ARCHIVE ?= $(OUT_DIR)/libshyos_$(LAYER)_rust.a
LAYER_CARGO_STATICLIB := \
	$(CARGO_TARGET_DIR)/$(RUST_TARGET)/$(CARGO_PROFILE)/lib$(LAYER_RUST_LIB).a
LAYER_DEPS := $(shell python3 $(LAYER_TOOL) --root $(SHYOS_ROOT) deps --layer $(LAYER))
LAYER_MODULES := $(shell python3 $(LAYER_TOOL) --root $(SHYOS_ROOT) module-order \
	--layer $(LAYER) --defines "$(SHYOS_DEFINES)")
LAYER_DEP_TARGETS := $(addprefix layer-dep-,$(LAYER_DEPS))

.PHONY: build build-norust _layer-build _layer-build-norust check-layer \
	layer-dependencies layer-modules layer-rust-staticlib $(LAYER_DEP_TARGETS)

build: check-layer
	$(MAKE) layer-dependencies
	$(MAKE) layer-modules
	$(MAKE) _layer-build

build-norust: check-layer
	$(MAKE) layer-dependencies
	$(MAKE) layer-modules
	$(MAKE) _layer-build-norust

check-layer:
	python3 $(LAYER_TOOL) --root $(SHYOS_ROOT) check

layer-dependencies: $(LAYER_DEP_TARGETS)

$(LAYER_DEP_TARGETS):
	$(MAKE) -C $(SHYOS_ROOT)/lib/$(patsubst layer-dep-%,%,$@) build-norust

layer-modules:
	@for module in $(LAYER_MODULES); do \
		$(MAKE) -C $(SHYOS_ROOT)/lib/$$module build || exit $$?; \
	done

_layer-build: $(LAYER_FILE)

_layer-build-norust: $(LAYER_NORUST_FILE)

layer-rust-staticlib: $(SHYOS_CONFIG_STATE)
	$(CARGO) build \
		--manifest-path $(CURDIR)/rust_image/Cargo.toml \
		--target $(RUST_TARGET) \
		$(CARGO_BUILD_STD_FLAGS) \
		$(CARGO_PROFILE_ARGS)
	@mkdir -p $(dir $(LAYER_RUST_ARCHIVE))
	@if ! test -r $(LAYER_RUST_ARCHIVE) || \
	    ! cmp -s $(LAYER_CARGO_STATICLIB) $(LAYER_RUST_ARCHIVE); then \
		cp -f $(LAYER_CARGO_STATICLIB) $(LAYER_RUST_ARCHIVE); \
	fi

$(LAYER_FILE): $(LAYER_ARCHIVE) layer-rust-staticlib $(LAYER_TOOL) \
		$(SHYOS_ROOT)/lib/$(LAYER)/layer.toml
	python3 $(LAYER_TOOL) --root $(SHYOS_ROOT) emit \
		--layer $(LAYER) \
		--output $@ \
		--config-id $(SHYOS_CONFIG_ID)

$(LAYER_NORUST_FILE): $(LAYER_ARCHIVE) $(LAYER_TOOL) \
		$(SHYOS_ROOT)/lib/$(LAYER)/layer.toml
	python3 $(LAYER_TOOL) --root $(SHYOS_ROOT) emit \
		--layer $(LAYER) \
		--norust \
		--output $@ \
		--config-id $(SHYOS_CONFIG_ID)
