/* generated by gpt-5<noreply@openai.com> @ codex
 * C 世界关机接口；实现在 shutdown.c。
 */
#ifndef SHYOS_SHUTDOWN_H
#define SHYOS_SHUTDOWN_H

#include "shy_type.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * 关机；不返回。
 * code == 0：QEMU virt 正常退出（exit 0）
 * code != 0：QEMU virt 失败退出（exit code 透传，低 16 位有效）
 * Linux user backend：调用 _exit(code)。
 */
void shutdown(i32 code) __attribute__((noreturn));

#ifdef __cplusplus
}
#endif

#endif /* SHYOS_SHUTDOWN_H */
