/* generated by gpt-5<noreply@openai.com> @ codex
 * shutdown(code)：QEMU virt 上写 SiFive test finisher
 *   0     → 0x5555
 *   非 0  → 0x3333 | ((code & 0xffff) << 16)
 */

#include "shutdown.h"
#include "board.h"

#ifdef SHYOS_BACKEND_LINUX_USER
#include <unistd.h>
#endif

void shutdown(i32 code)
{
#ifdef SHYOS_BACKEND_LINUX_USER
    _exit(code);
#else
#if defined(BOARD_QEMU_VIRT)
    volatile u32 *finisher =
        (volatile u32 *)(unsigned long)SIFIVE_TEST_BASE;
    if (code == 0)
        *finisher = SIFIVE_TEST_PASS;
    else
        *finisher = SIFIVE_TEST_FAIL | (((u32)code & 0xffffu) << 16);
#endif
    (void)code;
    for (;;) {
        __asm__ volatile("wfi");
    }
#endif
}
