//generated by grok-4.5<noreply@x.ai> @ pi
//参考 board.h 实现条件编译
//Rust 世界：path 依赖本 crate
//C 世界：Makefile 将本 crate emit 为 board.o（当前多为常量，目标文件几乎为空）

#![no_std]

#[cfg(BOARD_QEMU_VIRT)]
mod qemu_virt;

#[cfg(BOARD_QEMU_VIRT)]
pub use qemu_virt::*;

#[cfg(any(
    SHYOS_BACKEND_LINUX_USER,
    all(target_os = "linux", not(BOARD_QEMU_VIRT))
))]
mod linux_user;

#[cfg(any(
    SHYOS_BACKEND_LINUX_USER,
    all(target_os = "linux", not(BOARD_QEMU_VIRT))
))]
pub use linux_user::*;
