//generated by grok-4.5<noreply@x.ai> @ pi
//Linux user backend：
//  HEAP_START = null  => simple_alloc 自行向宿主申请 arena
//  HEAP_SIZE          => 申请大小

use core::ffi::{c_char, c_int, c_void};

/// Simple-alloc arena size requested from the host: 196 MiB.
pub const HEAP_SIZE: usize = 0x0C40_0000;

/// Null base means “allocator owns arena acquisition”.
pub const HEAP_START: *mut u8 = core::ptr::null_mut();

const AT_FDCWD: c_int = -100;
const O_RDONLY: c_int = 0;
const URANDOM: &[u8] = b"/dev/urandom\0";

unsafe extern "C" {
    fn openat(dirfd: c_int, path: *const c_char, flags: c_int, mode: u32) -> c_int;
    fn read(fd: c_int, buffer: *mut c_void, count: usize) -> isize;
    fn close(fd: c_int) -> c_int;
}

#[unsafe(no_mangle)]
pub extern "C" fn randseed() -> u64 {
    let mut seed = 0u64;
    let fd = unsafe { openat(AT_FDCWD, URANDOM.as_ptr().cast(), O_RDONLY, 0) };
    if fd >= 0 {
        unsafe {
            let _ = read(
                fd,
                (&mut seed as *mut u64).cast::<c_void>(),
                core::mem::size_of::<u64>(),
            );
            let _ = close(fd);
        }
    }
    seed
}
