//generated by grok-4.5<noreply@x.ai> @ pi
//qemu riscv virt平台的UART / 关机相关定义

/// QEMU virt default RAM base (matches `-machine virt`).
pub const RAM_BASE: usize = 0x8000_0000;
/// QEMU virt default RAM size: 256 MiB.
pub const RAM_SIZE: usize = 0x1000_0000;
/// Simple-alloc arena start: RAM_BASE + 64 MiB.
pub const HEAP_START: usize = RAM_BASE + 0x0400_0000;
/// Simple-alloc arena size: RAM_SIZE - 64 MiB = 192 MiB.
pub const HEAP_SIZE: usize = RAM_SIZE - 0x0400_0000;

/// QEMU virt: NS16550A MMIO UART0
pub const UART0_BASE: usize = 0x1000_0000;

/// Transmit Holding Register (write)
pub const UART_THR: usize = 0;
/// Receive Buffer Register (read)
pub const UART_RBR: usize = 0;
/// Interrupt Enable Register
pub const UART_IER: usize = 1;
/// Interrupt Identification Register (read)
pub const UART_IIR: usize = 2;
/// FIFO Control Register (write)
pub const UART_FCR: usize = 2;
/// Line Control Register
pub const UART_LCR: usize = 3;
/// Modem Control Register
pub const UART_MCR: usize = 4;
/// Line Status Register
pub const UART_LSR: usize = 5;
/// Modem Status Register
pub const UART_MSR: usize = 6;
/// Scratch Register
pub const UART_SCR: usize = 7;

/// Data Ready
pub const UART_LSR_DR: u8 = 1 << 0;
/// Overrun Error
pub const UART_LSR_OE: u8 = 1 << 1;
/// Parity Error
pub const UART_LSR_PE: u8 = 1 << 2;
/// Framing Error
pub const UART_LSR_FE: u8 = 1 << 3;
/// Break Interrupt
pub const UART_LSR_BI: u8 = 1 << 4;
/// Transmitter Holding Register Empty
pub const UART_LSR_THRE: u8 = 1 << 5;
/// Transmitter Empty
pub const UART_LSR_TEMT: u8 = 1 << 6;
/// Error in RCVR FIFO
pub const UART_LSR_FIFOERR: u8 = 1 << 7;

/// QEMU virt: SiFive test finisher MMIO base
pub const SIFIVE_TEST_BASE: usize = 0x1000_00;
/// 正常关机码（低 16 位 0x5555）
pub const SIFIVE_TEST_PASS: u32 = 0x5555;
/// 失败关机码前缀（实际为 0x3333 | (code << 16)）
pub const SIFIVE_TEST_FAIL: u32 = 0x3333;

/// QEMU virt platform-level interrupt controller.
pub const PLIC_BASE: usize = 0x0c00_0000;
pub const PLIC_NUM_SOURCES: u32 = 95;
pub const PLIC_PRIORITY_OFFSET: usize = 0x000000;
/// hart 0 S-mode context enable bitmap.
pub const PLIC_SCONTEXT_ENABLE_OFFSET: usize = 0x002080;
/// hart 0 S-mode context threshold/claim block.
pub const PLIC_SCONTEXT_OFFSET: usize = 0x201000;
pub const PLIC_THRESHOLD_OFFSET: usize = 0;
pub const PLIC_CLAIM_OFFSET: usize = 4;

pub const UART0_IRQ: u32 = 10;

#[unsafe(no_mangle)]
pub extern "C" fn randseed() -> u64 {
    let value: u64;
    unsafe {
        core::arch::asm!("rdcycle {}", out(reg) value);
    }
    value
}
