/* generated by grok-4.5<noreply@x.ai> @ pi
 * Linux user backend 板级/宿主侧常量
 *
 * 无物理 RAM 布局。
 * HEAP_START = NULL：告知 simple_alloc 通过板级 linux_sbrk 申请 arena。
 * HEAP_SIZE        ：申请大小。
 */

#ifndef SHYOS_BOARD_LINUX_USER_LINUX_USER_H
#define SHYOS_BOARD_LINUX_USER_LINUX_USER_H

#include "shy_type.h"
#include "syscall.h"

/* 默认 196 MiB arena */
#define HEAP_SIZE  0x0C400000UL
#define HEAP_START ((void *)0)

#endif /* SHYOS_BOARD_LINUX_USER_LINUX_USER_H */
