//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//Linux user backend 的原始系统调用与 brk/sbrk 包装

#ifndef SHYOS_BOARD_LINUX_USER_SYSCALL_H
#define SHYOS_BOARD_LINUX_USER_SYSCALL_H

#include <asm/unistd.h>
#include "shy_type.h"

static inline long linux_syscall(long number,
				 long arg0, long arg1, long arg2,
				 long arg3, long arg4, long arg5)
{
#if defined(__x86_64__)
	long result;
	register long r10 __asm__("r10") = arg3;
	register long r8 __asm__("r8") = arg4;
	register long r9 __asm__("r9") = arg5;

	__asm__ volatile(
		"syscall"
		: "=a"(result)
		: "a"(number), "D"(arg0), "S"(arg1), "d"(arg2),
		  "r"(r10), "r"(r8), "r"(r9)
		: "rcx", "r11", "memory");
	return result;
#elif defined(__aarch64__)
	register long x0 __asm__("x0") = arg0;
	register long x1 __asm__("x1") = arg1;
	register long x2 __asm__("x2") = arg2;
	register long x3 __asm__("x3") = arg3;
	register long x4 __asm__("x4") = arg4;
	register long x5 __asm__("x5") = arg5;
	register long x8 __asm__("x8") = number;

	__asm__ volatile(
		"svc 0"
		: "+r"(x0)
		: "r"(x1), "r"(x2), "r"(x3), "r"(x4), "r"(x5), "r"(x8)
		: "cc", "memory");
	return x0;
#elif defined(__riscv) && __riscv_xlen == 64
	register long a0 __asm__("a0") = arg0;
	register long a1 __asm__("a1") = arg1;
	register long a2 __asm__("a2") = arg2;
	register long a3 __asm__("a3") = arg3;
	register long a4 __asm__("a4") = arg4;
	register long a5 __asm__("a5") = arg5;
	register long a7 __asm__("a7") = number;

	__asm__ volatile(
		"ecall"
		: "+r"(a0)
		: "r"(a1), "r"(a2), "r"(a3), "r"(a4), "r"(a5), "r"(a7)
		: "memory");
	return a0;
#elif defined(__loongarch64)
	register long a0 __asm__("a0") = arg0;
	register long a1 __asm__("a1") = arg1;
	register long a2 __asm__("a2") = arg2;
	register long a3 __asm__("a3") = arg3;
	register long a4 __asm__("a4") = arg4;
	register long a5 __asm__("a5") = arg5;
	register long a7 __asm__("a7") = number;

	__asm__ volatile(
		"syscall 0"
		: "+r"(a0)
		: "r"(a1), "r"(a2), "r"(a3), "r"(a4), "r"(a5), "r"(a7)
		: "$t0", "$t1", "$t2", "$t3", "$t4",
		  "$t5", "$t6", "$t7", "$t8", "memory");
	return a0;
#else
#error "linux_user syscall is unsupported on this architecture"
#endif
}

static inline void *linux_sbrk(isize increment)
{
	long current;

	current = linux_syscall(__NR_brk, 0, 0, 0, 0, 0, 0);
	(void)linux_syscall(
		__NR_brk, current + (long)increment, 0, 0, 0, 0, 0);
	return (void *)current;
}

static inline long linux_ioctl(i32 fd, usize request, void *arg)
{
	return linux_syscall(
		__NR_ioctl, (long)fd, (long)request, (long)arg, 0, 0, 0);
}

#endif /* SHYOS_BOARD_LINUX_USER_SYSCALL_H */
