//generated by gpt-5<noreply@openai.com> @ codex
//C-only 04data_structure image 的 Rust 闭包与 panic handler。

#![no_std]

pub use shyos_data_structure::*;

#[panic_handler]
fn panic(info: &::core::panic::PanicInfo) -> ! {
    shyos_data_structure::panic::handle_panic(info)
}
