/* generated by gpt-5.6-sol<noreply@openai.com> @ codex
 * 架构无关 IRQ C ABI；具体行为由编译期 BACKEND 提供。
 */
#ifndef SHYOS_IRQ_H
#define SHYOS_IRQ_H

#include "shy_type.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef u32 irq_mask_t;
typedef u32 irq_id_t;

/* CPU 可接收的中断大类；不是具体设备 IRQ 编号。 */
#define IRQ_MASK_SOFTWARE (UINT32_C(1) << 0)
#define IRQ_MASK_TIMER    (UINT32_C(1) << 1)
#define IRQ_MASK_EXTERNAL (UINT32_C(1) << 2)
#define IRQ_MASK_ALL      \
    (IRQ_MASK_SOFTWARE | IRQ_MASK_TIMER | IRQ_MASK_EXTERNAL)

/*
 * irq_id_t 位编码：
 *   [31:28] kind
 *   [27:0]  kind 内部的 source number
 */
#define IRQ_ID_KIND_SHIFT  28U
#define IRQ_ID_KIND_MASK   UINT32_C(0xf0000000)
#define IRQ_ID_SOURCE_MASK UINT32_C(0x0fffffff)

#define IRQ_KIND_SOFTWARE UINT32_C(1)
#define IRQ_KIND_TIMER    UINT32_C(2)
#define IRQ_KIND_EXTERNAL UINT32_C(3)

#define IRQ_ID_MAKE(kind, source) \
    ((((irq_id_t)(kind) << IRQ_ID_KIND_SHIFT) & IRQ_ID_KIND_MASK) | \
     ((irq_id_t)(source) & IRQ_ID_SOURCE_MASK))
#define IRQ_ID_KIND(id) \
    (((irq_id_t)(id) & IRQ_ID_KIND_MASK) >> IRQ_ID_KIND_SHIFT)
#define IRQ_ID_SOURCE(id) ((irq_id_t)(id) & IRQ_ID_SOURCE_MASK)

#define IRQ_ID_SOFTWARE IRQ_ID_MAKE(IRQ_KIND_SOFTWARE, 0)
#define IRQ_ID_TIMER    IRQ_ID_MAKE(IRQ_KIND_TIMER, 0)
#define IRQ_ID_EXTERNAL(source) IRQ_ID_MAKE(IRQ_KIND_EXTERNAL, (source))

enum irq_status {
    IRQ_STATUS_OK = 0,
    IRQ_STATUS_NONE = 0,
    IRQ_STATUS_CLAIMED = 1,
    IRQ_ERROR_INVALID = -1,
    IRQ_ERROR_UNSUPPORTED = -2,
};

/*
 * 设置硬件 trap 入口地址。entry 必须满足后端要求的对齐。
 * Linux 用户态没有权限设置 CPU trap 入口，因此返回 IRQ_ERROR_UNSUPPORTED。
 */
i32 set_trap_entry(usize entry);

/*
 * 修改 CPU 中断大类 mask，返回修改前的抽象 mask。
 * set_irq 会用给定 mask 覆盖所有受支持的大类。
 */
irq_mask_t set_irq(irq_mask_t mask);
irq_mask_t enable_irq(irq_mask_t mask);
irq_mask_t disable_irq(irq_mask_t mask);
irq_mask_t get_irq(void);

/*
 * CPU 中断总开关。enabled 为 0 表示关闭，非 0 表示开启。
 * 返回修改前的状态：0 为关闭，1 为开启。
 */
bool global_irq(bool enabled);

/* 控制一个具体外部中断 source。 */
i32 enable_irq_source(irq_id_t irq);
i32 disable_irq_source(irq_id_t irq);

/*
 * claim 会领取一个 pending 外部中断：
 *   1  成功，*irq 收到完整 irq_id_t
 *   0  当前没有 pending 外部中断
 *  <0  参数或后端错误
 */
i32 claim_external_irq(irq_id_t *irq);

/* 完成之前 claim 得到的同一个外部中断。 */
i32 complete_external_irq(irq_id_t irq);

#ifdef __cplusplus
}
#endif

#endif /* SHYOS_IRQ_H */
