/* generated by gpt-5.6-sol<noreply@openai.com> @ codex
 * Linux user backend does not emulate hardware IRQ control. Higher layers may
 * provide ptrace or another process-control runtime without coupling 00arch
 * to that policy.
 */

#include "irq.h"

#if !defined(SHYOS_BACKEND_LINUX_USER)
#error "irq_linux_user.c requires SHYOS_BACKEND_LINUX_USER"
#endif

i32 set_trap_entry(usize entry)
{
    (void)entry;
    return IRQ_ERROR_UNSUPPORTED;
}

irq_mask_t set_irq(irq_mask_t mask)
{
    (void)mask;
    return 0;
}

irq_mask_t enable_irq(irq_mask_t mask)
{
    (void)mask;
    return 0;
}

irq_mask_t disable_irq(irq_mask_t mask)
{
    (void)mask;
    return 0;
}

irq_mask_t get_irq(void)
{
    return 0;
}

bool global_irq(bool enabled)
{
    (void)enabled;
    return false;
}

i32 enable_irq_source(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}

i32 disable_irq_source(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}

i32 claim_external_irq(irq_id_t *irq)
{
    if (irq == 0)
        return IRQ_ERROR_INVALID;

    *irq = 0;
    return IRQ_STATUS_NONE;
}

i32 complete_external_irq(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}
