/* generated by gpt-5.6-sol<noreply@openai.com> @ codex
 * QEMU virt / RISC-V S-mode IRQ backend。
 */

#include "irq.h"
#include "board.h"

#if !defined(SHYOS_BACKEND_QEMU_VIRT)
#error "irq_qemu_virt.c requires SHYOS_BACKEND_QEMU_VIRT"
#endif

#if !defined(__riscv)
#error "irq_qemu_virt.c requires a RISC-V target"
#endif

#define SIE_SSIE (1UL << 1)
#define SIE_STIE (1UL << 5)
#define SIE_SEIE (1UL << 9)
#define SSTATUS_SIE (1UL << 1)

static volatile u32 *plic_priority(u32 source)
{
    return (volatile u32 *)(usize)
        (PLIC_BASE + PLIC_PRIORITY_OFFSET + source * sizeof(u32));
}

static volatile u32 *plic_enable_word(u32 source)
{
    return (volatile u32 *)(usize)
        (PLIC_BASE + PLIC_SCONTEXT_ENABLE_OFFSET +
         (source / 32U) * sizeof(u32));
}

static volatile u32 *plic_threshold(void)
{
    return (volatile u32 *)(usize)
        (PLIC_BASE + PLIC_SCONTEXT_OFFSET + PLIC_THRESHOLD_OFFSET);
}

static volatile u32 *plic_claim_complete(void)
{
    return (volatile u32 *)(usize)
        (PLIC_BASE + PLIC_SCONTEXT_OFFSET + PLIC_CLAIM_OFFSET);
}

static unsigned long irq_mask_to_sie(irq_mask_t mask)
{
    unsigned long value = 0;

    if ((mask & IRQ_MASK_SOFTWARE) != 0U)
        value |= SIE_SSIE;
    if ((mask & IRQ_MASK_TIMER) != 0U)
        value |= SIE_STIE;
    if ((mask & IRQ_MASK_EXTERNAL) != 0U)
        value |= SIE_SEIE;

    return value;
}

static irq_mask_t sie_to_irq_mask(unsigned long value)
{
    irq_mask_t mask = 0;

    if ((value & SIE_SSIE) != 0UL)
        mask |= IRQ_MASK_SOFTWARE;
    if ((value & SIE_STIE) != 0UL)
        mask |= IRQ_MASK_TIMER;
    if ((value & SIE_SEIE) != 0UL)
        mask |= IRQ_MASK_EXTERNAL;

    return mask;
}

static i32 external_source(irq_id_t irq, u32 *source)
{
    u32 value;

    if (IRQ_ID_KIND(irq) != IRQ_KIND_EXTERNAL || source == 0)
        return IRQ_ERROR_INVALID;

    value = IRQ_ID_SOURCE(irq);
    if (value == 0U || value > PLIC_NUM_SOURCES)
        return IRQ_ERROR_INVALID;

    *source = value;
    return IRQ_STATUS_OK;
}

i32 set_trap_entry(usize entry)
{
    if ((entry & (usize)0x3U) != 0U)
        return IRQ_ERROR_INVALID;

    __asm__ volatile("csrw stvec, %0" : : "r"(entry) : "memory");
    return IRQ_STATUS_OK;
}

irq_mask_t get_irq(void)
{
    unsigned long value;

    __asm__ volatile("csrr %0, sie" : "=r"(value));
    return sie_to_irq_mask(value);
}

irq_mask_t set_irq(irq_mask_t mask)
{
    irq_mask_t previous = get_irq();
    unsigned long value = irq_mask_to_sie(mask & IRQ_MASK_ALL);

    __asm__ volatile("csrw sie, %0" : : "r"(value) : "memory");
    return previous;
}

irq_mask_t enable_irq(irq_mask_t mask)
{
    irq_mask_t previous = get_irq();
    unsigned long value = irq_mask_to_sie(mask & IRQ_MASK_ALL);

    __asm__ volatile("csrs sie, %0" : : "r"(value) : "memory");
    return previous;
}

irq_mask_t disable_irq(irq_mask_t mask)
{
    irq_mask_t previous = get_irq();
    unsigned long value = irq_mask_to_sie(mask & IRQ_MASK_ALL);

    __asm__ volatile("csrc sie, %0" : : "r"(value) : "memory");
    return previous;
}

bool global_irq(bool enabled)
{
    unsigned long previous;

    __asm__ volatile("csrr %0, sstatus" : "=r"(previous));
    if (enabled)
        __asm__ volatile("csrs sstatus, %0" : : "r"(SSTATUS_SIE) : "memory");
    else
        __asm__ volatile("csrc sstatus, %0" : : "r"(SSTATUS_SIE) : "memory");

    return (previous & SSTATUS_SIE) != 0UL;
}

i32 enable_irq_source(irq_id_t irq)
{
    u32 source;
    volatile u32 *enable;
    u32 bit;
    bool previous_global;
    i32 status = external_source(irq, &source);

    if (status != IRQ_STATUS_OK)
        return status;

    enable = plic_enable_word(source);
    bit = UINT32_C(1) << (source % 32U);

    previous_global = global_irq(0);
    if (*plic_priority(source) == 0U)
        *plic_priority(source) = 1U;
    *plic_threshold() = 0U;
    *enable |= bit;
    global_irq(previous_global);

    return IRQ_STATUS_OK;
}

i32 disable_irq_source(irq_id_t irq)
{
    u32 source;
    volatile u32 *enable;
    u32 bit;
    bool previous_global;
    i32 status = external_source(irq, &source);

    if (status != IRQ_STATUS_OK)
        return status;

    enable = plic_enable_word(source);
    bit = UINT32_C(1) << (source % 32U);

    previous_global = global_irq(0);
    *enable &= ~bit;
    global_irq(previous_global);

    return IRQ_STATUS_OK;
}

i32 claim_external_irq(irq_id_t *irq)
{
    u32 source;

    if (irq == 0)
        return IRQ_ERROR_INVALID;

    source = *plic_claim_complete();
    if (source == 0U)
        return IRQ_STATUS_NONE;
    if (source > PLIC_NUM_SOURCES)
        return IRQ_ERROR_INVALID;

    *irq = IRQ_ID_EXTERNAL(source);
    return IRQ_STATUS_CLAIMED;
}

i32 complete_external_irq(irq_id_t irq)
{
    u32 source;
    i32 status = external_source(irq, &source);

    if (status != IRQ_STATUS_OK)
        return status;

    *plic_claim_complete() = source;
    return IRQ_STATUS_OK;
}
