/* generated by gpt-5.6-sol<noreply@openai.com> @ codex
 * Linux user backend：中断屏蔽语义转发到 linux_user_signal（信号掩码）。
 * disable/enable/set/get 与 QEMU 侧语义对齐（保存/恢复现场）；
 * 中断源级操作与 trap entry 仍不支持——更高层可用 ptrace 等机制，
 * 不把该策略耦合进 00arch。
 */

#include "irq.h"

#include "linux_user_signal.h"

#if !defined(SHYOS_BACKEND_LINUX_USER)
#error "irq_linux_user.c requires SHYOS_BACKEND_LINUX_USER"
#endif

i32 set_trap_entry(usize entry)
{
    (void)entry;
    return IRQ_ERROR_UNSUPPORTED;
}

irq_mask_t set_irq(irq_mask_t mask)
{
    /* signal_enable 即 SIG_SETMASK，语义与 set_irq 一致 */
    return (irq_mask_t)signal_enable(mask);
}

irq_mask_t enable_irq(irq_mask_t mask)
{
    return (irq_mask_t)signal_unblock(mask);
}

irq_mask_t disable_irq(irq_mask_t mask)
{
    return (irq_mask_t)signal_disable(mask);
}

irq_mask_t get_irq(void)
{
    /* 空集 UNBLOCK：不修改掩码，只读回当前值 */
    return (irq_mask_t)signal_unblock(0);
}

bool global_irq(bool enabled)
{
    u64 prev;

    if (enabled) {
        prev = signal_unblock(SIGNAL_MASK_ALL);
    } else {
        prev = signal_disable(SIGNAL_MASK_ALL);
    }
    /* 之前不是全屏蔽即视为"开" */
    return prev != SIGNAL_MASK_ALL;
}

i32 enable_irq_source(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}

i32 disable_irq_source(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}

i32 claim_external_irq(irq_id_t *irq)
{
    if (irq == 0)
        return IRQ_ERROR_INVALID;

    *irq = 0;
    return IRQ_STATUS_NONE;
}

i32 complete_external_irq(irq_id_t irq)
{
    (void)irq;
    return IRQ_ERROR_UNSUPPORTED;
}
