//generated by gpt-5<noreply@openai.com> @ codex
#include "rawbuf.h"

#include "alloc.h"
#include "string_noalloc.h"

ResultRawBuf raw_buf_new(usize elem_size)
{
	if (elem_size == 0) {
		return RawBufErr(ERROR_INVALID_ARGUMENT);
	}
	return RawBufOk((RawBuf){
		.data = NULL,
		.cap = 0,
		.elem_size = elem_size,
	});
}

RawBuf raw_buf_from_raw_parts(void *data, usize cap, usize elem_size)
{
	return (RawBuf){
		.data = data,
		.cap = cap,
		.elem_size = elem_size,
	};
}

i32 raw_buf_reserve(RawBuf *buf, usize capacity)
{
	usize new_cap;
	void *new_data;

	if (capacity <= buf->cap) {
		return 0;
	}
	new_cap = buf->cap == 0 ? 5 : buf->cap;
	while (new_cap < capacity) {
		usize growth = new_cap / 2;

		if (growth == 0) {
			growth = 1;
		}
		if (new_cap > (usize)-1 - growth) {
			return -1;
		}
		new_cap += growth;
	}
	if (new_cap > (usize)-1 / buf->elem_size) {
		return -1;
	}
	new_data = malloc(new_cap * buf->elem_size);
	if (new_data == NULL) {
		return -1;
	}
	if (buf->cap != 0) {
		memcpy(new_data, buf->data, buf->cap * buf->elem_size);
	}
	if (buf->data != NULL) {
		free(buf->data);
	}
	buf->data = new_data;
	buf->cap = new_cap;
	return 0;
}

void *raw_buf_get(const RawBuf *buf, usize index)
{
	return (void *)((char *)buf->data + index * buf->elem_size);
}

void raw_buf_drop(void *self)
{
	RawBuf *buf = self;

	if (buf->data != NULL) {
		free(buf->data);
	}
	memset(buf, 0, sizeof(*buf));
}

void *raw_buf_clone_obj(const void *source_ptr)
{
	const RawBuf *source = source_ptr;
	RawBuf *copy;
	ResultRawBuf result;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	result = raw_buf_new(source->elem_size);
	if (RawBuf_is_err(&result)) {
		free(copy);
		return NULL;
	}
	*copy = RawBuf_unwrap(&result);
	if (raw_buf_reserve(copy, source->cap) != 0) {
		raw_buf_drop(copy);
		free(copy);
		return NULL;
	}
	if (source->cap != 0) {
		memcpy(copy->data, source->data,
			source->cap * source->elem_size);
	}
	return copy;
}

ResultRawBuf raw_buf_clone(const RawBuf *source)
{
	RawBuf *copy = raw_buf_clone_obj(source);
	RawBuf value;

	if (copy == NULL) {
		return RawBufErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return RawBufOk(value);
}
