//generated by grok-4.5<noreply@x.ai> @ pi
//qemu riscv virt平台的UART / 关机相关定义

#ifndef SHYOS_BOARD_QEMU_VIRT_QEMU_H
#define SHYOS_BOARD_QEMU_VIRT_QEMU_H

/*
 * QEMU virt 默认机器内存：256 MiB，从 0x80000000 起。
 * simple allocator 的 arena 放在 board define 里：
 *   HEAP_START = RAM_BASE + 64MiB
 *   HEAP_SIZE  = RAM_SIZE - 64MiB = 192MiB
 * （64MiB 保护区留给 text/data/bss/stack；192 而非 196，是为了不越出 256MiB RAM）
 */
#define RAM_BASE   0x80000000UL
#define RAM_SIZE   0x10000000UL /* 256 MiB */
#define HEAP_START ((void *)(RAM_BASE + 0x04000000UL)) /* +64 MiB = 0x84000000 */
#define HEAP_SIZE  (RAM_SIZE - 0x04000000UL) /* 192 MiB = 0x0C000000 */

/* QEMU virt: NS16550A MMIO UART0 */
#define UART0_BASE 0x10000000UL

#define UART_THR 0 /* Transmit Holding Register (write) */
#define UART_RBR 0 /* Receive Buffer Register (read) */
#define UART_IER 1 /* Interrupt Enable Register */
#define UART_IIR 2 /* Interrupt Identification Register (read) */
#define UART_FCR 2 /* FIFO Control Register (write) */
#define UART_LCR 3 /* Line Control Register */
#define UART_MCR 4 /* Modem Control Register */
#define UART_LSR 5 /* Line Status Register */
#define UART_MSR 6 /* Modem Status Register */
#define UART_SCR 7 /* Scratch Register */

/* Line Status Register bits */
#define UART_LSR_DR   (1u << 0) /* Data Ready */
#define UART_LSR_OE   (1u << 1) /* Overrun Error */
#define UART_LSR_PE   (1u << 2) /* Parity Error */
#define UART_LSR_FE   (1u << 3) /* Framing Error */
#define UART_LSR_BI   (1u << 4) /* Break Interrupt */
#define UART_LSR_THRE (1u << 5) /* Transmitter Holding Register Empty */
#define UART_LSR_TEMT (1u << 6) /* Transmitter Empty */
#define UART_LSR_FIFOERR (1u << 7) /* Error in RCVR FIFO */

/* QEMU virt: SiFive test finisher（写 0x5555 正常关机） */
#define SIFIVE_TEST_BASE 0x100000UL
#define SIFIVE_TEST_PASS 0x5555U
#define SIFIVE_TEST_FAIL 0x3333U

/*
 * QEMU virt PLIC。当前启动路径只启用 hart 0 的 S-mode context：
 * context 0 = hart 0 M-mode，context 1 = hart 0 S-mode。
 */
#define PLIC_BASE 0x0c000000UL
#define PLIC_NUM_SOURCES 95U
#define PLIC_PRIORITY_OFFSET 0x000000UL
#define PLIC_SCONTEXT_ENABLE_OFFSET 0x002080UL
#define PLIC_SCONTEXT_OFFSET 0x201000UL
#define PLIC_THRESHOLD_OFFSET 0x0UL
#define PLIC_CLAIM_OFFSET 0x4UL

#define UART0_IRQ 10U

#endif /* SHYOS_BOARD_QEMU_VIRT_QEMU_H */
