//generated by grok-4.5<noreply@x.ai> @ cursor
//trap 表驱动分发：Rust 实现，C ABI 见 trap.h
#![no_std]
#![cfg(not(SHYOS_BACKEND_LINUX_USER))]

use core::cell::UnsafeCell;

use irq::{IRQ_MASK_ALL, IrqError, claim_external_irq, complete_external_irq, enable_irq, irq_id_source, set_irq, set_trap_entry};
use panic::panic_cstr;

pub use irq;

pub const TRAP_EXCEPTION_MAX: usize = 32;
pub const TRAP_INTERRUPT_MAX: usize = 32;
pub const TRAP_EXTERNAL_MAX: usize = 96;

pub const TRAP_IRQ_CAUSE_SOFTWARE: usize = 1;
pub const TRAP_IRQ_CAUSE_TIMER: usize = 5;
pub const TRAP_IRQ_CAUSE_EXTERNAL: usize = 9;

pub type TrapHandler = Option<extern "C" fn(*mut TrapContext)>;

#[repr(C)]
pub struct TrapContext {
    pub orig_sp: usize,
    pub x1: usize,
    pub x2: usize,
    pub x3: usize,
    pub x4: usize,
    pub x5: usize,
    pub x6: usize,
    pub x7: usize,
    pub x8: usize,
    pub x9: usize,
    pub x10: usize,
    pub x11: usize,
    pub x12: usize,
    pub x13: usize,
    pub x14: usize,
    pub x15: usize,
    pub x16: usize,
    pub x17: usize,
    pub x18: usize,
    pub x19: usize,
    pub x20: usize,
    pub x21: usize,
    pub x22: usize,
    pub x23: usize,
    pub x24: usize,
    pub x25: usize,
    pub x26: usize,
    pub x27: usize,
    pub x28: usize,
    pub x29: usize,
    pub x30: usize,
    pub x31: usize,
    pub sepc: usize,
    pub sstatus: usize,
    pub scause: usize,
}

#[repr(C)]
struct TrapEntry {
    // Option<fn>：在 C 自然就是指针 / null
    exception_handlers: [TrapHandler; TRAP_EXCEPTION_MAX],
    cause_interrupt_table: [TrapHandler; TRAP_INTERRUPT_MAX],
    cause_external_table: [TrapHandler; TRAP_EXTERNAL_MAX],
}

struct TrapState(UnsafeCell<TrapEntry>);

// 单 hart 表；注册与 dispatch 由调用方保证不并发踩踏。
unsafe impl Sync for TrapState {}

static TRAP: TrapState = TrapState(UnsafeCell::new(TrapEntry {
    exception_handlers: [None; TRAP_EXCEPTION_MAX],
    cause_interrupt_table: [None; TRAP_INTERRUPT_MAX],
    cause_external_table: [None; TRAP_EXTERNAL_MAX],
}));

#[inline]
fn trap() -> *mut TrapEntry {
    TRAP.0.get()
}

extern "C" fn trap_external_dispatch(ctx: *mut TrapContext) {
    match claim_external_irq() {
        Ok(Some(irq)) => {
            let source = irq_id_source(irq) as usize;
            let handler = unsafe {
                if source < TRAP_EXTERNAL_MAX {
                    (*trap()).cause_external_table[source]
                } else {
                    None
                }
            };
            if let Some(handler) = handler {
                handler(ctx);
            } else {
                trap_unhandled();
            }
            let _ = complete_external_irq(irq);
        }
        _ => trap_unhandled(),
    }
}

#[no_mangle]
pub extern "C" fn init_trap_entry(entry: usize) -> i32 {
    unsafe {
        *trap() = TrapEntry {
            exception_handlers: [None; TRAP_EXCEPTION_MAX],
            cause_interrupt_table: [None; TRAP_INTERRUPT_MAX],
            cause_external_table: [None; TRAP_EXTERNAL_MAX],
        };
        (*trap()).cause_interrupt_table[TRAP_IRQ_CAUSE_EXTERNAL] = Some(trap_external_dispatch);
    }
    match unsafe { set_trap_entry(entry) } {
        Ok(()) => 0,
        Err(IrqError::Invalid) => -1,
        Err(IrqError::Unsupported) => -2,
        Err(IrqError::UnexpectedStatus(value)) => value,
    }
}

#[no_mangle]
pub extern "C" fn trap_dispatch(scause: usize, ctx: *mut TrapContext) {


    //中断处理流程允许重入，且可能时间比较长 不应持续关闭
    let previous_irq = enable_irq(IRQ_MASK_ALL);

    let is_interrupt = (scause as isize) < 0;
    let cause = scause & !(1usize << (usize::BITS - 1));
    let handler = unsafe {
        if is_interrupt {
            if cause < TRAP_INTERRUPT_MAX {
                (*trap()).cause_interrupt_table[cause]
            } else {
                None
            }
        } else if cause < TRAP_EXCEPTION_MAX {
            (*trap()).exception_handlers[cause]
        } else {
            None
        }
    };
    if let Some(handler) = handler {
        handler(ctx);
    } else {
        trap_unhandled();
    }
    set_irq(previous_irq);
}

#[no_mangle]
pub extern "C" fn trap_set_exception_handler(cause: usize, handler: TrapHandler) {
    if cause < TRAP_EXCEPTION_MAX {
        unsafe {
            (*trap()).exception_handlers[cause] = handler;
        }
    }
}

#[no_mangle]
pub extern "C" fn trap_set_interrupt_handler(cause: usize, handler: TrapHandler) {
    if cause < TRAP_INTERRUPT_MAX {
        unsafe {
            (*trap()).cause_interrupt_table[cause] = handler;
        }
    }
}

#[no_mangle]
pub extern "C" fn trap_set_external_handler(source: usize, handler: TrapHandler) {
    if source < TRAP_EXTERNAL_MAX {
        unsafe {
            (*trap()).cause_external_table[source] = handler;
        }
    }
}

#[no_mangle]
pub extern "C" fn trap_unhandled() -> ! {
    panic_cstr(c"unhandled trap")
}
