/* generated by grok-4.5<noreply@x.ai> @ cursor
 * trap 表驱动分发 C ABI；实现由 Rust crate shyos-trap 提供。
 */
#ifndef SHYOS_TRAP_H
#define SHYOS_TRAP_H

#include "shy_type.h"

#define TRAP_EXCEPTION_MAX 32U
#define TRAP_INTERRUPT_MAX 32U
/* 覆盖 QEMU virt PLIC sources 1..=95 */
#define TRAP_EXTERNAL_MAX  96U

#define TRAP_IRQ_CAUSE_SOFTWARE 1U
#define TRAP_IRQ_CAUSE_TIMER    5U
#define TRAP_IRQ_CAUSE_EXTERNAL 9U

typedef void (*trap_handler_t)(void);

/*
 * 清空并安装默认 external 分发（cause 9），再 set_trap_entry(entry)。
 * 返回值与 set_trap_entry 相同：0 成功，<0 错误。
 */
i32 init_trap_entry(usize entry);

/* 汇编入口保存现场后调用；按 scause 查表分发。 */
void trap_dispatch(usize scause);

/* handler 为 NULL 表示清空该槽。越界 cause/source 被忽略。 */
void trap_set_exception_handler(usize cause, trap_handler_t handler);
void trap_set_interrupt_handler(usize cause, trap_handler_t handler);
void trap_set_external_handler(usize source, trap_handler_t handler);

/* 空槽：直接 panic。 */
void trap_unhandled(void) __attribute__((noreturn));

#endif /* SHYOS_TRAP_H */
