//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//Rust early console：
// - FFI 对齐 C 的 early_*
// - early_print! / early_println! / early_scanf! 明确是early 路径
// - 更高层真正的 print 以后再做，不占用 print!/println! 名字

#![no_std]

use core::ffi::{c_char, c_int};
use core::fmt;

// ---- FFI：与 early_stdio.h / early_stdio.c 对齐 ----

unsafe extern "C" {
    pub safe fn early_putchar(c: c_int) -> c_int;
    pub safe fn early_getchar() -> c_int;

    pub fn early_printf(fmt: *const c_char, ...) -> c_int;
    pub fn early_scanf(fmt: *const c_char, ...) -> c_int;

    pub fn early_sprintf(buf: *mut c_char, fmt: *const c_char, ...) -> c_int;
    pub fn early_snprintf(buf: *mut c_char, n: usize, fmt: *const c_char, ...) -> c_int;
}

// ---- Rust early 格式化输出：始终走轮询 UART ----

pub struct EarlyConsole;

impl fmt::Write for EarlyConsole {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        for b in s.bytes() {
            uart::early_raw_putc(b);
        }
        Ok(())
    }
}

#[inline]
pub fn _early_print(args: fmt::Arguments) {
    let _ = fmt::write(&mut EarlyConsole, args);
}

/// early println!，基于 core::fmt，输出到 raw UART。
#[macro_export]
macro_rules! early_println {
    () => {
        $crate::_early_print(core::format_args!("\n"))
    };
    ($($arg:tt)*) => {
        $crate::_early_print(core::format_args!("{}\n", core::format_args!($($arg)*)))
    };
}

/// early print!，不换行。
#[macro_export]
macro_rules! early_print {
    ($($arg:tt)*) => {
        $crate::_early_print(core::format_args!($($arg)*))
    };
}

/// 包装 C early_scanf。
/// 用法：
/// ```ignore
/// let mut x: i32 = 0;
/// let n = unsafe { early_scanf!(c"%d", &mut x as *mut i32) };
/// ```
/// 格式串须为 C 字符串（c"..."）；其余参数按 C scanf 传指针。
#[macro_export]
macro_rules! early_scanf {
    ($fmt:expr $(, $arg:expr)* $(,)?) => {
        $crate::early_scanf(($fmt).as_ptr() $(, $arg)*)
    };
}
