# generated by gpt-5<noreply@openai.com> @ codex

import os
import struct

import gdb


DEFAULT_START = 0x84000000
DEFAULT_END = 0x90000000
DEFAULT_PAGE_SIZE = 0x1000
DEFAULT_HEAD_SIZE = 8
DEFAULT_OUTPUT = "/tmp/shyos-page-heads"


class DumpPageHeads(gdb.Command):
    """Dump each page address and its first pointer-sized value."""

    def __init__(self):
        super().__init__("dump-page-heads", gdb.COMMAND_DATA)

    def invoke(self, argument, from_tty):
        args = gdb.string_to_argv(argument)
        if len(args) > 5:
            raise gdb.GdbError(
                "usage: dump-page-heads [output-prefix] [start] [end] "
                "[page-size] [head-size]"
            )

        output = args[0] if len(args) >= 1 else DEFAULT_OUTPUT
        start = int(args[1], 0) if len(args) >= 2 else DEFAULT_START
        end = int(args[2], 0) if len(args) >= 3 else DEFAULT_END
        page_size = int(args[3], 0) if len(args) >= 4 else DEFAULT_PAGE_SIZE
        head_size = int(args[4], 0) if len(args) >= 5 else DEFAULT_HEAD_SIZE

        if start >= end:
            raise gdb.GdbError("start must be smaller than end")
        if page_size <= 0 or head_size <= 0:
            raise gdb.GdbError("page-size and head-size must be positive")

        output = os.path.abspath(os.path.expanduser(output))
        parent = os.path.dirname(output)
        if parent:
            os.makedirs(parent, exist_ok=True)

        text_path = output + ".tsv"
        binary_path = output + ".bin"
        inferior = gdb.selected_inferior()
        count = 0

        with open(text_path, "w", encoding="ascii") as text_file:
            with open(binary_path, "wb") as binary_file:
                text_file.write("page_address\thead_value\n")
                for address in range(start, end, page_size):
                    head = bytes(inferior.read_memory(address, head_size))
                    value = int.from_bytes(head, byteorder="little")
                    text_file.write(f"0x{address:016x}\t0x{value:016x}\n")
                    binary_file.write(struct.pack("<Q", address))
                    binary_file.write(head)
                    count += 1

        gdb.write(
            f"dumped {count} page heads to {text_path} and {binary_path}\n"
        )


DumpPageHeads()
