//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//allocator 通用接口

#ifndef SHYOS_ALLOC_H
#define SHYOS_ALLOC_H

#include "shy_type.h"

i32 heap_init(void *base, usize size);

void *malloc(usize size);
void free(void *ptr);

#endif /* SHYOS_ALLOC_H */
