//generated by gpt-5<noreply@openai.com> @ codex
//allocator 通用 C ABI 的 no_std Rust 接口

#![no_std]

use core::ffi::c_void;

unsafe extern "C" {
    #[link_name = "heap_init"]
    fn c_heap_init(base: *mut c_void, size: usize) -> i32;

    #[link_name = "malloc"]
    fn c_malloc(size: usize) -> *mut c_void;

    #[link_name = "free"]
    fn c_free(ptr: *mut c_void);
}

pub fn heap_init(base: *mut u8, size: usize) -> Result<(), i32> {
    let rc = unsafe { c_heap_init(base.cast(), size) };
    if rc == 0 {
        Ok(())
    } else {
        Err(rc)
    }
}

pub unsafe fn malloc(size: usize) -> *mut u8 {
    c_malloc(size).cast()
}

pub unsafe fn free(ptr: *mut u8) {
    c_free(ptr.cast());
}
