//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//int main()
//本项目的 kernel 实现

#include "shy_type.h"
#include "early_stdio.h"
#include "time.h"

i32 main(void)
{
    early_printf("Welcome to SHYOS!\n");
   
    for(int i=0;i<10;i++){
        early_printf("time:%ld\n",(i64)get_time());
    }
    return 0;
}
