//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//int main()
//本项目的 kernel 实现

#include "shy_type.h"

i32 main(void)
{
#if defined(SHYOS_BACKEND_LINUX_USER)
    return 0;
#else
    for (;;) {
        __asm__ volatile ("wfi");
    }
#endif
}
