//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//pmm capability 通用 C ABI 的 no_std Rust 接口

#![no_std]

use core::ffi::c_void;

#[cfg(not(SHYOS_PMM_NONE))]
unsafe extern "C" {
    #[link_name = "malloc_page"]
    fn c_malloc_page() -> *mut c_void;

    #[link_name = "free_page"]
    fn c_free_page(ptr: *mut c_void);
}

/// NONE provider 下的空实现：保持与实体 provider 同名符号。
#[cfg(SHYOS_PMM_NONE)]
#[no_mangle]
pub extern "C" fn page_memory_init() {}

/// 分配一个 4K 对齐页；失败返回空指针。
#[cfg(not(SHYOS_PMM_NONE))]
pub fn malloc_page() -> *mut u8 {
    unsafe { c_malloc_page().cast() }
}

/// 归还 malloc_page 分配的单页。
#[cfg(not(SHYOS_PMM_NONE))]
pub unsafe fn free_page(ptr: *mut u8) {
    c_free_page(ptr.cast());
}
