//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//pmm capability：4K 页分配通用接口；具体实现由 provider 提供。
//page_memory_init 始终声明（NONE provider 下为空实现）；
//malloc_page / free_page 只在选择了实体 provider 时可见。

#ifndef SHYOS_PMM_H
#define SHYOS_PMM_H

#include "shy_type.h"

void page_memory_init(void);

#if !defined(SHYOS_PMM_NONE)
void *malloc_page(void);
void free_page(void *ptr);
#endif

#endif /* SHYOS_PMM_H */
