//generated by gpt-5<noreply@openai.com> @ codex
//C-only 03basic image 的 Rust 闭包与 panic handler。

#![no_std]

pub use shyos_basic::*;

#[panic_handler]
fn panic(info: &::core::panic::PanicInfo) -> ! {
    shyos_basic::panic::handle_panic(info)
}
