//generated by gpt-5<noreply@openai.com> @ codex
//C-only 00arch image 的 Rust 闭包与最小 panic handler。

#![no_std]

pub use shyos_arch::*;

#[panic_handler]
fn panic(_info: &::core::panic::PanicInfo) -> ! {
    shyos_arch::shutdown::shutdown(-1)
}
