//generated by grok-4.5<noreply@x.ai> @ pi
//从 C 获得 shutdown 函数（link_name = "shutdown"，声明为 c_shutdown）

#![no_std]

unsafe extern "C" {
    #[link_name = "shutdown"]
    fn c_shutdown(code: i32) -> !;
}

/// Rust 侧关机封装；code 会传到 QEMU finisher / 平台关机路径。
#[inline]
pub fn shutdown(code: i32) -> ! {
    unsafe { c_shutdown(code) }
}
