//generated by grok-4.5<noreply@x.ai> @ cursor
//时间 ABI：C 符号 + Rust 包装。linux_user 的 get_time/init_time 在 C；
//QEMU 在此提供。set_timer 仅 QEMU 底层 deadline，软件定时见 05task/timer。

#![no_std]

unsafe extern "C" {
    #[link_name = "get_time"]
    fn c_get_time() -> u64;
}

/// 返回 `init_time` 之后的毫秒。
pub fn get_time() -> u64 {
    unsafe { c_get_time() }
}

#[cfg(SHYOS_BACKEND_QEMU_VIRT)]
mod qemu_virt {
    #[unsafe(no_mangle)]
    static mut TIME_BASE: u64 = 0;

    #[unsafe(no_mangle)]
    // 设定相对当前的 deadline（毫秒），到期触发时钟中断。
    unsafe extern "C" fn set_timer(ms: u64) {
        sbi_rt::set_timer(riscv::register::time::read() as u64 + ms * 10000);
    }

    #[unsafe(no_mangle)]
    /// 返回开机后的毫秒
    unsafe extern "C" fn get_time() -> u64 {
        unsafe { (riscv::register::cycle::read64() - TIME_BASE) / 10_000 }
    }

    #[unsafe(no_mangle)]
    unsafe extern "C" fn init_time() {
        unsafe {
            TIME_BASE = riscv::register::cycle::read64();
        }
    }
}

#[cfg(SHYOS_BACKEND_QEMU_VIRT)]
use qemu_virt as _;
