//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//C-only 06page_memory image 的 Rust 闭包与 panic handler。

#![no_std]

pub use shyos_page_memory::*;

#[panic_handler]
fn panic(info: &::core::panic::PanicInfo) -> ! {
    shyos_page_memory::panic::handle_panic(info)
}
