/* generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
 * 始终存在的 early console 与缓冲格式化接口。
 */
#ifndef SHYOS_EARLY_STDIO_H
#define SHYOS_EARLY_STDIO_H

#include <stdarg.h>
#include "shy_type.h"

#ifdef __cplusplus
extern "C" {
#endif

i32 early_putchar(i32 c);
i32 early_getchar(void);

i32 early_printf(const char *fmt, ...);
i32 early_vprintf(const char *fmt, va_list ap);

i32 early_scanf(const char *fmt, ...);
i32 early_vscanf(const char *fmt, va_list ap);

i32 early_sprintf(char *buf, const char *fmt, ...);
i32 early_snprintf(char *buf, usize n, const char *fmt, ...);
i32 early_vsnprintf(char *buf, usize n, const char *fmt, va_list ap);

#ifdef __cplusplus
}
#endif

#endif /* SHYOS_EARLY_STDIO_H */
