/* generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
 * freestanding 忙等 IO 子集（early console）
 * early_printf/early_scanf 固定走 early raw UART 轮询
 * 无前缀 stdio 共用格式化逻辑，走所选 raw UART provider
 * early_sprintf/early_snprintf 纯缓冲，无设备等待
 * 支持：%% %c %s %d %i %u %x %X %p，以及简单宽度 / 0 填充
 * early_scanf：%c %s %d %i %u %x %X，跳过空白
 */

#include "early_stdio.h"
#include "stdio.h"
#include "uart.h"

#include <stdint.h>

/* ---------------- busy put/get ---------------- */

i32 early_putchar(i32 c)
{
    early_raw_putc((char)c);
    return (u8)c;
}

i32 early_getchar(void)
{
    return (u8)early_raw_getc();
}

i32 putchar(i32 c)
{
    raw_putc((char)c);
    return (u8)c;
}

i32 getchar(void)
{
    return (u8)raw_getc();
}

/* ---------------- out context ---------------- */

struct out {
    char *buf;
    usize cap;   /* snprintf: 容量；0 表示调用 put */
    usize len;   /* 已写（不含 NUL；可超过 cap-1） */
    i32 (*put)(i32 c);
};

static void out_emit(struct out *o, char ch)
{
    if (o->cap == 0) {
        o->put((u8)ch);
    } else if (o->len + 1 < o->cap) {
        o->buf[o->len] = ch;
    }
    o->len++;
}

static void out_write(struct out *o, const char *s, usize n)
{
    usize i;
    for (i = 0; i < n; i++)
        out_emit(o, s[i]);
}

/* ---------------- number helpers ---------------- */

static unsigned long long uabs_ll(long long v)
{
    if (v < 0)
        return (unsigned long long)(-(v + 1)) + 1ULL;
    return (unsigned long long)v;
}

static i32 emit_uint(struct out *o, unsigned long long v, u32 base,
                     bool upper, i32 width, bool zero_pad)
{
    char tmp[32];
    const char *digits = upper ? "0123456789ABCDEF" : "0123456789abcdef";
    i32 n = 0;
    i32 i;
    i32 pad;

    if (base < 2 || base > 16)
        base = 10;

    if (v == 0)
        tmp[n++] = '0';
    else {
        while (v) {
            tmp[n++] = digits[v % base];
            v /= base;
        }
    }

    pad = width > n ? width - n : 0;
    for (i = 0; i < pad; i++)
        out_emit(o, zero_pad ? '0' : ' ');
    for (i = n - 1; i >= 0; i--)
        out_emit(o, tmp[i]);
    return n + pad;
}

static i32 emit_int(struct out *o, long long v, i32 width, bool zero_pad)
{
    i32 extra = 0;
    if (v < 0) {
        out_emit(o, '-');
        extra = 1;
        if (width > 0)
            width--;
        return extra + emit_uint(o, uabs_ll(v), 10, 0, width, zero_pad);
    }
    return emit_uint(o, (unsigned long long)v, 10, 0, width, zero_pad);
}

/* ---------------- busy printf core ---------------- */

static i32 format_out(struct out *o, const char *fmt, va_list ap)
{
    const char *p = fmt;

    while (*p) {
        if (*p != '%') {
            out_emit(o, *p++);
            continue;
        }
        p++; /* skip '%' */

        if (*p == '%') {
            out_emit(o, '%');
            p++;
            continue;
        }

        {
            bool zero_pad = false;
            i32 width = 0;
            i32 long_flag = 0; /* 1=long, 2=long long */

            if (*p == '0') {
                zero_pad = 1;
                p++;
            }
            while (*p >= '0' && *p <= '9') {
                width = width * 10 + (*p - '0');
                p++;
            }
            while (*p == 'l') {
                long_flag++;
                p++;
            }

            switch (*p) {
            case 'c': {
                char ch = (char)va_arg(ap, i32);
                i32 pad = width > 1 ? width - 1 : 0;
                i32 i;
                for (i = 0; i < pad; i++)
                    out_emit(o, ' ');
                out_emit(o, ch);
                p++;
                break;
            }
            case 's': {
                const char *s = va_arg(ap, const char *);
                usize slen = 0;
                i32 pad;
                i32 i;
                if (!s)
                    s = "(null)";
                while (s[slen])
                    slen++;
                pad = width > (i32)slen ? width - (i32)slen : 0;
                for (i = 0; i < pad; i++)
                    out_emit(o, ' ');
                out_write(o, s, slen);
                p++;
                break;
            }
            case 'd':
            case 'i': {
                long long v;
                if (long_flag >= 2)
                    v = va_arg(ap, long long);
                else if (long_flag == 1)
                    v = va_arg(ap, long);
                else
                    v = va_arg(ap, i32);
                emit_int(o, v, width, zero_pad);
                p++;
                break;
            }
            case 'u': {
                unsigned long long v;
                if (long_flag >= 2)
                    v = va_arg(ap, unsigned long long);
                else if (long_flag == 1)
                    v = va_arg(ap, unsigned long);
                else
                    v = va_arg(ap, u32);
                emit_uint(o, v, 10, 0, width, zero_pad);
                p++;
                break;
            }
            case 'x':
            case 'X': {
                unsigned long long v;
                bool upper = (*p == 'X');
                if (long_flag >= 2)
                    v = va_arg(ap, unsigned long long);
                else if (long_flag == 1)
                    v = va_arg(ap, unsigned long);
                else
                    v = va_arg(ap, u32);
                emit_uint(o, v, 16, upper, width, zero_pad);
                p++;
                break;
            }
            case 'p': {
                unsigned long long v = (unsigned long long)(usize)va_arg(ap, void *);
                out_write(o, "0x", 2);
                emit_uint(o, v, 16, 0, width > 2 ? width - 2 : 0, 1);
                p++;
                break;
            }
            default:
                /* 未知说明符：原样输出 */
                out_emit(o, '%');
                if (*p)
                    out_emit(o, *p++);
                break;
            }
        }
    }

    if (o->cap > 0) {
        usize nul_at = o->len < o->cap ? o->len : o->cap - 1;
        if (o->cap)
            o->buf[nul_at] = '\0';
    }
    return (i32)o->len;
}

i32 early_vprintf(const char *fmt, va_list ap)
{
    struct out o = { .put = early_putchar };
    return format_out(&o, fmt, ap);
}

i32 vprintf(const char *fmt, va_list ap)
{
    struct out o = { .put = putchar };
    return format_out(&o, fmt, ap);
}

i32 early_printf(const char *fmt, ...)
{
    va_list ap;
    i32 n;
    va_start(ap, fmt);
    n = early_vprintf(fmt, ap);
    va_end(ap);
    return n;
}

i32 printf(const char *fmt, ...)
{
    va_list ap;
    i32 n;
    va_start(ap, fmt);
    n = vprintf(fmt, ap);
    va_end(ap);
    return n;
}

i32 early_vsnprintf(char *buf, usize n, const char *fmt, va_list ap)
{
    struct out o;
    char dummy;

    /* n==0 或 buf==NULL：只计数，不写入 */
    if (!buf || n == 0) {
        o.buf = &dummy;
        o.cap = 1;
        o.len = 0;
        return format_out(&o, fmt, ap);
    }

    o.buf = buf;
    o.cap = n;
    o.len = 0;
    return format_out(&o, fmt, ap);
}

i32 early_snprintf(char *buf, usize n, const char *fmt, ...)
{
    va_list ap;
    i32 r;
    va_start(ap, fmt);
    r = early_vsnprintf(buf, n, fmt, ap);
    va_end(ap);
    return r;
}

i32 early_sprintf(char *buf, const char *fmt, ...)
{
    va_list ap;
    i32 r;
    va_start(ap, fmt);
    r = early_vsnprintf(buf, (usize)-1 / 2, fmt, ap);
    va_end(ap);
    return r;
}

i32 vsnprintf(char *buf, usize n, const char *fmt, va_list ap)
{
    return early_vsnprintf(buf, n, fmt, ap);
}

i32 snprintf(char *buf, usize n, const char *fmt, ...)
{
    va_list ap;
    i32 r;
    va_start(ap, fmt);
    r = vsnprintf(buf, n, fmt, ap);
    va_end(ap);
    return r;
}

i32 sprintf(char *buf, const char *fmt, ...)
{
    va_list ap;
    i32 r;
    va_start(ap, fmt);
    r = vsnprintf(buf, (usize)-1 / 2, fmt, ap);
    va_end(ap);
    return r;
}

/* ---------------- busy scanf ---------------- */

static bool is_space(i32 c)
{
    return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' || c == '\v';
}

struct in {
    i32 peeked;
    bool has_peek;
    i32 (*get)(void);
};

static i32 in_get(struct in *in)
{
    if (in->has_peek) {
        in->has_peek = 0;
        return in->peeked;
    }
    return in->get();
}

static void in_unget(struct in *in, i32 c)
{
    in->peeked = c;
    in->has_peek = 1;
}

static void skip_space(struct in *in)
{
    i32 c;
    for (;;) {
        c = in_get(in);
        if (!is_space(c)) {
            in_unget(in, c);
            return;
        }
    }
}

static i32 scan_int(struct in *in, i32 base, unsigned long long *out, bool *neg)
{
    i32 c;
    i32 digits = 0;
    unsigned long long v = 0;

    *neg = 0;
    skip_space(in);
    c = in_get(in);
    if (c == '-' || c == '+') {
        *neg = (c == '-');
        c = in_get(in);
    }
    if (base == 0) {
        if (c == '0') {
            i32 c2 = in_get(in);
            if (c2 == 'x' || c2 == 'X') {
                base = 16;
                c = in_get(in);
            } else {
                base = 8;
                in_unget(in, c2);
            }
        } else {
            base = 10;
        }
    }
    for (;;) {
        i32 d = -1;
        if (c >= '0' && c <= '9')
            d = c - '0';
        else if (c >= 'a' && c <= 'f')
            d = c - 'a' + 10;
        else if (c >= 'A' && c <= 'F')
            d = c - 'A' + 10;
        if (d < 0 || d >= base)
            break;
        v = v * (u32)base + (u32)d;
        digits++;
        c = in_get(in);
    }
    in_unget(in, c);
    if (!digits)
        return 0;
    *out = v;
    return 1;
}

static i32 scan_in(struct in *in, const char *fmt, va_list ap)
{
    const char *p = fmt;
    i32 assigned = 0;

    while (*p) {
        if (is_space((u8)*p)) {
            skip_space(in);
            while (is_space((u8)*p))
                p++;
            continue;
        }
        if (*p != '%') {
            i32 c = in_get(in);
            if (c != (u8)*p)
                return assigned;
            p++;
            continue;
        }
        p++;
        if (*p == '%') {
            i32 c = in_get(in);
            if (c != '%')
                return assigned;
            p++;
            continue;
        }

        {
            i32 long_flag = 0;
            while (*p == 'l') {
                long_flag++;
                p++;
            }
            switch (*p) {
            case 'c': {
                char *out = va_arg(ap, char *);
                i32 c = in_get(in);
                *out = (char)c;
                assigned++;
                p++;
                break;
            }
            case 's': {
                char *out = va_arg(ap, char *);
                i32 c;
                usize n = 0;
                skip_space(in);
                for (;;) {
                    c = in_get(in);
                    if (is_space(c)) {
                        in_unget(in, c);
                        break;
                    }
                    out[n++] = (char)c;
                }
                out[n] = '\0';
                if (n == 0)
                    return assigned;
                assigned++;
                p++;
                break;
            }
            case 'd':
            case 'i': {
                unsigned long long v;
                bool neg;
                i32 base = (*p == 'i') ? 0 : 10;
                if (!scan_int(in, base, &v, &neg))
                    return assigned;
                if (long_flag >= 2) {
                    long long *out = va_arg(ap, long long *);
                    *out = neg ? -(long long)v : (long long)v;
                } else if (long_flag == 1) {
                    long *out = va_arg(ap, long *);
                    *out = neg ? -(long)v : (long)v;
                } else {
                    i32 *out = va_arg(ap, i32 *);
                    *out = neg ? -(i32)v : (i32)v;
                }
                assigned++;
                p++;
                break;
            }
            case 'u':
            case 'x':
            case 'X': {
                unsigned long long v;
                bool neg;
                i32 base = (*p == 'u') ? 10 : 16;
                if (!scan_int(in, base, &v, &neg))
                    return assigned;
                (void)neg;
                if (long_flag >= 2) {
                    unsigned long long *out = va_arg(ap, unsigned long long *);
                    *out = v;
                } else if (long_flag == 1) {
                    unsigned long *out = va_arg(ap, unsigned long *);
                    *out = (unsigned long)v;
                } else {
                    u32 *out = va_arg(ap, u32 *);
                    *out = (u32)v;
                }
                assigned++;
                p++;
                break;
            }
            default:
                return assigned;
            }
        }
    }
    return assigned;
}

i32 early_vscanf(const char *fmt, va_list ap)
{
    struct in in = { .get = early_getchar };
    return scan_in(&in, fmt, ap);
}

i32 vscanf(const char *fmt, va_list ap)
{
    struct in in = { .get = getchar };
    return scan_in(&in, fmt, ap);
}

i32 early_scanf(const char *fmt, ...)
{
    va_list ap;
    i32 n;
    va_start(ap, fmt);
    n = early_vscanf(fmt, ap);
    va_end(ap);
    return n;
}

i32 scanf(const char *fmt, ...)
{
    va_list ap;
    i32 n;
    va_start(ap, fmt);
    n = vscanf(fmt, ap);
    va_end(ap);
    return n;
}
