//generated by gpt-5<noreply@openai.com> @ codex
//将正式 stdio 接口映射到始终存在的 early stdio。

#include "early_stdio.h"
#include "stdio.h"

#if defined(SHYOS_STDIO_EARLY)

i32 putchar(i32 c)
{
	return early_putchar(c);
}

i32 getchar(void)
{
	return early_getchar();
}

i32 vprintf(const char *fmt, va_list ap)
{
	return early_vprintf(fmt, ap);
}

i32 printf(const char *fmt, ...)
{
	va_list ap;
	i32 result;

	va_start(ap, fmt);
	result = vprintf(fmt, ap);
	va_end(ap);
	return result;
}

i32 vscanf(const char *fmt, va_list ap)
{
	return early_vscanf(fmt, ap);
}

i32 scanf(const char *fmt, ...)
{
	va_list ap;
	i32 result;

	va_start(ap, fmt);
	result = vscanf(fmt, ap);
	va_end(ap);
	return result;
}

i32 vsnprintf(char *buf, usize n, const char *fmt, va_list ap)
{
	return early_vsnprintf(buf, n, fmt, ap);
}

i32 snprintf(char *buf, usize n, const char *fmt, ...)
{
	va_list ap;
	i32 result;

	va_start(ap, fmt);
	result = vsnprintf(buf, n, fmt, ap);
	va_end(ap);
	return result;
}

i32 sprintf(char *buf, const char *fmt, ...)
{
	va_list ap;
	i32 result;

	va_start(ap, fmt);
	result = vsnprintf(buf, (usize)-1 / 2, fmt, ap);
	va_end(ap);
	return result;
}

#endif /* SHYOS_STDIO_EARLY */
