//generated by gpt-5<noreply@openai.com> @ codex
#ifndef SHYOS_STACK_H
#define SHYOS_STACK_H

#include "deque.h"

typedef struct Stack Stack;
struct Stack {
	Deque data;
};

void stack_drop(void *self);
void *stack_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(Stack, stack_drop, stack_clone_obj)

ResultStack stack_new(TypeDesc elem);
ResultStack stack_clone(const Stack *source);

usize stack_len(const Stack *stack);
usize stack_capacity(const Stack *stack);
bool stack_is_empty(const Stack *stack);

i32 stack_reserve(Stack *stack, usize additional);
i32 stack_push(Stack *stack, void *value);
i32 stack_push_raw(Stack *stack, const void *value);
i32 stack_pop(Stack *stack, void *out);
const void *stack_peek(const Stack *stack);
void *stack_peek_mut(Stack *stack);
void stack_clear(Stack *stack);

#endif /* SHYOS_STACK_H */
