//generated by gpt-5<noreply@openai.com> @ codex
#include "stack.h"

#include "alloc.h"

ResultStack stack_new(TypeDesc elem)
{
	ResultDeque result = deque_new(elem);
	Stack stack;

	if (Deque_is_err(&result)) {
		return StackErr(Deque_error(&result));
	}
	stack.data = Deque_unwrap(&result);
	return StackOk(stack);
}

usize stack_len(const Stack *stack)
{
	return deque_len(&stack->data);
}

usize stack_capacity(const Stack *stack)
{
	return deque_capacity(&stack->data);
}

bool stack_is_empty(const Stack *stack)
{
	return deque_is_empty(&stack->data);
}

i32 stack_reserve(Stack *stack, usize additional)
{
	return deque_reserve(&stack->data, additional);
}

i32 stack_push(Stack *stack, void *value)
{
	return deque_push_back(&stack->data, value);
}

i32 stack_push_raw(Stack *stack, const void *value)
{
	return deque_push_back_raw(&stack->data, value);
}

i32 stack_pop(Stack *stack, void *out)
{
	return deque_pop_back(&stack->data, out);
}

const void *stack_peek(const Stack *stack)
{
	return deque_back(&stack->data);
}

void *stack_peek_mut(Stack *stack)
{
	return deque_back_mut(&stack->data);
}

void stack_clear(Stack *stack)
{
	deque_clear(&stack->data);
}

void stack_drop(void *self)
{
	Stack *stack = self;

	deque_drop(&stack->data);
	memset(stack, 0, sizeof(*stack));
}

void *stack_clone_obj(const void *source_ptr)
{
	const Stack *source = source_ptr;
	Stack *copy;
	ResultDeque data;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	data = deque_clone(&source->data);
	if (Deque_is_err(&data)) {
		free(copy);
		return NULL;
	}
	copy->data = Deque_unwrap(&data);
	return copy;
}

ResultStack stack_clone(const Stack *source)
{
	Stack *copy = stack_clone_obj(source);
	Stack value;

	if (copy == NULL) {
		return StackErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return StackOk(value);
}
