# generated by gpt-5.6-sol<noreply@openai.com> @ codex
# 这是一个模板
# ShyOS final-image configuration template.
#
# Copy this file to app/kernel/test/<image>/shyos.mk. Keep the macros you
# need and comment out the macros you do not need.
# Every active macro is passed unchanged to both language worlds:
#   C:    -DSHYOS_...
#   Rust: --cfg SHYOS_...

# ---- debug/release ----
# CONFIG=DEBUG
CONFIG=RELEASE

SHYOS_DEFINES :=

# ---- backend: keep exactly one block ----

# QEMU virt bare-metal backend
SHYOS_DEFINES += SHYOS_BACKEND_QEMU_VIRT
SHYOS_DEFINES += BOARD_QEMU_VIRT

# Native Linux user backend
# SHYOS_DEFINES += SHYOS_BACKEND_LINUX_USER

# ---- allocator ----
# SHYOS_ALLOCATOR_NONE: 无ALLOCATOR
# SHYOS_ALLOCATOR_SIMPLE: 无 VM 的库级堆。arena 参数在对应 board define 里：
#   QEMU virt : lib/board/qemu_virt/qemu.h  -> HEAP_START / HEAP_SIZE
#   Linux user: lib/board/linux_user/linux_user.h -> 仅 HEAP_SIZE（启动时 host 申请）
# SHYOS_DEFINES += SHYOS_ALLOCATOR_NONE
SHYOS_DEFINES += SHYOS_ALLOCATOR_SIMPLE

# Future providers can be added directly, for example:
# SHYOS_DEFINES += SHYOS_ALLOCATOR_VM

# ---- stdio ----
# early_stdio 始终存在；这里只选择无前缀正式 stdio 接口的 provider。
# SHYOS_STDIO_EARLY: 将正式 stdio 映射到 early_stdio。
SHYOS_DEFINES += SHYOS_STDIO_EARLY

# Future providers can be added directly, for example:
# SHYOS_DEFINES += SHYOS_STDIO_INTERRUPT

# ---- scheduler ----

# No scheduler is provided by the selected ShyOS layers.1
SHYOS_DEFINES += SHYOS_SCHEDULER_NONE

# Future providers can be added directly, for example:
# SHYOS_DEFINES += SHYOS_SCHEDULER_RR

# ---- image layer ----

IMAGE_LAYER := 04data_structure
