//generated by grok-4.5<noreply@x.ai> @ cursor
//C ABI 兼容：RawSpinlock ↔ struct spinlock；CSpinlock<T> ↔ SpinlockT

#![no_std]

use core::cell::UnsafeCell;
use core::marker::PhantomData;
use core::ops::{Deref, DerefMut};

unsafe extern "C" {
    #[link_name = "spinlock_init"]
    fn c_spinlock_init(lock: *mut core::ffi::c_void);
    #[link_name = "spinlock_lock"]
    fn c_spinlock_lock(lock: *mut core::ffi::c_void);
    #[link_name = "spinlock_unlock"]
    fn c_spinlock_unlock(lock: *mut core::ffi::c_void);
}

/// 对应 C 的 `struct spinlock`。
#[repr(C)]
pub struct RawSpinlock {
    locked: i32,
    mask: u32,
}

/// 对应 C 的 `SpinlockT`（首字段 raw lock，其后为 `T`）。
///
/// 布局契约与 `result` 的 `ResultT` / `CResult<T>` 相同：C 用宏生成
/// `SpinlockT`，Rust 用本泛型；指针可按 `repr(C)` 互转。
#[repr(C)]
pub struct CSpinlock<T> {
    lock: RawSpinlock,
    value: UnsafeCell<T>,
}

/// `lock()` 返回的守卫，drop 时自动 unlock，并 `DerefMut` 到 `T`。
///
/// `*const ()` 使 guard `!Send`：unlock 必须在加锁的同一个 CPU 上发生。
pub struct CSpinlockGuard<'a, T> {
    lock: &'a CSpinlock<T>,
    _not_send: PhantomData<*const ()>,
}

unsafe impl Sync for RawSpinlock {}
unsafe impl<T: Send> Sync for CSpinlock<T> {}

impl RawSpinlock {
    pub const fn new() -> Self {
        Self { locked: 0, mask: 0 }
    }

    pub fn init(&mut self) {
        unsafe { c_spinlock_init((self as *mut Self).cast()) }
    }

    pub fn lock(&self) {
        /*在这里，返回的guard是&mut 所以是可变的！*/
        unsafe { c_spinlock_lock((self as *const Self as *mut Self).cast()) }
    }

    pub fn unlock(&self) {
        unsafe { c_spinlock_unlock((self as *const Self as *mut Self).cast()) }
    }
}

impl Default for RawSpinlock {
    fn default() -> Self {
        Self::new()
    }
}

impl<T> CSpinlock<T> {
    pub const fn new(value: T) -> Self {
        Self {
            lock: RawSpinlock::new(),
            value: UnsafeCell::new(value),
        }
    }

    pub fn init(&mut self) {
        self.lock.init();
    }

    pub fn lock(&self) -> CSpinlockGuard<'_, T> {
        self.lock.lock();
        CSpinlockGuard {
            lock: self,
            _not_send: PhantomData,
        }
    }

    /// 手工配对的 unlock；多数情况应使用 `lock()` 返回的 guard。
    pub fn unlock(&self) {
        self.lock.unlock();
    }

    /// 对应 C 的 `T_spinlock_get`；仅在已持锁时安全。
    pub fn get(&self) -> *mut T {
        self.value.get()
    }
}

impl<T> Deref for CSpinlockGuard<'_, T> {
    type Target = T;

    fn deref(&self) -> &T {
        unsafe { &*self.lock.value.get() }
    }
}

impl<T> DerefMut for CSpinlockGuard<'_, T> {
    fn deref_mut(&mut self) -> &mut T {
        unsafe { &mut *self.lock.value.get() }
    }
}

impl<T> Drop for CSpinlockGuard<'_, T> {
    fn drop(&mut self) {
        self.lock.unlock();
    }
}
