/* generated by gpt-5<noreply@openai.com> @ codex
 * 00arch xorshift random interface.
 */
#ifndef SHYOS_RAND_H
#define SHYOS_RAND_H

#include "shy_type.h"

void rand_seed(u64 seed);
u64 rand_u64(void);
i32 randint(i32 min, i32 max);

#endif /* SHYOS_RAND_H */
