/* generated by gpt-5<noreply@openai.com> @ codex
 * xorshift64 implementation shared by C and Rust.
 */

#include "board.h"
#include "rand.h"

#define DEFAULT_SEED 0x9e3779b97f4a7c15UL

static u64 state;

void rand_seed(u64 seed)
{
	state = seed == 0 ? DEFAULT_SEED : seed;
}

u64 rand_u64(void)
{
	u64 next;

	if (state == 0)
		rand_seed(randseed());

	next = state;
	next ^= next << 13;
	next ^= next >> 7;
	next ^= next << 17;
	state = next;
	return next;
}

i32 randint(i32 min, i32 max)
{
	u64 width = (u64)((i64)max - (i64)min + 1);

	if (width == 0)
		return min;
	return (i32)((i64)min + (i64)(rand_u64() % width));
}
