//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//外置存储环形缓冲区实现：head+len 计数，最旧元素下标 (head + cap - len) % cap

#include "ringbuffer_noalloc.h"
#include "string_noalloc.h"

void rb_noalloc_init(RbNoAlloc *rb, void *buf, usize buf_size, usize elem_size)
{
	rb->buf = (u8 *)buf;
	rb->elem_size = elem_size;
	rb->cap = elem_size == 0 ? 0 : buf_size / elem_size;
	rb->head = 0;
	rb->len = 0;
}

static usize rb_noalloc_oldest(const RbNoAlloc *rb)
{
	return (rb->head + rb->cap - rb->len) % rb->cap;
}

void rb_noalloc_push(RbNoAlloc *rb, const void *elem)
{
	u8 *slot;

	if (rb->cap == 0)
		return;
	slot = rb->buf + rb->head * rb->elem_size;
	memcpy(slot, elem, rb->elem_size);
	rb->head = (rb->head + 1) % rb->cap;
	if (rb->len < rb->cap)
		rb->len++;
}

bool rb_noalloc_pop(RbNoAlloc *rb, void *out)
{
	const u8 *slot;

	if (rb->len == 0)
		return false;
	slot = rb->buf + rb_noalloc_oldest(rb) * rb->elem_size;
	memcpy(out, slot, rb->elem_size);
	rb->len--;
	return true;
}

const void *rb_noalloc_front(const RbNoAlloc *rb)
{
	if (rb->len == 0)
		return NULL;
	return rb->buf + rb_noalloc_oldest(rb) * rb->elem_size;
}

const void *rb_noalloc_back(const RbNoAlloc *rb)
{
	if (rb->len == 0)
		return NULL;
	return rb->buf + (rb->head + rb->cap - 1) % rb->cap * rb->elem_size;
}

usize rb_noalloc_len(const RbNoAlloc *rb)
{
	return rb->len;
}

usize rb_noalloc_capacity(const RbNoAlloc *rb)
{
	return rb->cap;
}

bool rb_noalloc_is_empty(const RbNoAlloc *rb)
{
	return rb->len == 0;
}

bool rb_noalloc_is_full(const RbNoAlloc *rb)
{
	return rb->len == rb->cap;
}

void rb_noalloc_clear(RbNoAlloc *rb)
{
	rb->head = 0;
	rb->len = 0;
}
