//generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
//panic_handler 辅助：供最终 image crate 的 #[panic_handler] 调用
//层级 crate 不定义全局 panic_handler，只提供可复用的处理逻辑
//C 声明在 stdio.h：void panic(const char *fmt, ...)
//panic 路径走 early console / raw UART，不依赖未来更高层 print

#![no_std]

use core::ffi::c_char;
use core::fmt::Write;
use core::panic::PanicInfo;

use print::EarlyConsole;
use shutdown::shutdown;

unsafe extern "C" {
    #[link_name = "panic"]
    fn c_panic(fmt: *const c_char, ...) -> !;
}

/// 调用 C 侧 `panic("%s", msg)`。
#[inline]
pub fn panic_cstr(msg: &core::ffi::CStr) -> ! {
    unsafe { c_panic(c"%s".as_ptr(), msg.as_ptr()) }
}

/// 无格式串 panic。
#[inline]
pub fn panic_unknown() -> ! {
    unsafe { c_panic(core::ptr::null()) }
}

/// 最终 image 的 `#[panic_handler]` 应调用本函数。
/// 打印 location / message 后以 -1 关机。
pub fn handle_panic(info: &PanicInfo) -> ! {
    let mut console = EarlyConsole;
    let _ = writeln!(console, "panic: {info}");
    shutdown(-1)
}

/// 兼容命名。
#[inline]
pub fn panic_handler(info: &PanicInfo) -> ! {
    handle_panic(info)
}
