//generated by gpt-5.6-luna<noreply@openai.com> @ codex
//panic and assert C interface

#ifndef SHYOS_PANIC_H
#define SHYOS_PANIC_H

#include <stdarg.h>

#ifdef __cplusplus
extern "C" {
#endif

void panic(const char *fmt, ...) __attribute__((noreturn, format(printf, 1, 2)));
void vpanic(const char *fmt, va_list ap) __attribute__((noreturn));

#ifdef __cplusplus
}
#endif

#define __SHYOS_ASSERT_STR2(x) #x
#define __SHYOS_ASSERT_STR(x) __SHYOS_ASSERT_STR2(x)

#ifndef assert
#define assert(cond)                                                           \
	do {                                                                   \
		if (!(cond))                                                   \
			panic("assert failed: %s @ %s:%s", #cond, __FILE__,    \
			      __SHYOS_ASSERT_STR(__LINE__));                   \
	} while (0)
#endif

#endif /* SHYOS_PANIC_H */
