/* generated by deepseek-v4-pro<noreply@deepseek.com> @ pi
 * panic：可变参数格式化后 shutdown(-1)
 * 输出固定走 early_*（可在无中断路径使用）
 */

#include "panic.h"
#include "early_stdio.h"
#include "shutdown.h"

void vpanic(const char *fmt, va_list ap)
{
	early_printf("panic: ");
	if (fmt)
		early_vprintf(fmt, ap);
	early_printf("\n");
	shutdown(-1);
}

void panic(const char *fmt, ...)
{
	va_list ap;

	va_start(ap, fmt);
	vpanic(fmt, ap);
}
