//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//freelist pmm provider：4K 页 freelist，next 指针直接放在空闲页开头

#include "pmm.h"

#if defined(SHYOS_PMM_FREELIST)

#include "board.h"

#define PAGE_SIZE 4096UL
  #define PAGE_NEXT(ptr) (*(void **)(ptr))
static void *free_list;

//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//把 [PMM_START, PMM_START+PMM_SIZE) 按 4K 对齐切页，串成 freelist
void page_memory_init(void)
{
	usize addr = ((usize)PMM_START + PAGE_SIZE - 1u) & ~(usize)(PAGE_SIZE - 1u);
	usize end = (usize)PMM_START + (usize)PMM_SIZE;

	free_list = NULL;
	while (addr + PAGE_SIZE <= end) {
		free_page((void *)addr);
		addr += PAGE_SIZE;
	}
}

//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//取走 freelist 首页；空则返回 NULL
void *malloc_page(void)
{
	void *page = free_list;

	if (page == NULL) {
		return NULL;
	}
	free_list = PAGE_NEXT(page);
	return page;
}

//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//单页归还：页内写入旧表头后成为新表头
void free_page(void *ptr)
{
	if (ptr == NULL) {
		return;
	}
	void* p;
	if (free_list == NULL){
		p=NULL;
	}
	else{
		p=free_list;
	}
	free_list=ptr;
	PAGE_NEXT(ptr)=p;
}

#endif /* SHYOS_PMM_FREELIST */
