//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//C 实现的 freelist pmm 最小包装

#![no_std]

#[cfg(SHYOS_PMM_FREELIST)]
pub use shyos_pmm::{free_page, malloc_page};

/// RAII 包装：drop 时 free_page。
#[cfg(SHYOS_PMM_FREELIST)]
pub struct PageBox {
    ptr: *mut u8,
}

#[cfg(SHYOS_PMM_FREELIST)]
impl PageBox {
    pub fn alloc() -> Option<Self> {
        let ptr = malloc_page();
        if ptr.is_null() {
            None
        } else {
            Some(Self { ptr })
        }
    }

    pub fn as_ptr(&self) -> *const u8 {
        self.ptr
    }

    pub fn as_mut_ptr(&mut self) -> *mut u8 {
        self.ptr
    }
}

#[cfg(SHYOS_PMM_FREELIST)]
impl Drop for PageBox {
    fn drop(&mut self) {
        unsafe { free_page(self.ptr) };
    }
}
