//generated by gpt-5<noreply@openai.com> @ codex
//C-only 02core image 的 Rust 闭包与 panic handler。

#![no_std]

pub use shyos_core::*;

#[panic_handler]
fn panic(info: &::core::panic::PanicInfo) -> ! {
    shyos_core::panic::handle_panic(info)
}
