//generated by gpt-5<noreply@openai.com> @ codex
#![no_std]

use core::ffi::c_void;
use core::marker::PhantomData;
use core::mem::{align_of, size_of, ManuallyDrop, MaybeUninit};
use core::ops::{Index, IndexMut};
use core::ptr;
use shyos_obj::TypeDesc;
use shyos_rawbuf::RawBuf;
use shyos_result::{CResult, ERROR_INVALID_ARGUMENT, ERROR_NO_VALUE, ERROR_OUT_OF_MEMORY};

pub const LINKED_LIST_NONE: usize = usize::MAX;

#[repr(C)]
pub struct RawLinkedList {
    pub nodes: RawBuf,
    pub elem: TypeDesc,
    pub first: usize,
    pub last: usize,
    pub free: usize,
    pub len: usize,
}

unsafe extern "C" {
    #[link_name = "linked_list_new"]
    fn c_linked_list_new(elem: TypeDesc) -> CResult<RawLinkedList>;
    #[link_name = "linked_list_reserve"]
    fn c_linked_list_reserve(list: *mut RawLinkedList, additional: usize) -> i32;
    #[link_name = "linked_list_push_front_raw"]
    fn c_linked_list_push_front_raw(
        list: *mut RawLinkedList,
        value: *const c_void,
        out_index: *mut usize,
    ) -> i32;
    #[link_name = "linked_list_push_back_raw"]
    fn c_linked_list_push_back_raw(
        list: *mut RawLinkedList,
        value: *const c_void,
        out_index: *mut usize,
    ) -> i32;
    #[link_name = "linked_list_pop_front"]
    fn c_linked_list_pop_front(list: *mut RawLinkedList, out: *mut c_void) -> i32;
    #[link_name = "linked_list_pop_back"]
    fn c_linked_list_pop_back(list: *mut RawLinkedList, out: *mut c_void) -> i32;
    #[link_name = "linked_list_remove"]
    fn c_linked_list_remove(list: *mut RawLinkedList, index: usize, out: *mut c_void) -> i32;
    #[link_name = "linked_list_get"]
    fn c_linked_list_get(list: *const RawLinkedList, index: usize) -> *const c_void;
    #[link_name = "linked_list_get_mut"]
    fn c_linked_list_get_mut(list: *mut RawLinkedList, index: usize) -> *mut c_void;
    #[link_name = "linked_list_next_index"]
    fn c_linked_list_next_index(list: *const RawLinkedList, index: usize) -> usize;
    #[link_name = "linked_list_prev_index"]
    fn c_linked_list_prev_index(list: *const RawLinkedList, index: usize) -> usize;
    #[link_name = "linked_list_clear"]
    fn c_linked_list_clear(list: *mut RawLinkedList);
    #[link_name = "linked_list_drop"]
    fn c_linked_list_drop(list: *mut RawLinkedList);
}

unsafe extern "C" fn drop_element<T>(value: *mut c_void) {
    unsafe { ptr::drop_in_place(value.cast::<T>()) }
}

fn type_desc<T>() -> TypeDesc {
    TypeDesc {
        size: size_of::<T>(),
        drop: Some(drop_element::<T>),
        clone: None,
    }
}

#[repr(transparent)]
pub struct CLinkedList<T> {
    pub raw: RawLinkedList,
    marker: PhantomData<T>,
}

pub struct Iter<'a, T> {
    list: &'a CLinkedList<T>,
    next: usize,
}

unsafe impl<T: Send> Send for CLinkedList<T> {}
unsafe impl<T: Sync> Sync for CLinkedList<T> {}

impl<T> CLinkedList<T> {
    pub fn new() -> CResult<Self> {
        if size_of::<T>() == 0 || align_of::<T>() > align_of::<usize>() {
            return CResult::err(ERROR_INVALID_ARGUMENT);
        }
        match unsafe { c_linked_list_new(type_desc::<T>()) } {
            CResult::Ok(raw) => CResult::ok(Self {
                raw,
                marker: PhantomData,
            }),
            CResult::Err(error) => CResult::err(error),
        }
    }

    pub fn with_capacity(capacity: usize) -> CResult<Self> {
        let mut list = match Self::new() {
            CResult::Ok(list) => list,
            CResult::Err(error) => return CResult::err(error),
        };
        if let CResult::Err(error) = list.reserve(capacity) {
            return CResult::err(error);
        }
        CResult::ok(list)
    }

    pub fn len(&self) -> usize {
        self.raw.len
    }

    pub fn capacity(&self) -> usize {
        self.raw.nodes.cap
    }

    pub fn is_empty(&self) -> bool {
        self.raw.len == 0
    }

    pub fn reserve(&mut self, additional: usize) -> CResult<()> {
        if unsafe { c_linked_list_reserve(&mut self.raw, additional) } == 0 {
            CResult::ok(())
        } else {
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn push_front(&mut self, value: T) -> CResult<usize> {
        self.push(value, true)
    }

    pub fn push_back(&mut self, value: T) -> CResult<usize> {
        self.push(value, false)
    }

    fn push(&mut self, value: T, front: bool) -> CResult<usize> {
        let value = ManuallyDrop::new(value);
        let mut index = LINKED_LIST_NONE;
        let status = unsafe {
            if front {
                c_linked_list_push_front_raw(
                    &mut self.raw,
                    (&*value as *const T).cast(),
                    &mut index,
                )
            } else {
                c_linked_list_push_back_raw(&mut self.raw, (&*value as *const T).cast(), &mut index)
            }
        };
        if status == 0 {
            CResult::ok(index)
        } else {
            drop(ManuallyDrop::into_inner(value));
            CResult::err(ERROR_OUT_OF_MEMORY)
        }
    }

    pub fn pop_front(&mut self) -> CResult<T> {
        self.pop(true)
    }

    pub fn pop_back(&mut self) -> CResult<T> {
        self.pop(false)
    }

    fn pop(&mut self, front: bool) -> CResult<T> {
        let mut value = MaybeUninit::<T>::uninit();
        let status = unsafe {
            if front {
                c_linked_list_pop_front(&mut self.raw, value.as_mut_ptr().cast())
            } else {
                c_linked_list_pop_back(&mut self.raw, value.as_mut_ptr().cast())
            }
        };
        if status == 0 {
            CResult::ok(unsafe { value.assume_init() })
        } else {
            CResult::err(ERROR_NO_VALUE)
        }
    }

    pub fn remove(&mut self, index: usize) -> CResult<T> {
        let mut value = MaybeUninit::<T>::uninit();
        if unsafe { c_linked_list_remove(&mut self.raw, index, value.as_mut_ptr().cast()) } == 0 {
            CResult::ok(unsafe { value.assume_init() })
        } else {
            CResult::err(ERROR_NO_VALUE)
        }
    }

    pub fn get(&self, index: usize) -> Option<&T> {
        unsafe { c_linked_list_get(&self.raw, index).cast::<T>().as_ref() }
    }

    pub fn get_mut(&mut self, index: usize) -> Option<&mut T> {
        unsafe {
            c_linked_list_get_mut(&mut self.raw, index)
                .cast::<T>()
                .as_mut()
        }
    }

    pub fn first_index(&self) -> Option<usize> {
        (self.raw.first != LINKED_LIST_NONE).then_some(self.raw.first)
    }

    pub fn last_index(&self) -> Option<usize> {
        (self.raw.last != LINKED_LIST_NONE).then_some(self.raw.last)
    }

    pub fn prev_index(&self, index: usize) -> Option<usize> {
        let previous = unsafe { c_linked_list_prev_index(&self.raw, index) };
        (previous != LINKED_LIST_NONE).then_some(previous)
    }

    pub fn next_index(&self, index: usize) -> Option<usize> {
        let next = unsafe { c_linked_list_next_index(&self.raw, index) };
        (next != LINKED_LIST_NONE).then_some(next)
    }

    pub fn front(&self) -> Option<&T> {
        self.first_index().and_then(|index| self.get(index))
    }

    pub fn front_mut(&mut self) -> Option<&mut T> {
        let index = self.first_index()?;
        self.get_mut(index)
    }

    pub fn back(&self) -> Option<&T> {
        self.last_index().and_then(|index| self.get(index))
    }

    pub fn back_mut(&mut self) -> Option<&mut T> {
        let index = self.last_index()?;
        self.get_mut(index)
    }

    pub fn iter(&self) -> Iter<'_, T> {
        Iter {
            list: self,
            next: self.raw.first,
        }
    }

    pub fn clear(&mut self) {
        unsafe { c_linked_list_clear(&mut self.raw) }
    }
}

impl<'a, T> Iterator for Iter<'a, T> {
    type Item = (usize, &'a T);

    fn next(&mut self) -> Option<Self::Item> {
        if self.next == LINKED_LIST_NONE {
            return None;
        }
        let index = self.next;
        let value = self.list.get(index)?;
        self.next = self.list.next_index(index).unwrap_or(LINKED_LIST_NONE);
        Some((index, value))
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        (0, Some(self.list.len()))
    }
}

impl<T: Clone> Clone for CLinkedList<T> {
    fn clone(&self) -> Self {
        let mut clone = Self::with_capacity(self.len()).unwrap();
        for (_, value) in self.iter() {
            clone.push_back(value.clone()).unwrap();
        }
        clone
    }
}

impl<T> Index<usize> for CLinkedList<T> {
    type Output = T;

    fn index(&self, index: usize) -> &Self::Output {
        self.get(index).expect("linked list node is not active")
    }
}

impl<T> IndexMut<usize> for CLinkedList<T> {
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        self.get_mut(index).expect("linked list node is not active")
    }
}

impl<T> Drop for CLinkedList<T> {
    fn drop(&mut self) {
        unsafe { c_linked_list_drop(&mut self.raw) }
    }
}
