//generated by gpt-5<noreply@openai.com> @ codex
#include "linked_list.h"

#include "alloc.h"

static LinkedListNode *linked_list_node(
	const LinkedList *list,
	usize index
)
{
	return raw_buf_get(&list->nodes, index);
}

static void *linked_list_value(const LinkedList *list, usize index)
{
	return (char *)linked_list_node(list, index) +
		sizeof(LinkedListNode);
}

static bool linked_list_is_active(const LinkedList *list, usize index)
{
	return index < list->nodes.cap &&
		linked_list_node(list, index)->prev != index;
}

ResultLinkedList linked_list_new(TypeDesc elem)
{
	ResultRawBuf result;
	LinkedList list;

	if (elem.size == 0 ||
	    elem.size > (usize)-1 - sizeof(LinkedListNode)) {
		return LinkedListErr(ERROR_INVALID_ARGUMENT);
	}
	result = raw_buf_new(sizeof(LinkedListNode) + elem.size);
	if (RawBuf_is_err(&result)) {
		return LinkedListErr(RawBuf_error(&result));
	}
	list = (LinkedList){
		.nodes = RawBuf_unwrap(&result),
		.elem = elem,
		.first = LINKED_LIST_NONE,
		.last = LINKED_LIST_NONE,
		.free = LINKED_LIST_NONE,
		.len = 0,
	};
	return LinkedListOk(list);
}

ResultLinkedList linked_list_new_with_capacity(
	usize capacity,
	TypeDesc elem
)
{
	ResultLinkedList result = linked_list_new(elem);
	LinkedList list;

	if (LinkedList_is_err(&result)) {
		return result;
	}
	list = LinkedList_unwrap(&result);
	if (linked_list_reserve(&list, capacity) != 0) {
		linked_list_drop(&list);
		return LinkedListErr(ERROR_OUT_OF_MEMORY);
	}
	return LinkedListOk(list);
}

usize linked_list_len(const LinkedList *list)
{
	return list->len;
}

usize linked_list_capacity(const LinkedList *list)
{
	return list->nodes.cap;
}

bool linked_list_is_empty(const LinkedList *list)
{
	return list->len == 0;
}

i32 linked_list_reserve(LinkedList *list, usize additional)
{
	usize old_capacity = list->nodes.cap;
	usize required;
	usize index;

	if (additional > (usize)-1 - list->len) {
		return -1;
	}
	required = list->len + additional;
	if (required <= old_capacity) {
		return 0;
	}
	if (raw_buf_reserve(&list->nodes, required) != 0) {
		return -1;
	}
	for (index = list->nodes.cap; index > old_capacity; --index) {
		LinkedListNode *node = linked_list_node(list, index - 1);

		node->prev = index - 1;
		node->next = list->free;
		list->free = index - 1;
	}
	return 0;
}

static i32 linked_list_allocate(LinkedList *list, usize *out_index)
{
	LinkedListNode *node;
	usize index;

	if (list->free == LINKED_LIST_NONE &&
	    linked_list_reserve(list, 1) != 0) {
		return -1;
	}
	index = list->free;
	node = linked_list_node(list, index);
	list->free = node->next;
	*out_index = index;
	return 0;
}

static i32 linked_list_push_impl(
	LinkedList *list,
	const void *value,
	bool front,
	bool clear_source,
	usize *out_index
)
{
	LinkedListNode *node;
	usize index;

	if (value == NULL || linked_list_allocate(list, &index) != 0) {
		return -1;
	}
	node = linked_list_node(list, index);
	if (front) {
		node->prev = LINKED_LIST_NONE;
		node->next = list->first;
		if (list->first == LINKED_LIST_NONE) {
			list->last = index;
		} else {
			linked_list_node(list, list->first)->prev = index;
		}
		list->first = index;
	} else {
		node->prev = list->last;
		node->next = LINKED_LIST_NONE;
		if (list->last == LINKED_LIST_NONE) {
			list->first = index;
		} else {
			linked_list_node(list, list->last)->next = index;
		}
		list->last = index;
	}
	if (clear_source) {
		obj_move(list->elem, linked_list_value(list, index),
			 (void *)value);
	} else {
		memcpy(linked_list_value(list, index), value, list->elem.size);
	}
	list->len++;
	if (out_index != NULL) {
		*out_index = index;
	}
	return 0;
}

i32 linked_list_push_front(
	LinkedList *list,
	void *value,
	usize *out_index
)
{
	return linked_list_push_impl(list, value, true, true, out_index);
}

i32 linked_list_push_back(
	LinkedList *list,
	void *value,
	usize *out_index
)
{
	return linked_list_push_impl(list, value, false, true, out_index);
}

i32 linked_list_push_front_raw(
	LinkedList *list,
	const void *value,
	usize *out_index
)
{
	return linked_list_push_impl(list, value, true, false, out_index);
}

i32 linked_list_push_back_raw(
	LinkedList *list,
	const void *value,
	usize *out_index
)
{
	return linked_list_push_impl(list, value, false, false, out_index);
}

i32 linked_list_remove(LinkedList *list, usize index, void *out)
{
	LinkedListNode *node;

	if (!linked_list_is_active(list, index)) {
		return ERROR_NO_VALUE;
	}
	node = linked_list_node(list, index);
	if (node->prev == LINKED_LIST_NONE) {
		list->first = node->next;
	} else {
		linked_list_node(list, node->prev)->next = node->next;
	}
	if (node->next == LINKED_LIST_NONE) {
		list->last = node->prev;
	} else {
		linked_list_node(list, node->next)->prev = node->prev;
	}
	if (out == NULL) {
		obj_drop(list->elem, linked_list_value(list, index));
	} else {
		obj_move(list->elem, out, linked_list_value(list, index));
	}
	node->prev = index;
	node->next = list->free;
	list->free = index;
	list->len--;
	return 0;
}

i32 linked_list_pop_front(LinkedList *list, void *out)
{
	if (list->first == LINKED_LIST_NONE) {
		return ERROR_EMPTY;
	}
	return linked_list_remove(list, list->first, out);
}

i32 linked_list_pop_back(LinkedList *list, void *out)
{
	if (list->last == LINKED_LIST_NONE) {
		return ERROR_EMPTY;
	}
	return linked_list_remove(list, list->last, out);
}

const void *linked_list_get(const LinkedList *list, usize index)
{
	if (!linked_list_is_active(list, index)) {
		return NULL;
	}
	return linked_list_value(list, index);
}

void *linked_list_get_mut(LinkedList *list, usize index)
{
	return (void *)linked_list_get(list, index);
}

usize linked_list_first_index(const LinkedList *list)
{
	return list->first;
}

usize linked_list_last_index(const LinkedList *list)
{
	return list->last;
}

usize linked_list_prev_index(const LinkedList *list, usize index)
{
	if (!linked_list_is_active(list, index)) {
		return LINKED_LIST_NONE;
	}
	return linked_list_node(list, index)->prev;
}

usize linked_list_next_index(const LinkedList *list, usize index)
{
	if (!linked_list_is_active(list, index)) {
		return LINKED_LIST_NONE;
	}
	return linked_list_node(list, index)->next;
}

const void *linked_list_front(const LinkedList *list)
{
	return linked_list_get(list, list->first);
}

void *linked_list_front_mut(LinkedList *list)
{
	return linked_list_get_mut(list, list->first);
}

const void *linked_list_back(const LinkedList *list)
{
	return linked_list_get(list, list->last);
}

void *linked_list_back_mut(LinkedList *list)
{
	return linked_list_get_mut(list, list->last);
}

void linked_list_clear(LinkedList *list)
{
	while (list->first != LINKED_LIST_NONE) {
		(void)linked_list_remove(list, list->first, NULL);
	}
}

void linked_list_drop(void *self)
{
	LinkedList *list = self;

	linked_list_clear(list);
	raw_buf_drop(&list->nodes);
	memset(list, 0, sizeof(*list));
}

void *linked_list_clone_obj(const void *source_ptr)
{
	const LinkedList *source = source_ptr;
	LinkedList *copy;
	ResultLinkedList result;
	usize index;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	result = linked_list_new_with_capacity(source->len, source->elem);
	if (LinkedList_is_err(&result)) {
		free(copy);
		return NULL;
	}
	*copy = LinkedList_unwrap(&result);
	for (index = source->first;
	     index != LINKED_LIST_NONE;
	     index = linked_list_next_index(source, index)) {
		const void *value = linked_list_get(source, index);

		if (is_copy(source->elem)) {
			if (linked_list_push_back_raw(copy, value, NULL) != 0) {
				linked_list_drop(copy);
				free(copy);
				return NULL;
			}
		} else {
			void *cloned = obj_clone(source->elem, value);

			if (cloned == NULL ||
			    linked_list_push_back(copy, cloned, NULL) != 0) {
				if (cloned != NULL) {
					obj_drop(source->elem, cloned);
					free(cloned);
				}
				linked_list_drop(copy);
				free(copy);
				return NULL;
			}
			free(cloned);
		}
	}
	return copy;
}

ResultLinkedList linked_list_clone(const LinkedList *source)
{
	LinkedList *copy = linked_list_clone_obj(source);
	LinkedList value;

	if (copy == NULL) {
		return LinkedListErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return LinkedListOk(value);
}
