//generated by gpt-5<noreply@openai.com> @ codex
#ifndef SHYOS_LINKED_LIST_H
#define SHYOS_LINKED_LIST_H

#include "obj.h"
#include "rawbuf.h"
#include "result.h"

#define LINKED_LIST_NONE ((usize)-1)

typedef struct LinkedListNode LinkedListNode;
struct LinkedListNode {
	usize prev;
	usize next;
};

typedef struct LinkedList LinkedList;
struct LinkedList {
	RawBuf nodes;
	TypeDesc elem;
	usize first;
	usize last;
	usize free;
	usize len;
};

void linked_list_drop(void *self);
void *linked_list_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(LinkedList, linked_list_drop, linked_list_clone_obj)

ResultLinkedList linked_list_new(TypeDesc elem);
ResultLinkedList linked_list_new_with_capacity(usize capacity, TypeDesc elem);
ResultLinkedList linked_list_clone(const LinkedList *source);

usize linked_list_len(const LinkedList *list);
usize linked_list_capacity(const LinkedList *list);
bool linked_list_is_empty(const LinkedList *list);
i32 linked_list_reserve(LinkedList *list, usize additional);

i32 linked_list_push_front(
	LinkedList *list,
	void *value,
	usize *out_index
);
i32 linked_list_push_back(
	LinkedList *list,
	void *value,
	usize *out_index
);
i32 linked_list_push_front_raw(
	LinkedList *list,
	const void *value,
	usize *out_index
);
i32 linked_list_push_back_raw(
	LinkedList *list,
	const void *value,
	usize *out_index
);
i32 linked_list_pop_front(LinkedList *list, void *out);
i32 linked_list_pop_back(LinkedList *list, void *out);
i32 linked_list_remove(LinkedList *list, usize index, void *out);

const void *linked_list_get(const LinkedList *list, usize index);
void *linked_list_get_mut(LinkedList *list, usize index);
usize linked_list_first_index(const LinkedList *list);
usize linked_list_last_index(const LinkedList *list);
usize linked_list_prev_index(const LinkedList *list, usize index);
usize linked_list_next_index(const LinkedList *list, usize index);
const void *linked_list_front(const LinkedList *list);
void *linked_list_front_mut(LinkedList *list);
const void *linked_list_back(const LinkedList *list);
void *linked_list_back_mut(LinkedList *list);

void linked_list_clear(LinkedList *list);

#endif /* SHYOS_LINKED_LIST_H */
