//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//C IRQ backend 的 no_std Rust FFI 与最小安全包装。

#![no_std]

use core::marker::PhantomData;

pub type IrqMask = u32;
pub type IrqId = u32;

pub const IRQ_MASK_SOFTWARE: IrqMask = 1 << 0;
pub const IRQ_MASK_TIMER: IrqMask = 1 << 1;
pub const IRQ_MASK_EXTERNAL: IrqMask = 1 << 2;
pub const IRQ_MASK_ALL: IrqMask = IRQ_MASK_SOFTWARE | IRQ_MASK_TIMER | IRQ_MASK_EXTERNAL;

pub const IRQ_KIND_SOFTWARE: u32 = 1;
pub const IRQ_KIND_TIMER: u32 = 2;
pub const IRQ_KIND_EXTERNAL: u32 = 3;

pub const IRQ_ID_KIND_SHIFT: u32 = 28;
pub const IRQ_ID_KIND_MASK: IrqId = 0xf000_0000;
pub const IRQ_ID_SOURCE_MASK: IrqId = 0x0fff_ffff;

pub const IRQ_ID_SOFTWARE: IrqId = irq_id_make(IRQ_KIND_SOFTWARE, 0);
pub const IRQ_ID_TIMER: IrqId = irq_id_make(IRQ_KIND_TIMER, 0);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IrqError {
    Invalid,
    Unsupported,
    UnexpectedStatus(i32),
}

unsafe extern "C" {
    #[link_name = "set_trap_entry"]
    fn c_set_trap_entry(entry: usize) -> i32;
    #[link_name = "set_irq"]
    fn c_set_irq(mask: IrqMask) -> IrqMask;
    #[link_name = "enable_irq"]
    fn c_enable_irq(mask: IrqMask) -> IrqMask;
    #[link_name = "disable_irq"]
    fn c_disable_irq(mask: IrqMask) -> IrqMask;
    #[link_name = "get_irq"]
    fn c_get_irq() -> IrqMask;
    #[link_name = "global_irq"]
    fn c_global_irq(enabled: bool) -> bool;
    #[link_name = "enable_irq_source"]
    fn c_enable_irq_source(irq: IrqId) -> i32;
    #[link_name = "disable_irq_source"]
    fn c_disable_irq_source(irq: IrqId) -> i32;
    #[link_name = "claim_external_irq"]
    fn c_claim_external_irq(irq: *mut IrqId) -> i32;
    #[link_name = "complete_external_irq"]
    fn c_complete_external_irq(irq: IrqId) -> i32;
}

#[inline]
pub const fn irq_id_make(kind: u32, source: u32) -> IrqId {
    ((kind << IRQ_ID_KIND_SHIFT) & IRQ_ID_KIND_MASK) | (source & IRQ_ID_SOURCE_MASK)
}

#[inline]
pub const fn irq_id_kind(irq: IrqId) -> u32 {
    (irq & IRQ_ID_KIND_MASK) >> IRQ_ID_KIND_SHIFT
}

#[inline]
pub const fn irq_id_source(irq: IrqId) -> u32 {
    irq & IRQ_ID_SOURCE_MASK
}

#[inline]
pub const fn irq_id_external(source: u32) -> IrqId {
    irq_id_make(IRQ_KIND_EXTERNAL, source)
}

#[inline]
fn status_result(status: i32) -> Result<(), IrqError> {
    match status {
        0 => Ok(()),
        -1 => Err(IrqError::Invalid),
        -2 => Err(IrqError::Unsupported),
        value => Err(IrqError::UnexpectedStatus(value)),
    }
}

/// 设置硬件直接跳转的 trap 入口。
///
/// # Safety
///
/// `entry` 必须指向满足当前架构 trap ABI、对齐和现场保存要求的有效入口。
#[inline]
pub unsafe fn set_trap_entry(entry: usize) -> Result<(), IrqError> {
    status_result(unsafe { c_set_trap_entry(entry) })
}

#[inline]
pub fn get_irq() -> IrqMask {
    unsafe { c_get_irq() }
}

/// 覆盖 CPU 中断大类 mask，返回修改前的 mask。
#[inline]
pub fn set_irq(mask: IrqMask) -> IrqMask {
    unsafe { c_set_irq(mask) }
}

/// 开启指定 CPU 中断大类，返回修改前的 mask。
#[inline]
pub fn enable_irq(mask: IrqMask) -> IrqMask {
    unsafe { c_enable_irq(mask) }
}

/// 关闭指定 CPU 中断大类，返回修改前的 mask。
#[inline]
pub fn disable_irq(mask: IrqMask) -> IrqMask {
    unsafe { c_disable_irq(mask) }
}

/// 修改 CPU 中断总开关，返回修改前的状态。
#[inline]
pub fn global_irq(enabled: bool) -> bool {
    unsafe { c_global_irq(enabled) }
}

#[inline]
pub fn enable_irq_source(irq: IrqId) -> Result<(), IrqError> {
    status_result(unsafe { c_enable_irq_source(irq) })
}

#[inline]
pub fn disable_irq_source(irq: IrqId) -> Result<(), IrqError> {
    status_result(unsafe { c_disable_irq_source(irq) })
}

/// 领取一个 pending 外部中断；没有 pending 中断时返回 `Ok(None)`。
#[inline]
pub fn claim_external_irq() -> Result<Option<IrqId>, IrqError> {
    let mut irq = 0;

    match unsafe { c_claim_external_irq(&mut irq) } {
        0 => Ok(None),
        1 => Ok(Some(irq)),
        -1 => Err(IrqError::Invalid),
        -2 => Err(IrqError::Unsupported),
        value => Err(IrqError::UnexpectedStatus(value)),
    }
}

#[inline]
pub fn complete_external_irq(irq: IrqId) -> Result<(), IrqError> {
    status_result(unsafe { c_complete_external_irq(irq) })
}

/// 在当前作用域关闭总中断，并在离开作用域时恢复此前状态。
#[must_use = "dropping the guard immediately restores the previous IRQ state"]
pub struct GlobalIrqGuard {
    previous: bool,
    // IRQ 总开关是 hart-local 状态，guard 不能在线程或 hart 之间移动。
    _not_send: PhantomData<*mut ()>,
}

impl GlobalIrqGuard {
    #[inline]
    pub fn disable() -> Self {
        Self {
            previous: global_irq(false),
            _not_send: PhantomData,
        }
    }

    #[inline]
    pub const fn was_enabled(&self) -> bool {
        self.previous
    }
}

impl Drop for GlobalIrqGuard {
    #[inline]
    fn drop(&mut self) {
        global_irq(self.previous);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn irq_id_layout_matches_c_header() {
        let irq = irq_id_external(10);

        assert_eq!(irq_id_kind(irq), IRQ_KIND_EXTERNAL);
        assert_eq!(irq_id_source(irq), 10);
        assert_eq!(irq, 0x3000_000a);
    }
}
