//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//无需分配器、locale、errno 或宿主 C 库的实现

#include "string_noalloc.h"

#include <stdint.h>

static u8 ascii_lower(u8 ch) {
    if (ch >= (u8)'A' && ch <= (u8)'Z') {
        return (u8)(ch + ((u8)'a' - (u8)'A'));
    }
    return ch;
}

static bool char_in_set(u8 ch, const char *set) {
    while (*set != '\0') {
        if ((u8)*set == ch) {
            return true;
        }
        ++set;
    }
    return false;
}

static bool ascii_space(u8 ch) {
    return ch == (u8)' ' || ch == (u8)'\t' ||
           ch == (u8)'\n' || ch == (u8)'\r' ||
           ch == (u8)'\v' || ch == (u8)'\f';
}

void *memcpy(void *dest, const void *src, usize n) {
    u8 *dst_bytes = (u8 *)dest;
    const u8 *src_bytes = (const u8 *)src;

    for (usize i = 0; i < n; ++i) {
        dst_bytes[i] = src_bytes[i];
    }
    return dest;
}

void *memmove(void *dest, const void *src, usize n) {
    u8 *dst_bytes = (u8 *)dest;
    const u8 *src_bytes = (const u8 *)src;
    usize dst_addr = (usize)dest;
    usize src_addr = (usize)src;

    if (dest == src || n == 0) {
        return dest;
    }

    if (dst_addr < src_addr || dst_addr - src_addr >= n) {
        for (usize i = 0; i < n; ++i) {
            dst_bytes[i] = src_bytes[i];
        }
    } else {
        for (usize i = n; i != 0; --i) {
            dst_bytes[i - 1] = src_bytes[i - 1];
        }
    }
    return dest;
}

i32 memcmp(const void *lhs, const void *rhs, usize n) {
    const u8 *lhs_bytes = (const u8 *)lhs;
    const u8 *rhs_bytes = (const u8 *)rhs;

    for (usize i = 0; i < n; ++i) {
        if (lhs_bytes[i] != rhs_bytes[i]) {
            return (i32)lhs_bytes[i] - (i32)rhs_bytes[i];
        }
    }
    return 0;
}

void *memchr(const void *ptr, i32 ch, usize n) {
    const u8 *bytes = (const u8 *)ptr;
    u8 target = (u8)ch;

    for (usize i = 0; i < n; ++i) {
        if (bytes[i] == target) {
            return (void *)(bytes + i);
        }
    }
    return NULL;
}

void *memrchr(const void *ptr, i32 ch, usize n) {
    const u8 *bytes = (const u8 *)ptr;
    u8 target = (u8)ch;

    for (usize i = n; i != 0; --i) {
        if (bytes[i - 1] == target) {
            return (void *)(bytes + i - 1);
        }
    }
    return NULL;
}

void *memmem(const void *haystack, usize haystack_len,
             const void *needle, usize needle_len) {
    const u8 *haystack_bytes = (const u8 *)haystack;
    const u8 *needle_bytes = (const u8 *)needle;

    if (needle_len == 0) {
        return (void *)haystack_bytes;
    }
    if (needle_len > haystack_len) {
        return NULL;
    }

    for (usize i = 0; i <= haystack_len - needle_len; ++i) {
        if (haystack_bytes[i] == needle_bytes[0] &&
            memcmp(haystack_bytes + i, needle_bytes, needle_len) == 0) {
            return (void *)(haystack_bytes + i);
        }
    }
    return NULL;
}

void *memset(void *dest, i32 ch, usize n) {
    u8 *bytes = (u8 *)dest;
    u8 value = (u8)ch;

    for (usize i = 0; i < n; ++i) {
        bytes[i] = value;
    }
    return dest;
}

void memzero_explicit(void *dest, usize n) {
    volatile u8 *bytes = (volatile u8 *)dest;

    while (n != 0) {
        *bytes++ = 0;
        --n;
    }
}

void *mempcpy(void *dest, const void *src, usize n) {
    memcpy(dest, src, n);
    return (u8 *)dest + n;
}

usize strlen(const char *str) {
    const char *end = str;

    while (*end != '\0') {
        ++end;
    }
    return (usize)(end - str);
}

usize strnlen(const char *str, usize max_len) {
    usize len = 0;

    while (len < max_len && str[len] != '\0') {
        ++len;
    }
    return len;
}

i32 strcmp(const char *lhs, const char *rhs) {
    while (*lhs != '\0' && (u8)*lhs == (u8)*rhs) {
        ++lhs;
        ++rhs;
    }
    return (i32)(u8)*lhs - (i32)(u8)*rhs;
}

i32 strncmp(const char *lhs, const char *rhs, usize n) {
    for (usize i = 0; i < n; ++i) {
        u8 left = (u8)lhs[i];
        u8 right = (u8)rhs[i];

        if (left != right) {
            return (i32)left - (i32)right;
        }
        if (left == 0) {
            return 0;
        }
    }
    return 0;
}

i32 strcasecmp_ascii(const char *lhs, const char *rhs) {
    for (;;) {
        u8 left = ascii_lower((u8)*lhs++);
        u8 right = ascii_lower((u8)*rhs++);

        if (left != right || left == 0) {
            return (i32)left - (i32)right;
        }
    }
}

i32 strncasecmp_ascii(const char *lhs, const char *rhs, usize n) {
    for (usize i = 0; i < n; ++i) {
        u8 left = ascii_lower((u8)lhs[i]);
        u8 right = ascii_lower((u8)rhs[i]);

        if (left != right) {
            return (i32)left - (i32)right;
        }
        if (left == 0) {
            return 0;
        }
    }
    return 0;
}

char *strchr(const char *str, i32 ch) {
    u8 target = (u8)ch;

    for (;;) {
        if ((u8)*str == target) {
            return (char *)str;
        }
        if (*str == '\0') {
            return NULL;
        }
        ++str;
    }
}

char *strrchr(const char *str, i32 ch) {
    const char *last = NULL;
    u8 target = (u8)ch;

    for (;;) {
        if ((u8)*str == target) {
            last = str;
        }
        if (*str == '\0') {
            return (char *)last;
        }
        ++str;
    }
}

char *strchrnul(const char *str, i32 ch) {
    u8 target = (u8)ch;

    while (*str != '\0' && (u8)*str != target) {
        ++str;
    }
    return (char *)str;
}

char *strnchr(const char *str, usize count, i32 ch) {
    u8 target = (u8)ch;

    for (usize i = 0; i < count; ++i) {
        if ((u8)str[i] == target) {
            return (char *)(str + i);
        }
        if (str[i] == '\0') {
            return NULL;
        }
    }
    return NULL;
}

char *strstr(const char *haystack, const char *needle) {
    if (*needle == '\0') {
        return (char *)haystack;
    }

    while (*haystack != '\0') {
        const char *left = haystack;
        const char *right = needle;

        while (*right != '\0' && *left == *right) {
            ++left;
            ++right;
        }
        if (*right == '\0') {
            return (char *)haystack;
        }
        ++haystack;
    }
    return NULL;
}

char *strnstr(const char *haystack, const char *needle, usize len) {
    if (*needle == '\0') {
        return (char *)haystack;
    }

    for (usize i = 0; i < len && haystack[i] != '\0'; ++i) {
        usize j = 0;

        while (needle[j] != '\0' && i + j < len &&
               haystack[i + j] != '\0' && haystack[i + j] == needle[j]) {
            ++j;
        }
        if (needle[j] == '\0') {
            return (char *)(haystack + i);
        }
    }
    return NULL;
}

char *strcasestr_ascii(const char *haystack, const char *needle) {
    if (*needle == '\0') {
        return (char *)haystack;
    }

    while (*haystack != '\0') {
        const char *left = haystack;
        const char *right = needle;

        while (*right != '\0' && *left != '\0' &&
               ascii_lower((u8)*left) ==
                   ascii_lower((u8)*right)) {
            ++left;
            ++right;
        }
        if (*right == '\0') {
            return (char *)haystack;
        }
        ++haystack;
    }
    return NULL;
}

usize strspn(const char *str, const char *accept) {
    usize len = 0;

    while (str[len] != '\0' &&
           char_in_set((u8)str[len], accept)) {
        ++len;
    }
    return len;
}

usize strcspn(const char *str, const char *reject) {
    usize len = 0;

    while (str[len] != '\0' &&
           !char_in_set((u8)str[len], reject)) {
        ++len;
    }
    return len;
}

char *strpbrk(const char *str, const char *accept) {
    while (*str != '\0') {
        if (char_in_set((u8)*str, accept)) {
            return (char *)str;
        }
        ++str;
    }
    return NULL;
}

i32 strstarts(const char *str, const char *prefix) {
    while (*prefix != '\0') {
        if (*str++ != *prefix++) {
            return 0;
        }
    }
    return 1;
}

i32 strends(const char *str, const char *suffix) {
    usize str_len = strlen(str);
    usize suffix_len = strlen(suffix);

    if (suffix_len > str_len) {
        return 0;
    }
    return memcmp(str + str_len - suffix_len, suffix, suffix_len) == 0;
}

usize strlcpy(char *dest, const char *src, usize size) {
    usize src_len = strlen(src);

    if (size != 0) {
        usize copy_len = src_len < size - 1 ? src_len : size - 1;
        memcpy(dest, src, copy_len);
        dest[copy_len] = '\0';
    }
    return src_len;
}

usize strlcat(char *dest, const char *src, usize size) {
    usize dest_len = strnlen(dest, size);
    usize src_len = strlen(src);

    if (dest_len == size) {
        return size + src_len;
    }
    if (dest_len + 1 < size) {
        usize available = size - dest_len - 1;
        usize copy_len = src_len < available ? src_len : available;
        memcpy(dest + dest_len, src, copy_len);
        dest[dest_len + copy_len] = '\0';
    }
    return dest_len + src_len;
}

isize strscpy(char *dest, const char *src, usize size) {
    if (size == 0) {
        return -1;
    }

    usize i = 0;
    while (i + 1 < size && src[i] != '\0') {
        dest[i] = src[i];
        ++i;
    }
    dest[i] = '\0';

    if (src[i] != '\0') {
        return -1;
    }
    return (isize)i;
}

char *stpcpy(char *dest, const char *src) {
    while (*src != '\0') {
        *dest++ = *src++;
    }
    *dest = '\0';
    return dest;
}

char *strsep(char **stringp, const char *delim) {
    char *token;
    char *cursor;

    if (stringp == NULL || *stringp == NULL) {
        return NULL;
    }

    token = *stringp;
    cursor = token;
    while (*cursor != '\0') {
        if (char_in_set((u8)*cursor, delim)) {
            *cursor = '\0';
            *stringp = cursor + 1;
            return token;
        }
        ++cursor;
    }

    *stringp = NULL;
    return token;
}

char *strtok_r(char *str, const char *delim, char **saveptr) {
    char *token;

    if (str == NULL) {
        str = *saveptr;
    }
    if (str == NULL) {
        return NULL;
    }

    while (*str != '\0' && char_in_set((u8)*str, delim)) {
        ++str;
    }
    if (*str == '\0') {
        *saveptr = str;
        return NULL;
    }

    token = str;
    while (*str != '\0' && !char_in_set((u8)*str, delim)) {
        ++str;
    }
    if (*str != '\0') {
        *str = '\0';
        ++str;
    }
    *saveptr = str;
    return token;
}

char *strtok(char *str, const char *delim) {
    static char *state;
    return strtok_r(str, delim, &state);
}

const char *skip_spaces(const char *str) {
    while (ascii_space((u8)*str)) {
        ++str;
    }
    return str;
}

char *strim(char *str) {
    char *start = (char *)skip_spaces(str);
    char *end = start + strlen(start);

    while (end != start && ascii_space((u8)end[-1])) {
        --end;
    }
    *end = '\0';
    return start;
}

const char *kbasename(const char *path) {
    const char *base = path;

    while (*path != '\0') {
        if (*path == '/') {
            base = path + 1;
        }
        ++path;
    }
    return base;
}
