#!/usr/bin/env python3
# generated by gpt-5<noreply@openai.com> @ codex
"""Discover and validate ShyOS module and numbered-layer build DAGs."""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


LAYER_NAME = re.compile(r"^(?P<rank>[0-9]{2})(?P<name>[a-z][a-z0-9_]*)$")
LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"', re.MULTILINE)
DEPENDENCY_TABLES = {"dependencies", "dev-dependencies", "build-dependencies"}
MAX_INTRA_LAYER_DEPTH = 3


class LayerError(RuntimeError):
    pass


@dataclass(frozen=True)
class Layer:
    key: str
    rank: int
    path: Path
    dependencies: tuple[str, ...]
    image: bool

    @property
    def archive(self) -> Path:
        return self.path / "target" / f"libshyos_{self.key}.a"

    @property
    def rust_archive(self) -> Path:
        return self.path / "target" / f"libshyos_{self.key}_rust.a"


@dataclass(frozen=True)
class Module:
    key: str
    path: Path
    layer: str | None
    buildable: bool
    capability: str | None
    provides: tuple[CapabilityProvider, ...]


@dataclass(frozen=True)
class CapabilityProvider:
    capability: str
    define: str


def load_module_metadata(path: Path) -> tuple[str | None, tuple[CapabilityProvider, ...]]:
    manifest = path / "Cargo.toml"
    if not manifest.is_file():
        return None, ()

    with manifest.open("rb") as stream:
        document = tomllib.load(stream)
    package = document.get("package")
    if not isinstance(package, dict):
        return None, ()
    metadata = package.get("metadata")
    if not isinstance(metadata, dict):
        return None, ()
    shyos = metadata.get("shyos")
    if shyos is None:
        return None, ()
    if not isinstance(shyos, dict):
        raise LayerError(f"{manifest}: package.metadata.shyos must be a table")

    capability = shyos.get("capability")
    if capability is not None and (
        not isinstance(capability, str) or not capability
    ):
        raise LayerError(f"{manifest}: shyos.capability must be a non-empty string")

    raw_providers = shyos.get("provides", [])
    if not isinstance(raw_providers, list):
        raise LayerError(f"{manifest}: shyos.provides must be an array of tables")
    providers: list[CapabilityProvider] = []
    for provider in raw_providers:
        if not isinstance(provider, dict):
            raise LayerError(f"{manifest}: each shyos.provides item must be a table")
        provided = provider.get("capability")
        define = provider.get("define")
        if not isinstance(provided, str) or not provided:
            raise LayerError(
                f"{manifest}: provider capability must be a non-empty string"
            )
        if not isinstance(define, str) or not define:
            raise LayerError(f"{manifest}: provider define must be a non-empty string")
        providers.append(CapabilityProvider(provided, define))
    return capability, tuple(providers)


def load_layers(root: Path) -> dict[str, Layer]:
    lib_dir = root / "lib"
    layers: dict[str, Layer] = {}

    if not lib_dir.is_dir():
        raise LayerError(f"missing layer directory: {lib_dir}")

    for path in sorted(item for item in lib_dir.iterdir() if item.is_dir()):
        match = LAYER_NAME.fullmatch(path.name)
        if match is None:
            if not (path / "Cargo.toml").is_file() and not (path / "Makefile").is_file():
                raise LayerError(
                    f"unnumbered lib directory must be a shared module: {path.name}"
                )
            continue

        metadata_path = path / "layer.toml"
        if not metadata_path.is_file():
            raise LayerError(f"{path.name}: missing layer.toml")

        with metadata_path.open("rb") as stream:
            document = tomllib.load(stream)
        metadata = document.get("layer")
        if not isinstance(metadata, dict):
            raise LayerError(f"{metadata_path}: missing [layer] table")

        dependencies = metadata.get("dependencies", [])
        image = metadata.get("image", True)
        if not isinstance(dependencies, list) or not all(
            isinstance(item, str) for item in dependencies
        ):
            raise LayerError(f"{metadata_path}: dependencies must be a string array")
        if not isinstance(image, bool):
            raise LayerError(f"{metadata_path}: image must be true or false")

        layers[path.name] = Layer(
            key=path.name,
            rank=int(match.group("rank")),
            path=path.resolve(),
            dependencies=tuple(dependencies),
            image=image,
        )

    if not layers:
        raise LayerError("no numbered layers found under lib/")
    return layers


def load_modules(root: Path, layers: dict[str, Layer]) -> dict[str, Module]:
    lib_dir = (root / "lib").resolve()
    modules: dict[str, Module] = {}

    for path in sorted(item for item in lib_dir.rglob("*") if item.is_dir()):
        if "target" in path.parts:
            continue
        if not (path / "Cargo.toml").is_file() and not (path / "Makefile").is_file():
            continue
        relative = path.relative_to(lib_dir)
        first = relative.parts[0]
        layer = first if first in layers else None
        key = relative.as_posix()
        capability, provides = load_module_metadata(path)
        modules[key] = Module(
            key=key,
            path=path.resolve(),
            layer=layer,
            buildable=(path / "Makefile").is_file(),
            capability=capability,
            provides=provides,
        )

    for layer in layers.values():
        if layer.key not in modules:
            modules[layer.key] = Module(
                key=layer.key,
                path=layer.path,
                layer=layer.key,
                buildable=(layer.path / "Makefile").is_file(),
                capability=None,
                provides=(),
            )
    return modules


def validate_capabilities(modules: dict[str, Module]) -> None:
    capabilities: dict[str, str] = {}
    provider_defines: set[tuple[str, str]] = set()

    for module in modules.values():
        if module.capability is None:
            continue
        previous = capabilities.get(module.capability)
        if previous is not None:
            raise LayerError(
                f"capability {module.capability!r} is declared by both "
                f"{previous} and {module.key}"
            )
        capabilities[module.capability] = module.key

    for module in modules.values():
        for provider in module.provides:
            if provider.capability not in capabilities:
                raise LayerError(
                    f"{module.key} provides unknown capability "
                    f"{provider.capability!r}"
                )
            selector = (provider.capability, provider.define)
            if selector in provider_defines:
                raise LayerError(
                    f"capability {provider.capability!r} has duplicate provider "
                    f"selector {provider.define}"
                )
            provider_defines.add(selector)


def validate_layer_graph(layers: dict[str, Layer]) -> None:
    for layer in layers.values():
        if len(layer.dependencies) != len(set(layer.dependencies)):
            raise LayerError(f"{layer.key}: duplicate layer dependency")
        for dependency_name in layer.dependencies:
            dependency = layers.get(dependency_name)
            if dependency is None:
                raise LayerError(
                    f"{layer.key}: unknown layer dependency {dependency_name}"
                )
            if dependency.rank == layer.rank:
                raise LayerError(
                    f"{layer.key} -> {dependency.key}: horizontal dependency "
                    f"between rank {layer.rank:02d} layers is forbidden"
                )
            if dependency.rank > layer.rank:
                raise LayerError(
                    f"{layer.key} -> {dependency.key}: dependency points upward "
                    f"from rank {layer.rank:02d} to {dependency.rank:02d}"
                )
    topological_order(
        {name: set(layer.dependencies) for name, layer in layers.items()},
        "layer",
    )


def dependency_closure(layers: dict[str, Layer], name: str) -> set[str]:
    closure: set[str] = set()

    def collect(current: str) -> None:
        for dependency in layers[current].dependencies:
            if dependency not in closure:
                closure.add(dependency)
                collect(dependency)

    collect(name)
    return closure


def ordered_layer_closure(layers: dict[str, Layer], name: str) -> list[Layer]:
    if name not in layers:
        raise LayerError(f"unknown layer: {name}")
    names = dependency_closure(layers, name)
    names.add(name)
    return sorted(
        (layers[item] for item in names),
        key=lambda layer: (-layer.rank, layer.key),
    )


def owner_module(modules: dict[str, Module], path: Path) -> Module | None:
    resolved = path.resolve()
    owners: list[Module] = []
    for module in modules.values():
        try:
            resolved.relative_to(module.path)
        except ValueError:
            continue
        owners.append(module)
    if not owners:
        return None
    return max(owners, key=lambda module: len(module.path.parts))


def dependency_paths(document: object) -> Iterable[str]:
    if not isinstance(document, dict):
        return
    for key, value in document.items():
        if key in DEPENDENCY_TABLES and isinstance(value, dict):
            for dependency in value.values():
                if isinstance(dependency, dict):
                    path = dependency.get("path")
                    if isinstance(path, str):
                        yield path
        if isinstance(value, dict):
            yield from dependency_paths(value)


def add_dependency(
    graph: dict[str, set[str]], source: Module, target: Module
) -> None:
    if source.key != target.key:
        graph[source.key].add(target.key)


def cargo_dependencies(
    root: Path,
    modules: dict[str, Module],
    graph: dict[str, set[str]],
) -> None:
    for module in modules.values():
        manifest = module.path / "Cargo.toml"
        if not manifest.is_file():
            continue
        with manifest.open("rb") as stream:
            document = tomllib.load(stream)
        for dependency_path in dependency_paths(document):
            target_path = (manifest.parent / dependency_path).resolve()
            target = owner_module(modules, target_path)
            if target is None:
                try:
                    target_path.relative_to((root / "lib").resolve())
                except ValueError:
                    continue
                raise LayerError(
                    f"{manifest.relative_to(root)} path={dependency_path!r}: "
                    "target is not a module"
                )
            add_dependency(graph, module, target)


def header_candidates(modules: dict[str, Module]) -> dict[str, list[Path]]:
    candidates: dict[str, list[Path]] = {}
    for module in modules.values():
        for header in module.path.rglob("*.h"):
            if "target" in header.parts:
                continue
            if owner_module(modules, header) != module:
                continue
            relative = header.relative_to(module.path).as_posix()
            candidates.setdefault(header.name, []).append(header)
            candidates.setdefault(relative, []).append(header)
    return candidates


def c_dependencies(
    root: Path,
    modules: dict[str, Module],
    graph: dict[str, set[str]],
) -> None:
    candidates = header_candidates(modules)
    lib_dir = root / "lib"

    for pattern in ("*.c", "*.h", "*.S"):
        for source_path in sorted(lib_dir.rglob(pattern)):
            if "target" in source_path.parts:
                continue
            source = owner_module(modules, source_path)
            if source is None:
                continue
            text = source_path.read_text(encoding="utf-8")
            for include in LOCAL_INCLUDE.findall(text):
                local = (source_path.parent / include).resolve()
                if local.is_file():
                    target = owner_module(modules, local)
                    if target is not None:
                        add_dependency(graph, source, target)
                    continue

                matches = candidates.get(include, [])
                owners = {
                    target.key: target
                    for match in matches
                    if (target := owner_module(modules, match)) is not None
                }
                if len(owners) > 1:
                    names = ", ".join(sorted(owners))
                    raise LayerError(
                        f"{source_path.relative_to(root)} includes {include!r}: "
                        f"ambiguous module providers: {names}"
                    )
                if len(owners) == 1:
                    add_dependency(graph, source, next(iter(owners.values())))


def build_module_graph(
    root: Path,
    layers: dict[str, Layer],
    modules: dict[str, Module],
) -> dict[str, set[str]]:
    graph = {name: set() for name in modules}
    cargo_dependencies(root, modules, graph)
    c_dependencies(root, modules, graph)

    for source_name, dependencies in graph.items():
        source = modules[source_name]
        for target_name in dependencies:
            target = modules[target_name]
            validate_module_direction(layers, source, target)
    topological_order(graph, "module")
    validate_intra_layer_depth(layers, modules, graph)
    return graph


def validate_module_direction(
    layers: dict[str, Layer], source: Module, target: Module
) -> None:
    if source.layer is None:
        if target.layer is not None:
            raise LayerError(
                f"shared module {source.key} cannot depend on numbered module {target.key}"
            )
        return
    if target.layer is None or source.layer == target.layer:
        return

    source_layer = layers[source.layer]
    target_layer = layers[target.layer]
    if source_layer.rank == target_layer.rank:
        raise LayerError(
            f"{source.key} -> {target.key}: horizontal dependency between "
            f"rank {source_layer.rank:02d} layers"
        )
    if source_layer.rank < target_layer.rank:
        raise LayerError(
            f"{source.key} -> {target.key}: dependency points upward from "
            f"{source.layer} to {target.layer}"
        )
    if target.layer not in dependency_closure(layers, source.layer):
        raise LayerError(
            f"{source.key} -> {target.key}: {source.layer} references "
            f"undeclared layer {target.layer}"
        )


def topological_order(
    graph: dict[str, set[str]], graph_name: str
) -> list[str]:
    order: list[str] = []
    visiting: list[str] = []
    visited: set[str] = set()

    def visit(name: str) -> None:
        if name in visiting:
            cycle = " -> ".join(visiting[visiting.index(name) :] + [name])
            raise LayerError(f"{graph_name} dependency cycle: {cycle}")
        if name in visited:
            return
        visiting.append(name)
        for dependency in sorted(graph[name]):
            visit(dependency)
        visiting.pop()
        visited.add(name)
        order.append(name)

    for name in sorted(graph):
        visit(name)
    return order


def intra_layer_depths(
    layers: dict[str, Layer],
    modules: dict[str, Module],
    graph: dict[str, set[str]],
) -> dict[str, tuple[int, list[str]]]:
    results: dict[str, tuple[int, list[str]]] = {}

    for layer_name in layers:
        component_names = {
            name
            for name, module in modules.items()
            if module.layer == layer_name and name != layer_name
        }
        memo: dict[str, tuple[int, list[str]]] = {}

        def depth(name: str) -> tuple[int, list[str]]:
            cached = memo.get(name)
            if cached is not None:
                return cached
            dependencies = [
                dependency
                for dependency in graph[name]
                if dependency in component_names
            ]
            if not dependencies:
                result = (1, [name])
            else:
                dependency_depth, dependency_path = max(
                    (depth(dependency) for dependency in dependencies),
                    key=lambda item: item[0],
                )
                result = (dependency_depth + 1, [name, *dependency_path])
            memo[name] = result
            return result

        if component_names:
            results[layer_name] = max(
                (depth(name) for name in component_names),
                key=lambda item: item[0],
            )
        else:
            results[layer_name] = (0, [])
    return results


def validate_intra_layer_depth(
    layers: dict[str, Layer],
    modules: dict[str, Module],
    graph: dict[str, set[str]],
) -> None:
    for layer_name, (depth, consumer_to_dependency) in intra_layer_depths(
        layers, modules, graph
    ).items():
        if depth <= MAX_INTRA_LAYER_DEPTH:
            continue
        build_order = " -> ".join(reversed(consumer_to_dependency))
        raise LayerError(
            f"{layer_name}: intra-layer module dependency depth {depth} "
            f"exceeds limit {MAX_INTRA_LAYER_DEPTH}: {build_order}"
        )


def module_order_for_layer(
    layers: dict[str, Layer],
    modules: dict[str, Module],
    graph: dict[str, set[str]],
    layer_name: str,
    defines: set[str],
) -> list[str]:
    if layer_name not in layers:
        raise LayerError(f"unknown layer: {layer_name}")
    if layer_name not in modules:
        raise LayerError(f"{layer_name}: missing aggregate module")

    selected: set[str] = set()

    def collect(name: str) -> None:
        for dependency in graph[name]:
            module = modules[dependency]
            if module.layer not in (None, layer_name):
                continue
            if dependency not in selected:
                selected.add(dependency)
                collect(dependency)

    collect(layer_name)
    for name, module in modules.items():
        if module.layer != layer_name:
            continue
        if any(provider.define in defines for provider in module.provides):
            selected.add(name)
            collect(name)
    return [
        name
        for name in topological_order(graph, "module")
        if name in selected and modules[name].buildable
    ]


def validate(
    root: Path,
) -> tuple[dict[str, Layer], dict[str, Module], dict[str, set[str]]]:
    layers = load_layers(root)
    validate_layer_graph(layers)
    modules = load_modules(root, layers)
    validate_capabilities(modules)
    graph = build_module_graph(root, layers, modules)
    return layers, modules, graph


def module_include_dirs(modules: dict[str, Module]) -> list[Path]:
    return [modules[name].path for name in sorted(modules)]


def build_html_layout(
    layers: dict[str, Layer],
    modules: dict[str, Module],
    graph: dict[str, set[str]],
    defines: set[str],
    max_sweeps: int = 12,
) -> dict[str, object]:
    """Build the complete, deterministic slot layout consumed by the HTML."""
    ordered_layers = sorted(
        layers.values(), key=lambda layer: (layer.rank, layer.key)
    )
    module_order = topological_order(graph, "module")
    visible_names = {
        name
        for name in module_order
        if modules[name].layer is None or name != modules[name].layer
    }
    visible_order = [name for name in module_order if name in visible_names]
    order_index = {name: index for index, name in enumerate(visible_order)}
    depths = intra_layer_depths(layers, modules, graph)

    capability_modules = {
        module.capability: module.key
        for module in modules.values()
        if module.capability is not None and module.key in visible_names
    }
    providers_by_capability: dict[str, list[dict[str, object]]] = {}
    for module in modules.values():
        if module.key not in visible_names:
            continue
        for provider in module.provides:
            providers_by_capability.setdefault(provider.capability, []).append(
                {
                    "module": module.key,
                    "define": provider.define,
                    "selected": provider.define in defines,
                }
            )
    for providers in providers_by_capability.values():
        providers.sort(key=lambda provider: str(provider["module"]))

    columns: list[dict[str, object]] = [
        {"key": "shared", "rank": None, "slots": []}
    ]
    columns.extend(
        {
            "key": layer.key,
            "rank": layer.rank,
            "slots": [],
        }
        for layer in ordered_layers
    )
    column_index = {
        str(column["key"]): index for index, column in enumerate(columns)
    }

    def module_column(name: str) -> str:
        return modules[name].layer or "shared"

    for name in visible_order:
        column = columns[column_index[module_column(name)]]
        slots = column["slots"]
        assert isinstance(slots, list)
        slots.append(
            {
                "id": f"module:{name}",
                "type": "module",
                "key": name,
            }
        )

    shared_slots = columns[0]["slots"]
    assert isinstance(shared_slots, list)
    shared_slots.sort(
        key=lambda slot: (
            modules[str(slot["key"])].capability is None,
            order_index[str(slot["key"])],
            str(slot["key"]),
        )
    )

    edges: list[dict[str, object]] = []
    for consumer in visible_order:
        for dependency in sorted(graph[consumer] & visible_names):
            edges.append(
                {
                    "from": dependency,
                    "to": consumer,
                    "kind": "dependency",
                }
            )
    for capability, capability_module in sorted(capability_modules.items()):
        for provider in providers_by_capability.get(capability, []):
            edges.append(
                {
                    "from": capability_module,
                    "to": provider["module"],
                    "kind": "provider",
                    "define": provider["define"],
                    "selected": provider["selected"],
                }
            )
    edges.sort(
        key=lambda edge: (
            str(edge["kind"]),
            str(edge["from"]),
            str(edge["to"]),
            str(edge.get("define", "")),
        )
    )

    slot_columns: dict[str, int] = {}
    for index, column in enumerate(columns):
        slots = column["slots"]
        assert isinstance(slots, list)
        for slot in slots:
            slot_columns[str(slot["id"])] = index

    adjacent_neighbors: dict[str, set[str]] = {
        slot_id: set() for slot_id in slot_columns
    }
    for edge_number, edge in enumerate(edges):
        edge_id = f"edge:{edge_number}"
        edge["id"] = edge_id
        source = str(edge["from"])
        target = str(edge["to"])
        source_column = column_index[module_column(source)]
        target_column = column_index[module_column(target)]
        edge["intra"] = source_column == target_column
        edge["long"] = abs(target_column - source_column) > 1

        route: list[dict[str, object]] = [
            {
                "column": str(columns[source_column]["key"]),
                "slot": f"module:{source}",
            }
        ]
        if source_column != target_column:
            step = 1 if target_column > source_column else -1
            for index in range(source_column + step, target_column, step):
                if index == 0:
                    continue
                column_key = str(columns[index]["key"])
                dummy_id = f"dummy:{edge_id}:{column_key}"
                slots = columns[index]["slots"]
                assert isinstance(slots, list)
                slots.append(
                    {
                        "id": dummy_id,
                        "type": "dummy",
                        "edge": edge_id,
                    }
                )
                slot_columns[dummy_id] = index
                adjacent_neighbors[dummy_id] = set()
                route.append({"column": column_key, "slot": dummy_id})
        route.append(
            {
                "column": str(columns[target_column]["key"]),
                "slot": f"module:{target}",
            }
        )
        edge["route"] = route

        if not edge["intra"]:
            for first, second in zip(route, route[1:]):
                first_id = str(first["slot"])
                second_id = str(second["slot"])
                adjacent_neighbors[first_id].add(second_id)
                adjacent_neighbors[second_id].add(first_id)

    def reorder_column(index: int, neighbor_index: int) -> bool:
        slots = columns[index]["slots"]
        assert isinstance(slots, list)
        positions = {
            str(slot["id"]): position
            for position, slot in enumerate(columns[neighbor_index]["slots"])
        }
        previous = [str(slot["id"]) for slot in slots]
        current_positions = {
            str(slot["id"]): position for position, slot in enumerate(slots)
        }

        def barycenter(slot: dict[str, object]) -> tuple[float, int, str]:
            slot_id = str(slot["id"])
            connected = [
                positions[neighbor]
                for neighbor in adjacent_neighbors[slot_id]
                if neighbor in positions
            ]
            center = (
                sum(connected) / len(connected)
                if connected
                else float(current_positions[slot_id])
            )
            return center, current_positions[slot_id], slot_id

        if index == 0:
            capabilities = [
                slot
                for slot in slots
                if modules[str(slot["key"])].capability is not None
            ]
            shared_modules = [
                slot
                for slot in slots
                if modules[str(slot["key"])].capability is None
            ]
            slots[:] = sorted(capabilities, key=barycenter) + sorted(
                shared_modules, key=barycenter
            )
        else:
            slots.sort(key=barycenter)
        return previous != [str(slot["id"]) for slot in slots]

    for _ in range(max_sweeps):
        changed = False
        for index in range(1, len(columns)):
            changed |= reorder_column(index, index - 1)
        for index in range(len(columns) - 2, -1, -1):
            changed |= reorder_column(index, index + 1)
        if not changed:
            break

    module_payload = [
        {
            "key": name,
            "layer": modules[name].layer,
            "kind": (
                "capability"
                if modules[name].capability is not None
                else "module"
            ),
            "dependencies": sorted(graph[name] & visible_names),
            "buildable": modules[name].buildable,
            "capability": modules[name].capability,
            "providers": providers_by_capability.get(
                modules[name].capability or "", []
            ),
            "provides": [
                {
                    "capability": provider.capability,
                    "define": provider.define,
                    "selected": provider.define in defines,
                }
                for provider in modules[name].provides
            ],
        }
        for name in visible_order
    ]
    return {
        "maxIntraLayerDepth": MAX_INTRA_LAYER_DEPTH,
        "defines": sorted(defines),
        "layers": [
            {
                "key": layer.key,
                "rank": layer.rank,
                "dependencies": list(layer.dependencies),
                "moduleDepth": depths[layer.key][0],
            }
            for layer in ordered_layers
        ],
        "modules": module_payload,
        "columns": columns,
        "edges": edges,
    }


def stress_graph() -> tuple[
    dict[str, Layer], dict[str, Module], dict[str, set[str]], set[str]
]:
    """Create deterministic demonstration data without entering validation."""
    layer_specs = [
        ("00arch", 5),
        ("01log", 6),
        ("02core", 7),
        ("03basic", 5),
        ("04vm", 6),
        ("05task", 7),
        ("06syscall", 8),
        ("07compat", 6),
    ]
    layers: dict[str, Layer] = {}
    modules: dict[str, Module] = {}
    graph: dict[str, set[str]] = {}

    for rank, (key, _) in enumerate(layer_specs):
        layers[key] = Layer(
            key=key,
            rank=rank,
            path=Path(f"/stress/{key}"),
            dependencies=(() if rank == 0 else (layer_specs[rank - 1][0],)),
            image=True,
        )

    shared_specs = [
        ("alloc", "alloc"),
        ("scheduler", "scheduler"),
        ("io_contract", "io"),
        ("board", None),
        ("abi", None),
        ("boot_protocol", None),
    ]
    for key, capability in shared_specs:
        modules[key] = Module(
            key=key,
            path=Path(f"/stress/{key}"),
            layer=None,
            buildable=True,
            capability=capability,
            provides=(),
        )
        graph[key] = set()

    names_by_layer: list[list[str]] = []
    for rank, (layer_key, count) in enumerate(layer_specs):
        names = [f"{layer_key}/module_{index + 1}" for index in range(count)]
        names_by_layer.append(names)
        for index, name in enumerate(names):
            provides: tuple[CapabilityProvider, ...] = ()
            if name == "03basic/module_1":
                provides = (
                    CapabilityProvider("alloc", "SHYOS_ALLOCATOR_SIMPLE"),
                )
            elif name == "04vm/module_2":
                provides = (
                    CapabilityProvider("alloc", "SHYOS_ALLOCATOR_VM"),
                )
            elif name == "05task/module_1":
                provides = (
                    CapabilityProvider("scheduler", "SHYOS_SCHEDULER_RR"),
                )
            elif name == "06syscall/module_3":
                provides = (
                    CapabilityProvider("scheduler", "SHYOS_SCHEDULER_FAIR"),
                )
            elif name == "01log/module_2":
                provides = (
                    CapabilityProvider("io", "SHYOS_IO_UART"),
                )
            elif name == "07compat/module_4":
                provides = (
                    CapabilityProvider("io", "SHYOS_IO_VFS"),
                )
            modules[name] = Module(
                key=name,
                path=Path(f"/stress/{name}"),
                layer=layer_key,
                buildable=True,
                capability=None,
                provides=provides,
            )
            dependencies: set[str] = set()
            if rank == 0:
                dependencies.add(("board", "abi", "boot_protocol")[index % 3])
            else:
                dependencies.add(
                    names_by_layer[rank - 1][
                        (index * 2 + rank) % len(names_by_layer[rank - 1])
                    ]
                )
            if rank >= 2 and index % 2 == 0:
                dependencies.add(
                    names_by_layer[rank - 2][
                        (index + rank) % len(names_by_layer[rank - 2])
                    ]
                )
            if rank >= 3 and index in (1, count - 1):
                dependencies.add(("board", "abi", "boot_protocol")[index % 3])
            if index % 3 == 2:
                dependencies.add(names[index - 1])
            graph[name] = dependencies

    return (
        layers,
        modules,
        graph,
        {
            "SHYOS_ALLOCATOR_VM",
            "SHYOS_SCHEDULER_RR",
            "SHYOS_IO_UART",
        },
    )


def emit_layer_file(
    root: Path,
    layers: dict[str, Layer],
    name: str,
    output: Path,
    include_rust: bool,
) -> None:
    archives = [layer.archive for layer in ordered_layer_closure(layers, name)]
    if include_rust:
        archives.append(layers[name].rust_archive)
    missing = [path for path in archives if not path.is_file()]
    if missing:
        paths = ", ".join(str(path.relative_to(root)) for path in missing)
        raise LayerError(f"cannot emit {name}.layer.ld; missing archives: {paths}")

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* generated by gpt-5.6-sol<noreply@openai.com> @ codex */",
        "GROUP (",
    ]
    lines.extend(f'  "{archive}"' for archive in archives)
    lines.append(")")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_html(
    root: Path,
    layers: dict[str, Layer],
    modules: dict[str, Module],
    graph: dict[str, set[str]],
    defines: set[str],
    output: Path,
) -> None:
    template_path = root / "tools" / "layer_dag_template.html"
    if not template_path.is_file():
        raise LayerError(f"missing HTML template: {template_path}")

    payload = build_html_layout(layers, modules, graph, defines)
    encoded = json.dumps(
        payload, ensure_ascii=False, separators=(",", ":")
    ).replace("<", "\\u003c")
    template = template_path.read_text(encoding="utf-8")
    marker = "__SHYOS_DAG_DATA__"
    if template.count(marker) != 1:
        raise LayerError(f"{template_path}: expected exactly one {marker} marker")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(template.replace(marker, encoded), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="ShyOS repository root",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("check")
    subparsers.add_parser("module-graph")
    subparsers.add_parser("include-dirs")

    list_parser = subparsers.add_parser("list")
    list_parser.add_argument("--image", action="store_true")

    deps_parser = subparsers.add_parser("deps")
    deps_parser.add_argument("--layer", required=True)

    closure_parser = subparsers.add_parser("closure")
    closure_parser.add_argument("--layer", required=True)

    modules_parser = subparsers.add_parser("module-order")
    modules_parser.add_argument("--layer", required=True)
    modules_parser.add_argument("--defines", default="")

    emit_parser = subparsers.add_parser("emit")
    emit_parser.add_argument("--layer", required=True)
    emit_parser.add_argument("--output", required=True, type=Path)
    emit_parser.add_argument("--norust", action="store_true")

    html_parser = subparsers.add_parser("html")
    html_parser.add_argument("--output", required=True, type=Path)
    html_parser.add_argument("--defines", default="")

    stress_parser = subparsers.add_parser("html-stress")
    stress_parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    try:
        if args.command == "html-stress":
            stress_layers, stress_modules, stress_dependencies, stress_defines = (
                stress_graph()
            )
            emit_html(
                root,
                stress_layers,
                stress_modules,
                stress_dependencies,
                stress_defines,
                args.output.resolve(),
            )
            return 0

        layers, modules, graph = validate(root)

        if args.command == "check":
            ordered = sorted(layers.values(), key=lambda layer: (layer.rank, layer.key))
            depths = intra_layer_depths(layers, modules, graph)
            print("layer DAG:", " -> ".join(layer.key for layer in ordered))
            print("module DAG: ok", f"({len(modules)} modules)")
            print(
                "intra-layer depth:",
                " ".join(
                    f"{layer.key}={depths[layer.key][0]}"
                    for layer in ordered
                ),
                f"(limit={MAX_INTRA_LAYER_DEPTH})",
            )
        elif args.command == "module-graph":
            for name in topological_order(graph, "module"):
                dependencies = " ".join(sorted(graph[name])) or "-"
                print(f"{name}: {dependencies}")
        elif args.command == "include-dirs":
            print(" ".join(str(path) for path in module_include_dirs(modules)))
        elif args.command == "list":
            ordered = sorted(layers.values(), key=lambda layer: (layer.rank, layer.key))
            print(
                " ".join(
                    layer.key for layer in ordered if not args.image or layer.image
                )
            )
        elif args.command == "deps":
            if args.layer not in layers:
                raise LayerError(f"unknown layer: {args.layer}")
            print(" ".join(layers[args.layer].dependencies))
        elif args.command == "closure":
            print(
                " ".join(
                    layer.key
                    for layer in ordered_layer_closure(layers, args.layer)
                )
            )
        elif args.command == "module-order":
            print(
                " ".join(
                    module_order_for_layer(
                        layers,
                        modules,
                        graph,
                        args.layer,
                        set(args.defines.split()),
                    )
                )
            )
        elif args.command == "emit":
            emit_layer_file(
                root,
                layers,
                args.layer,
                args.output.resolve(),
                not args.norust,
            )
        elif args.command == "html":
            emit_html(
                root,
                layers,
                modules,
                graph,
                set(args.defines.split()),
                args.output.resolve(),
            )
        return 0
    except (LayerError, tomllib.TOMLDecodeError, OSError) as error:
        print(f"layer graph error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
