#!/usr/bin/env python3
# generated by gpt-5.6-sol<noreply@openai.com> @ codex
"""Generate VS Code configuration from the active ShyOS Make config."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def write_json(path: Path, document: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(document, indent=2, ensure_ascii=True) + "\n",
        encoding="ascii",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--c-compiler", required=True)
    parser.add_argument("--rust-target", required=True)
    parser.add_argument("--rustflags", default="")
    parser.add_argument("--defines", default="")
    parser.add_argument("--kernel-elf", default="")
    parser.add_argument("--app-elf", default="")
    args = parser.parse_args()

    root = args.root.resolve()
    vscode_dir = root / ".vscode"

    write_json(
        vscode_dir / "settings.json",
        {
            "C_Cpp.default.compileCommands": (
                "${workspaceFolder}/compile_commands.json"
            ),
            "C_Cpp_Runner.cCompilerPath": args.c_compiler,
            "clangd.arguments": [
                "--compile-commands-dir=${workspaceFolder}",
            ],
            "rust-analyzer.linkedProjects": ["Cargo.toml"],
            "rust-analyzer.cargo.target": args.rust_target,
            "rust-analyzer.cargo.cfgs": args.defines.split(),
            "rust-analyzer.cargo.extraEnv": {
                "RUSTFLAGS": args.rustflags,
            },
            "rust-analyzer.check.allTargets": False,
        },
    )
    write_json(
        vscode_dir / "c_cpp_properties.json",
        {
            "configurations": [
                {
                    "name": "ShyOS",
                    "compileCommands": "${workspaceFolder}/compile_commands.json",
                    "compilerPath": args.c_compiler,
                }
            ],
            "version": 4,
        },
    )

    # GDB attach configurations for `make run-kernel-gdb` / `make run-app-gdb`
    # (QEMU frozen at reset with a gdb stub on :1234). Each configuration
    # starts its image's gdb run target via a background task first, then
    # attaches once the task prints the frozen banner.
    gdb_images = [
        (name, elf)
        for name, elf in [("kernel", args.kernel_elf), ("app", args.app_elf)]
        if elf
    ]
    configurations = [
        {
            "type": "gdb",
            "request": "attach",
            "name": f"Attach {name} (QEMU :1234)",
            "executable": elf,
            "target": "localhost:1234",
            "remote": True,
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText",
            "preLaunchTask": f"run-{name}-gdb",
        }
        for name, elf in gdb_images
    ]
    if configurations:
        write_json(
            vscode_dir / "launch.json",
            {"version": "0.2.0", "configurations": configurations},
        )
        write_json(
            vscode_dir / "tasks.json",
            {
                "version": "2.0.0",
                "tasks": [
                    {
                        "label": f"run-{name}-gdb",
                        "type": "shell",
                        "command": f"make run-{name}-gdb",
                        "isBackground": True,
                        "presentation": {"reveal": "always", "panel": "dedicated"},
                        "problemMatcher": {
                            "pattern": {"regexp": "^$"},
                            "background": {
                                "activeOnStart": True,
                                "beginsPattern": ".*",
                                "endsPattern": "QEMU frozen at reset",
                            },
                        },
                    }
                    for name, _ in gdb_images
                ],
            },
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
