#!/usr/bin/env python3
# generated by gpt-5.6-sol<noreply@openai.com> @ codex
"""Generate VS Code configuration from the active ShyOS Make config."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def write_json(path: Path, document: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(document, indent=2, ensure_ascii=True) + "\n",
        encoding="ascii",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--c-compiler", required=True)
    parser.add_argument("--rust-target", required=True)
    parser.add_argument("--rustflags", default="")
    parser.add_argument("--defines", default="")
    args = parser.parse_args()

    root = args.root.resolve()
    vscode_dir = root / ".vscode"

    write_json(
        vscode_dir / "settings.json",
        {
            "C_Cpp.default.compileCommands": (
                "${workspaceFolder}/compile_commands.json"
            ),
            "C_Cpp_Runner.cCompilerPath": args.c_compiler,
            "clangd.arguments": [
                "--compile-commands-dir=${workspaceFolder}",
            ],
            "rust-analyzer.linkedProjects": ["Cargo.toml"],
            "rust-analyzer.cargo.target": args.rust_target,
            "rust-analyzer.cargo.cfgs": args.defines.split(),
            "rust-analyzer.cargo.extraEnv": {
                "RUSTFLAGS": args.rustflags,
            },
            "rust-analyzer.check.allTargets": False,
        },
    )
    write_json(
        vscode_dir / "c_cpp_properties.json",
        {
            "configurations": [
                {
                    "name": "ShyOS",
                    "compileCommands": "${workspaceFolder}/compile_commands.json",
                    "compilerPath": args.c_compiler,
                }
            ],
            "version": 4,
        },
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
