//generated by gpt-5<noreply@openai.com> @ codex
//双世界接口统一为 raw_putc / raw_getc：
// 1) C 世界：#[no_mangle] extern "C"（见 uart.h）
// 2) Rust 世界：同名函数（参数用 u8，调用同一实现）
// Linux 用户态使用 read/write；裸机目标轮询 UART 寄存器

#![no_std]

use core::ffi::c_char;

#[cfg(not(target_os = "linux"))]
use board::{UART0_BASE, UART_LSR, UART_LSR_DR, UART_LSR_THRE, UART_RBR, UART_THR};
#[cfg(target_os = "linux")]
use core::ffi::{c_int, c_void};

#[cfg(target_os = "linux")]
unsafe extern "C" {
    fn shyos_linux_raw_getc() -> u8;
    fn write(fd: c_int, buf: *const c_void, count: usize) -> isize;
}

#[cfg(not(target_os = "linux"))]
#[inline(always)]
fn reg(offset: usize) -> *mut u8 {
    (UART0_BASE + offset) as *mut u8
}

/// 向 early console 写一字节（Rust）。
#[cfg(target_os = "linux")]
#[inline]
pub fn raw_putc(c: u8) {
    unsafe {
        let _ = write(1, (&c as *const u8).cast(), 1);
    }
}

/// 向 early console 写一字节（Rust）。
#[cfg(not(target_os = "linux"))]
#[inline]
pub fn raw_putc(c: u8) {
    unsafe {
        while reg(UART_LSR).read_volatile() & UART_LSR_THRE == 0 {}
        reg(UART_THR).write_volatile(c);
    }
}

/// 从 early console 读一字节（Rust）。
#[cfg(target_os = "linux")]
#[inline]
pub fn raw_getc() -> u8 {
    unsafe { shyos_linux_raw_getc() }
}

/// 从 early console 读一字节（Rust）。
#[cfg(not(target_os = "linux"))]
#[inline]
pub fn raw_getc() -> u8 {
    unsafe {
        while reg(UART_LSR).read_volatile() & UART_LSR_DR == 0 {}
        reg(UART_RBR).read_volatile()
    }
}

/// C ABI：void raw_putc(char c);
/// 导出符号名 raw_putc；与上面的 Rust 函数同名但分属不同导出路径。
/// 注意：Rust 侧请调用本模块的 raw_putc(u8)；C 侧链接本符号。
#[export_name = "raw_putc"]
pub extern "C" fn raw_putc_cabi(c: c_char) {
    raw_putc(c as u8);
}

/// C ABI：char raw_getc(void);
#[export_name = "raw_getc"]
pub extern "C" fn raw_getc_cabi() -> c_char {
    raw_getc() as c_char
}
