//generated by gpt-5<noreply@openai.com> @ codex
//early_raw_* 始终轮询；raw_* 由 SHYOS_UART_* provider 选择。

#![no_std]

use core::ffi::c_char;

#[cfg(not(target_os = "linux"))]
use board::{UART0_BASE, UART_LSR, UART_LSR_DR, UART_LSR_THRE, UART_RBR, UART_THR};
#[cfg(target_os = "linux")]
use core::ffi::{c_int, c_void};

#[cfg(target_os = "linux")]
unsafe extern "C" {
    fn shyos_linux_raw_getc() -> u8;
    fn write(fd: c_int, buf: *const c_void, count: usize) -> isize;
}

#[cfg(not(target_os = "linux"))]
#[inline(always)]
fn reg(offset: usize) -> *mut u8 {
    (UART0_BASE + offset) as *mut u8
}

/// 向 early console 写一字节（Rust），始终使用轮询实现。
#[cfg(target_os = "linux")]
#[inline]
pub fn early_raw_putc(c: u8) {
    unsafe {
        let _ = write(1, (&c as *const u8).cast(), 1);
    }
}

/// 向 early console 写一字节（Rust），始终使用轮询实现。
#[cfg(not(target_os = "linux"))]
#[inline]
pub fn early_raw_putc(c: u8) {
    unsafe {
        while reg(UART_LSR).read_volatile() & UART_LSR_THRE == 0 {}
        reg(UART_THR).write_volatile(c);
    }
}

/// 从 early console 读一字节（Rust），始终使用轮询实现。
#[cfg(target_os = "linux")]
#[inline]
pub fn early_raw_getc() -> u8 {
    unsafe { shyos_linux_raw_getc() }
}

/// 从 early console 读一字节（Rust），始终使用轮询实现。
#[cfg(not(target_os = "linux"))]
#[inline]
pub fn early_raw_getc() -> u8 {
    unsafe {
        while reg(UART_LSR).read_volatile() & UART_LSR_DR == 0 {}
        reg(UART_RBR).read_volatile()
    }
}

#[unsafe(export_name = "early_raw_putc")]
pub extern "C" fn early_raw_putc_cabi(c: c_char) {
    early_raw_putc(c as u8);
}

#[unsafe(export_name = "early_raw_getc")]
pub extern "C" fn early_raw_getc_cabi() -> c_char {
    early_raw_getc() as c_char
}

#[cfg(SHYOS_UART_POLLING)]
#[inline]
pub fn raw_putc(c: u8) {
    early_raw_putc(c);
}

#[cfg(SHYOS_UART_POLLING)]
#[inline]
pub fn raw_getc() -> u8 {
    early_raw_getc()
}

#[cfg(SHYOS_UART_POLLING)]
#[unsafe(export_name = "raw_putc")]
pub extern "C" fn raw_putc_cabi(c: c_char) {
    raw_putc(c as u8);
}

#[cfg(SHYOS_UART_POLLING)]
#[unsafe(export_name = "raw_getc")]
pub extern "C" fn raw_getc_cabi() -> c_char {
    raw_getc() as c_char
}

/// 轮询 provider 下无中断 UART 可初始化；保持与中断 provider 同名符号。
#[cfg(SHYOS_UART_POLLING)]
#[unsafe(no_mangle)]
pub extern "C" fn uart_interupt_init() -> i32 {
    0
}

#[cfg(SHYOS_UART_INTERRUPT)]
unsafe extern "C" {
    #[link_name = "raw_putc"]
    fn selected_raw_putc(c: c_char);
    #[link_name = "raw_getc"]
    fn selected_raw_getc() -> c_char;
}

#[cfg(SHYOS_UART_INTERRUPT)]
#[inline]
pub fn raw_putc(c: u8) {
    unsafe { selected_raw_putc(c as c_char) };
}

#[cfg(SHYOS_UART_INTERRUPT)]
#[inline]
pub fn raw_getc() -> u8 {
    unsafe { selected_raw_getc() as u8 }
}
