//generated by kimi-k3<noreply@moonshot.cn> @ kimi-code
//QEMU virt 中断驱动 UART provider。

#![no_std]

#[cfg(all(SHYOS_UART_INTERRUPT, not(target_os = "linux")))]
mod interrupt {
    use core::cell::UnsafeCell;
    use core::ffi::c_char;
    use core::mem::MaybeUninit;

    use board::{
        UART0_BASE, UART0_IRQ, UART_FCR, UART_FCR_CLEAR_RX, UART_FCR_CLEAR_TX,
        UART_FCR_ENABLE, UART_IER, UART_IER_RX_AVAILABLE, UART_IER_TX_EMPTY, UART_IIR,
        UART_IIR_ID_MASK, UART_IIR_LINE_STATUS, UART_IIR_NO_PENDING, UART_IIR_RX_AVAILABLE,
        UART_IIR_RX_TIMEOUT, UART_IIR_TX_EMPTY, UART_LSR, UART_LSR_DR, UART_LSR_THRE, UART_RBR,
        UART_THR,
    };
    use ringbuffer_no_alloc::RingBufferNoAlloc;
    use shyos_trap::irq::{
        enable_irq, enable_irq_source, irq_id_external, GlobalIrqGuard, IRQ_MASK_EXTERNAL,
    };
    use shyos_trap::{TrapContext, trap_set_external_handler};

    const BUFFER_SIZE: usize = 128;

    struct StaticCell<T>(UnsafeCell<T>);

    // 单 hart；前台访问由 GlobalIrqGuard 与 ISR 串行化。
    unsafe impl<T> Sync for StaticCell<T> {}

    impl<T> StaticCell<T> {
        const fn new(value: T) -> Self {
            Self(UnsafeCell::new(value))
        }

        fn get(&self) -> *mut T {
            self.0.get()
        }
    }

    struct UartInterrupt {
        rx_storage: StaticCell<[u8; BUFFER_SIZE]>,
        tx_storage: StaticCell<[u8; BUFFER_SIZE]>,
        rx_ring: StaticCell<MaybeUninit<RingBufferNoAlloc<u8>>>,
        tx_ring: StaticCell<MaybeUninit<RingBufferNoAlloc<u8>>>,
    }

    static UART: UartInterrupt = UartInterrupt {
        rx_storage: StaticCell::new([0; BUFFER_SIZE]),
        tx_storage: StaticCell::new([0; BUFFER_SIZE]),
        rx_ring: StaticCell::new(MaybeUninit::uninit()),
        tx_ring: StaticCell::new(MaybeUninit::uninit()),
    };

    impl UartInterrupt {
        unsafe fn init(&self) {
            unsafe {
                (*self.rx_ring.get()).write(RingBufferNoAlloc::from_raw_parts(
                    self.rx_storage.get().cast(),
                    BUFFER_SIZE,
                ));
                (*self.tx_ring.get()).write(RingBufferNoAlloc::from_raw_parts(
                    self.tx_storage.get().cast(),
                    BUFFER_SIZE,
                ));
            }
        }

        unsafe fn rx(&self) -> &mut RingBufferNoAlloc<u8> {
            unsafe { (&mut *self.rx_ring.get()).assume_init_mut() }
        }

        unsafe fn tx(&self) -> &mut RingBufferNoAlloc<u8> {
            unsafe { (&mut *self.tx_ring.get()).assume_init_mut() }
        }
    }

    #[inline(always)]
    fn reg(offset: usize) -> *mut u8 {
        (UART0_BASE + offset) as *mut u8
    }

    #[inline(always)]
    fn read_reg(offset: usize) -> u8 {
        unsafe { reg(offset).read_volatile() }
    }

    #[inline(always)]
    fn write_reg(offset: usize, value: u8) {
        unsafe { reg(offset).write_volatile(value) };
    }

    fn receive_available() {
        while read_reg(UART_LSR) & UART_LSR_DR != 0 {
            unsafe { UART.rx().push(read_reg(UART_RBR)) };
        }
    }

    fn transmit_available() {
        while read_reg(UART_LSR) & UART_LSR_THRE != 0 {
            match unsafe { UART.tx().pop() } {
                Some(byte) => write_reg(UART_THR, byte),
                None => {
                    let ier = read_reg(UART_IER);
                    write_reg(UART_IER, ier & !UART_IER_TX_EMPTY);
                    break;
                }
            }
        }
    }

    extern "C" fn uart_trap_handler(_ctx: *mut TrapContext) {
        loop {
            let iir = read_reg(UART_IIR);
            if iir & UART_IIR_NO_PENDING != 0 {
                break;
            }
            match iir & UART_IIR_ID_MASK {
                UART_IIR_RX_AVAILABLE | UART_IIR_RX_TIMEOUT => receive_available(),
                UART_IIR_TX_EMPTY => transmit_available(),
                UART_IIR_LINE_STATUS => {
                    let _ = read_reg(UART_LSR);
                }
                _ => break,
            }
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn uart_interupt_init() -> i32 {
        let _guard = GlobalIrqGuard::disable();
        write_reg(UART_IER, 0);
        write_reg(
            UART_FCR,
            UART_FCR_ENABLE | UART_FCR_CLEAR_RX | UART_FCR_CLEAR_TX,
        );
        unsafe { UART.init() };
        trap_set_external_handler(UART0_IRQ as usize, Some(uart_trap_handler));
        if enable_irq_source(irq_id_external(UART0_IRQ)).is_err() {
            return -1;
        }
        enable_irq(IRQ_MASK_EXTERNAL);
        write_reg(UART_IER, UART_IER_RX_AVAILABLE);
        0
    }

    pub fn raw_putc(c: u8) {
        let _guard = GlobalIrqGuard::disable();
        unsafe { UART.tx().push(c) };
        let ier = read_reg(UART_IER);
        write_reg(UART_IER, ier | UART_IER_TX_EMPTY);
    }

    pub fn raw_getc() -> u8 {
        loop {
            {
                let _guard = GlobalIrqGuard::disable();
                if let Some(byte) = unsafe { UART.rx().pop() } {
                    return byte;
                }
            }
            core::hint::spin_loop();
        }
    }

    #[unsafe(export_name = "raw_putc")]
    pub extern "C" fn raw_putc_cabi(c: c_char) {
        raw_putc(c as u8);
    }

    #[unsafe(export_name = "raw_getc")]
    pub extern "C" fn raw_getc_cabi() -> c_char {
        raw_getc() as c_char
    }
}

#[cfg(all(SHYOS_UART_INTERRUPT, not(target_os = "linux")))]
pub use interrupt::{raw_getc, raw_putc, uart_interupt_init};
