/* generated by gpt-5.6-sol<noreply@openai.com> @ cursor
 * 中断 UART provider；ABI 入口见 uart.h。
 */
#ifndef SHYOS_UART_INTERUPT_H
#define SHYOS_UART_INTERUPT_H

#include "uart.h"

#endif /* SHYOS_UART_INTERUPT_H */
