//generated by gpt-5.6-sol<noreply@openai.com> @ codex
//宿主行为测试，不参与裸机镜像

#include "../string_noalloc.h"

#define CHECK(condition) do { if (!(condition)) return __LINE__; } while (0)

i32 main(void) {
    u8 bytes[] = {1, 2, 3, 2, 0};
    u8 copy[5] = {0};
    char text[] = "  one,,three  ";
    char tokens[] = "one,,three";
    char fields[] = "one,,three";
    char output[8] = {0};
    char *save = NULL;
    char *cursor = fields;

    CHECK(memcpy(copy, bytes, sizeof(bytes)) == copy);
    CHECK(memcmp(copy, bytes, sizeof(bytes)) == 0);
    CHECK(memchr(bytes, 2, sizeof(bytes)) == bytes + 1);
    CHECK(memrchr(bytes, 2, sizeof(bytes)) == bytes + 3);
    CHECK(memmem(bytes, sizeof(bytes), bytes + 1, 2) == bytes + 1);
    memzero_explicit(copy, sizeof(copy));
    CHECK(memcmp(copy, "\0\0\0\0\0", sizeof(copy)) == 0);

    CHECK(strlen("Alpha/Beta") == 10);
    CHECK(strnlen("Alpha", 3) == 3);
    CHECK(strcmp("abc", "abc") == 0);
    CHECK(strncmp("abc", "abd", 2) == 0);
    CHECK(strcasecmp_ascii("Alpha", "aLPHa") == 0);
    CHECK(strncasecmp_ascii("Alpha", "ALPzz", 3) == 0);
    CHECK(strchr("abc", 'b') != NULL);
    CHECK(strrchr("abcb", 'b') == strchr("abcb", 'b') + 2);
    CHECK(*strchrnul("abc", 'x') == '\0');
    CHECK(strnchr("abc", 2, 'c') == NULL);
    CHECK(strstr("abcabc", "cab") != NULL);
    CHECK(strnstr("abcabc", "cab", 4) == NULL);
    CHECK(strnstr("abcabc", "cab", 5) != NULL);
    CHECK(strcasestr_ascii("AlphaBeta", "bETA") != NULL);
    CHECK(strspn("aaab", "a") == 3);
    CHECK(strcspn("abc:", ":") == 3);
    CHECK(strpbrk("abc", "xzcy") == strchr("abc", 'c'));
    CHECK(strstarts("prefix-value", "prefix"));
    CHECK(strends("prefix-value", "value"));

    CHECK(strlcpy(output, "abcdefghi", sizeof(output)) == 9);
    CHECK(strcmp(output, "abcdefg") == 0);
    CHECK(strscpy(output, "ok", sizeof(output)) == 2);
    CHECK(strlcat(output, "!", sizeof(output)) == 3);
    CHECK(strcmp(output, "ok!") == 0);
    CHECK(stpcpy(output, "end") == output + 3);

    CHECK(strcmp(skip_spaces(text), "one,,three  ") == 0);
    CHECK(strcmp(strim(text), "one,,three") == 0);
    CHECK(strcmp(kbasename("/boot/kernel.bin"), "kernel.bin") == 0);

    CHECK(strcmp(strtok_r(tokens, ",", &save), "one") == 0);
    CHECK(strcmp(strtok_r(NULL, ",", &save), "three") == 0);
    CHECK(strtok_r(NULL, ",", &save) == NULL);

    CHECK(strcmp(strsep(&cursor, ","), "one") == 0);
    CHECK(strcmp(strsep(&cursor, ","), "") == 0);
    CHECK(strcmp(strsep(&cursor, ","), "three") == 0);
    CHECK(strsep(&cursor, ",") == NULL);

    return 0;
}
