//generated by gpt-5<noreply@openai.com> @ codex
#include "queue.h"

#include "alloc.h"

ResultQueue queue_new(TypeDesc elem)
{
	ResultDeque result = deque_new(elem);
	Queue queue;

	if (Deque_is_err(&result)) {
		return QueueErr(Deque_error(&result));
	}
	queue.data = Deque_unwrap(&result);
	return QueueOk(queue);
}

usize queue_len(const Queue *queue)
{
	return deque_len(&queue->data);
}

usize queue_capacity(const Queue *queue)
{
	return deque_capacity(&queue->data);
}

bool queue_is_empty(const Queue *queue)
{
	return deque_is_empty(&queue->data);
}

i32 queue_reserve(Queue *queue, usize additional)
{
	return deque_reserve(&queue->data, additional);
}

i32 queue_push(Queue *queue, void *value)
{
	return deque_push_back(&queue->data, value);
}

i32 queue_push_raw(Queue *queue, const void *value)
{
	return deque_push_back_raw(&queue->data, value);
}

i32 queue_pop(Queue *queue, void *out)
{
	return deque_pop_front(&queue->data, out);
}

const void *queue_front(const Queue *queue)
{
	return deque_front(&queue->data);
}

void *queue_front_mut(Queue *queue)
{
	return deque_front_mut(&queue->data);
}

const void *queue_back(const Queue *queue)
{
	return deque_back(&queue->data);
}

void *queue_back_mut(Queue *queue)
{
	return deque_back_mut(&queue->data);
}

void queue_clear(Queue *queue)
{
	deque_clear(&queue->data);
}

void queue_drop(void *self)
{
	Queue *queue = self;

	deque_drop(&queue->data);
	memset(queue, 0, sizeof(*queue));
}

void *queue_clone_obj(const void *source_ptr)
{
	const Queue *source = source_ptr;
	Queue *copy;
	ResultDeque data;

	copy = malloc(sizeof(*copy));
	if (copy == NULL) {
		return NULL;
	}
	data = deque_clone(&source->data);
	if (Deque_is_err(&data)) {
		free(copy);
		return NULL;
	}
	copy->data = Deque_unwrap(&data);
	return copy;
}

ResultQueue queue_clone(const Queue *source)
{
	Queue *copy = queue_clone_obj(source);
	Queue value;

	if (copy == NULL) {
		return QueueErr(ERROR_OUT_OF_MEMORY);
	}
	value = *copy;
	memset(copy, 0, sizeof(*copy));
	free(copy);
	return QueueOk(value);
}
