//generated by gpt-5<noreply@openai.com> @ codex
#ifndef SHYOS_QUEUE_H
#define SHYOS_QUEUE_H

#include "deque.h"

typedef struct Queue Queue;
struct Queue {
	Deque data;
};

void queue_drop(void *self);
void *queue_clone_obj(const void *source);

IMPL_SHY_OWNED_RESULT(Queue, queue_drop, queue_clone_obj)

ResultQueue queue_new(TypeDesc elem);
ResultQueue queue_clone(const Queue *source);

usize queue_len(const Queue *queue);
usize queue_capacity(const Queue *queue);
bool queue_is_empty(const Queue *queue);

i32 queue_reserve(Queue *queue, usize additional);
i32 queue_push(Queue *queue, void *value);
i32 queue_push_raw(Queue *queue, const void *value);
i32 queue_pop(Queue *queue, void *out);
const void *queue_front(const Queue *queue);
void *queue_front_mut(Queue *queue);
const void *queue_back(const Queue *queue);
void *queue_back_mut(Queue *queue);
void queue_clear(Queue *queue);

#endif /* SHYOS_QUEUE_H */
