/* generated by grok-4.5<noreply@x.ai> @ cursor
 * linux_user：CLOCK_MONOTONIC 毫秒时间戳（相对 init_time）。
 * set_timer 不在本层；由 05task/timer 按 backend 接线（中断 / epoll 等）。
 */
#include "time.h"

#include "board.h"

#if !defined(SHYOS_BACKEND_LINUX_USER)
#error "time_linux_user.c requires SHYOS_BACKEND_LINUX_USER"
#endif

#ifndef CLOCK_MONOTONIC
#define CLOCK_MONOTONIC 1
#endif

struct shy_timespec {
	i64 tv_sec;
	i64 tv_nsec;
};

static u64 time_base_ms;

static u64 monotonic_ms(void)
{
	struct shy_timespec ts;

	(void)linux_syscall(
		__NR_clock_gettime, CLOCK_MONOTONIC, (long)&ts, 0, 0, 0, 0);
	return (u64)ts.tv_sec * 1000ULL + (u64)ts.tv_nsec / 1000000ULL;
}

void init_time(void)
{
	time_base_ms = monotonic_ms();
}

u64 get_time(void)
{
	return monotonic_ms() - time_base_ms;
}
