/* generated by grok-4.5<noreply@x.ai> @ cursor
 * 架构时间 ABI：
 *   init_time / get_time —— 各 backend 均提供（开机/初始化后毫秒）
 *   set_timer            —— 仅 QEMU virt 提供底层 deadline（SBI）；
 *                          软件定时与中断/epoll 接线在 05task/timer。
 */
#ifndef SHYOS_TIME_H
#define SHYOS_TIME_H

#include "shy_type.h"

#ifdef __cplusplus
extern "C" {
#endif

void init_time(void);
u64 get_time(void);

#if defined(SHYOS_BACKEND_QEMU_VIRT)
void set_timer(u64 ms);
#endif

#ifdef __cplusplus
}
#endif

#endif /* SHYOS_TIME_H */
