/* generated by grok-4.5<noreply@x.ai> @ pi
 * runtime 启动钩子：仅由启动路径调用。
 * 不是可 patch 的 hook；行为在 init.c 里用条件编译维护。
 *
 *   _start / 宿主入口
 *     -> _shy_os_init()
 *     -> main()
 */

#ifndef SHYOS_ARCH_INIT_H
#define SHYOS_ARCH_INIT_H

#ifdef __cplusplus
extern "C" {
#endif

void _shy_os_init(void);

#ifdef __cplusplus
}
#endif

#endif /* SHYOS_ARCH_INIT_H */
