/* generated by grok-4.5<noreply@x.ai> @ pi
 * 00arch runtime init。
 *
 * 启动路径专用，不作为普通库 API，也不用 weak 覆盖：
 *   QEMU virt : init.S → _shy_os_init() → main() → shutdown()
 *   Linux user: 宿主 CRT 进入 main 前，constructor 调 _shy_os_init()
 *
 * 行为只通过条件编译维护：
 *   SHYOS_ALLOCATOR_NONE  -> 空
 *   否则                  -> heap_init(HEAP_START, HEAP_SIZE)
 *
 * board 约定：
 *   HEAP_START != NULL  => 使用给定线性区
 *   HEAP_START == NULL  => simple_alloc 用 brk/sbrk 向宿主申请 arena
 */

#include "init.h"

#if !defined(SHYOS_ALLOCATOR_NONE)
#include "alloc.h"
#include "board.h"
#endif


#if defined(SHYOS_02)&&!defined(SHYOS_BACKEND_LINUX_USER)
/*前向声明 trap_entry符号*/
//HACK: 这里应当改为注册或者配置机制，而非低层知道高层
void trap_entry(void);
i32 init_trap_entry(usize entry);
#endif


void _shy_os_init(void)
{
#if !defined(SHYOS_ALLOCATOR_NONE)
	//内存分配器
	(void)heap_init(HEAP_START, (usize)HEAP_SIZE);
#endif

#if defined(SHYOS_02)&&!defined(SHYOS_BACKEND_LINUX_USER)
	/*需init trap*/

	init_trap_entry((usize)trap_entry);
#endif
}

#if defined(SHYOS_BACKEND_LINUX_USER)
/* 宿主 CRT 不会走裸机 init.S，用 constructor 在 main 前完成同一钩子。 */
__attribute__((constructor(101))) static void shyos_linux_premain(void)
{
	_shy_os_init();
}
#endif
